import { createClient, type Session, type SupabaseClient } from '@supabase/supabase-js'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Download, FileUp, LogOut, RefreshCw, ShieldAlert, UserRoundCog } from 'lucide-react'
import App, { type CloudControls } from '../App'
import type { ExportBundle } from '../types'
import { writeCloudCache } from './cache'
import { readAuthCallbackError, readSupabaseConfig, type SupabaseBrowserConfig } from './config'
import type { Membership, OrganizationSummary, WorkspaceRole } from './contracts'
import { inspectMigrationSource, readLocalMigrationSource, verifyRawReadback, type InspectedMigrationSource, type RawMigrationSource } from './migration'
import { CloudRepositoryError, SupabaseWorkspaceRepository, type LoadedWorkspace } from './repository'
import type { Database } from './database.types'

const LOCAL_ORG_KEY='nexus.cloud.organization.v1'
const message=(cause:unknown)=>cause instanceof Error?cause.message:'不明なエラーが発生しました'
const rememberedOrganization=()=>{try{return localStorage.getItem(LOCAL_ORG_KEY)}catch{return null}}
const rememberOrganization=(id:string)=>{try{localStorage.setItem(LOCAL_ORG_KEY,id)}catch{/* workspace preference is best-effort */}}
const downloadRaw=(raw:string,prefix='nexus-ops-migration-source')=>{const url=URL.createObjectURL(new Blob([raw],{type:'application/json'})),anchor=document.createElement('a');anchor.href=url;anchor.download=`${prefix}-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url)}
const downloadBundle=(bundle:ExportBundle,prefix='nexus-ops-unsaved')=>downloadRaw(JSON.stringify(bundle,null,2),prefix)
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

function Screen({title,children}:{title:string;children:React.ReactNode}){return <main className="cloud-screen"><div className="cloud-card"><div className="brand-mark" aria-hidden="true">N</div><span className="eyebrow">NEXUS OPS / SUPABASE</span><h1>{title}</h1>{children}</div></main>}
function MissingConfig(){return <Screen title="共有接続が設定されていません"><p>この公開版はSupabaseのProject URLとpublishable keyが必要です。秘密鍵、service role、DB passwordは設定しないでください。</p><dl className="config-list"><div><dt>必要な変数</dt><dd>VITE_SUPABASE_URL</dd></div><div><dt>必要な変数</dt><dd>VITE_SUPABASE_PUBLISHABLE_KEY</dd></div></dl></Screen>}

function Login({client,config,callbackError}:{client:SupabaseClient<Database>;config:SupabaseBrowserConfig;callbackError:string}){
  const [email,setEmail]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(callbackError)
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');const {error:authError}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:config.redirectTo,shouldCreateUser:false}});setBusy(false);if(authError){setError(authError.message);return}setNotice('招待済みのアドレスであれば、ログインリンクを送信しました。')}
  return <Screen title="共有ワークスペースへログイン"><p>招待済みのメールアドレスを入力してください。未登録アカウントは作成されません。</p><p className="public-boundary-note">S4静的正本と初期73タスク本文は公開情報です。ログイン後の更新状態と共有編集データはSupabase Auth/RLSで保護されます。</p><form className="auth-form" onSubmit={submit}><label htmlFor="auth-email">メールアドレス</label><input id="auth-email" type="email" autoComplete="email" required value={email} onChange={(event)=>setEmail(event.target.value)}/><button className="button primary" disabled={busy}>{busy?'送信中…':'マジックリンクを送信'}</button></form>{notice&&<p role="status" className="cloud-success">{notice}</p>}{error&&<p role="alert" className="cloud-error">{error}</p>}<p className="cloud-help">リンクはこのサイトの <code>{new URL(config.redirectTo).pathname}</code> に戻ります。</p></Screen>
}

function MigrationPreparation({workspace,repository,onImported,onReload,onSignOut}:{workspace:LoadedWorkspace;repository:SupabaseWorkspaceRepository;onImported:(value:LoadedWorkspace)=>void;onReload:()=>void;onSignOut:()=>void}){
  const [source,setSource]=useState<InspectedMigrationSource|null>(null),[backupDownloaded,setBackupDownloaded]=useState(false),[backupVerified,setBackupVerified]=useState(false),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const inspect=useCallback(async(rawSource:RawMigrationSource)=>{setError('');setBackupDownloaded(false);setBackupVerified(false);setSource(await inspectMigrationSource(rawSource))},[])
  useEffect(()=>{const local=readLocalMigrationSource();if(local)void inspect(local)},[inspect])
  const choose=async(file?:File)=>{if(!file)return;await inspect({storageKey:'manual-file-upload',raw:await file.text(),sourceOrigin:'manual-file-upload'})}
  const verifyBackup=async(file?:File)=>{if(!file||!source)return;const ok=await verifyRawReadback(source,file);setBackupVerified(ok);setError(ok?'':'再選択したバックアップが移行元rawと完全一致しません')}
  const importNow=async()=>{if(!source?.prepared)return;setBusy(true);setError('');try{const result=await repository.importV4(source.prepared,workspace.organization.id);onImported(result);setNotice(result.cacheWarning?`移行は完了しました（${result.cacheWarning}）`:'移行とserver read-back検証が完了しました')}catch(cause){setError(message(cause))}finally{setBusy(false)}}
  const owner=workspace.organization.role==='owner',remoteEmpty=!workspace.entities.length&&workspace.importState.status==='empty'&&workspace.importState.manifestCount===0,confirmed=confirmation===workspace.organization.name||confirmation===workspace.organization.slug,canImport=owner&&remoteEmpty&&!!source?.prepared&&backupDownloaded&&backupVerified&&confirmed&&!busy
  return <Screen title="クラウド移行の準備が必要です"><div className="cloud-status"><b>{workspace.organization.name}</b><span>{workspace.organization.role}</span><span>{workspace.organization.status}</span></div><p>既存のローカル正本を自動上書きしません。rawバックアップの保存と再読込、移行先、remote空状態を確認してからownerが1回だけimportします。</p><dl className="config-list"><div><dt>organization</dt><dd>{workspace.organization.name} / {workspace.organization.id}</dd></div><div><dt>remote</dt><dd>{workspace.entities.length} entities / {workspace.importState.status} / manifest {workspace.importState.manifestCount}</dd></div>{source&&<><div><dt>移行元</dt><dd>{source.storageKey} / {source.sourceSize} bytes</dd></div><div><dt>raw SHA-256</dt><dd><code>{source.rawSha256}</code></dd></div>{source.prepared&&<><div><dt>semantic fingerprint</dt><dd><code>{source.prepared.semanticFingerprint}</code></dd></div><div><dt>source</dt><dd>{source.prepared.sourceEntityCount} entities / tasks {source.prepared.bundle.tasks.length}</dd></div></>}</>}</dl><div className="migration-actions">{source&&<button className="button ghost" onClick={()=>{downloadRaw(source.raw);setBackupDownloaded(true)}}><Download size={16}/>rawバックアップを保存</button>}<label className="button ghost" htmlFor="migration-json"><FileUp size={16}/>別の移行JSONを選択</label><input className="sr-only" id="migration-json" type="file" accept="application/json,.json" onChange={(event)=>void choose(event.target.files?.[0])}/><label className="button ghost" htmlFor="migration-readback"><FileUp size={16}/>保存したrawを再読込</label><input className="sr-only" id="migration-readback" type="file" accept="application/json,.json" onChange={(event)=>void verifyBackup(event.target.files?.[0])}/><button className="button ghost" onClick={onReload}><RefreshCw size={16}/>remoteを再確認</button><button className="button ghost" onClick={onSignOut}><LogOut size={16}/>ログアウト</button></div>{source?.error&&<p role="alert" className="cloud-error">rawバックアップは保存できますが、移行データとして不正です: {source.error}</p>}{!source&&<p role="status">このoriginに移行元がありません。移行JSONを選択してください。</p>}{source?.prepared&&<div className="migration-summary"><b>schema v4検証済み</b><span>raw保存 {backupDownloaded?'済':'未'} / raw再読込 {backupVerified?'一致':'未確認'} / remote {remoteEmpty?'空':'空ではない'}</span><label htmlFor="migration-confirm">移行先確認としてorganization名またはslugを入力</label><input id="migration-confirm" value={confirmation} onChange={(event)=>setConfirmation(event.target.value)} placeholder={workspace.organization.name}/><button className="button primary" disabled={!canImport} onClick={()=>void importNow()}>ownerとして初回importを実行</button></div>}{!owner&&<p role="status">現在のroleではimportできません。ownerへ実行を依頼してください。</p>}{notice&&<p role="status" className="cloud-success">{notice}</p>}{error&&<p role="alert" className="cloud-error">{error}</p>}<p className="cloud-help">既存の <code>nexus.bundle.v4</code> は移行元として削除・更新しません。</p></Screen>
}

function MembershipManager({workspace,repository,sessionUserId,onConfirmed,onFailure}:{workspace:LoadedWorkspace;repository:SupabaseWorkspaceRepository;sessionUserId:string;onConfirmed:(workspace:LoadedWorkspace)=>void;onFailure:(cause:unknown)=>void}){
  const [open,setOpen]=useState(false),[memberships,setMemberships]=useState<Membership[]>([]),[userId,setUserId]=useState(''),[role,setRole]=useState<WorkspaceRole>('editor'),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const load=useCallback(async()=>{if(workspace.organization.role!=='owner')return;setBusy(true);setError('');try{setMemberships(await repository.listMemberships(workspace.organization.id))}catch(cause){setError(message(cause));onFailure(cause)}finally{setBusy(false)}},[onFailure,repository,workspace.organization.id,workspace.organization.role])
  useEffect(()=>{if(open)void load()},[load,open])
  if(workspace.organization.role!=='owner')return null
  const mutate=async(targetUserId:string,nextRole:WorkspaceRole|null,action:'upsert'|'remove',expectedMembershipVersion:number)=>{if(targetUserId===sessionUserId){setError('現在ログイン中の自分自身はこの画面から変更できません');return}setBusy(true);setError('');try{const result=await repository.manageMembership(workspace.organization.id,{userId:targetUserId,role:nextRole,action,expectedMembershipVersion});setMemberships(result.memberships);onConfirmed(result.workspace);if(action==='upsert'&&targetUserId===userId)setUserId('')}catch(cause){setError(message(cause));onFailure(cause)}finally{setBusy(false)}}
  const add=()=>{if(!uuid.test(userId)){setError('Auth user UUIDを正しい形式で入力してください');return}const existing=memberships.find((item)=>item.userId===userId);void mutate(userId,role,'upsert',existing?.version??0)}
  return <section className="membership-manager" aria-labelledby="membership-title"><button className="button ghost" onClick={()=>setOpen((value)=>!value)}><UserRoundCog size={16}/>membership管理</button>{open&&<div><h2 id="membership-title">organization membership</h2><p>メールアドレスではなく、確認済みAuth user UUIDを使用します。更新はstate versionとmembership versionの両方で競合検知します。</p><div className="membership-form"><label htmlFor="member-user-id">Auth user UUID</label><input id="member-user-id" value={userId} onChange={(event)=>setUserId(event.target.value.trim())}/><select aria-label="新しいmembership role" value={role} onChange={(event)=>setRole(event.target.value as WorkspaceRole)}><option value="owner">owner</option><option value="editor">editor</option><option value="viewer">viewer</option></select><button className="button primary" disabled={busy} onClick={add}>追加・更新</button></div><ul>{memberships.map((member)=><li key={member.userId}><code>{member.userId}</code><span>{member.role} / v{member.version}</span><select aria-label={`${member.userId}のrole`} defaultValue={member.role} disabled={busy||member.userId===sessionUserId} onChange={(event)=>void mutate(member.userId,event.target.value as WorkspaceRole,'upsert',member.version)}><option value="owner">owner</option><option value="editor">editor</option><option value="viewer">viewer</option></select><button className="button ghost" disabled={busy||member.userId===sessionUserId} onClick={()=>{if(confirm(`${member.userId} のmembershipを削除しますか？`))void mutate(member.userId,null,'remove',member.version)}}>削除</button></li>)}</ul>{error&&<p role="alert" className="cloud-error">{error}</p>}</div>}</section>
}

function PendingRecoveryList({pending,organizations,onDiscard}:{pending:Record<string,ExportBundle>;organizations:OrganizationSummary[];onDiscard:(organizationId:string)=>void}){
  const entries=Object.entries(pending);if(!entries.length)return null
  return <section className="pending-recovery-list" aria-labelledby="pending-recovery-title"><div><b id="pending-recovery-title">未保存候補の回収</b><span>アクセス失効後もorganization ID単位で書き出しまたは破棄できます。</span></div><ul>{entries.map(([organizationId,bundle])=><li key={organizationId}><span>{organizations.find((organization)=>organization.id===organizationId)?.name??'アクセス失効済みorganization'}</span><code>{organizationId}</code><button className="button ghost" onClick={()=>downloadBundle(bundle,`nexus-ops-unsaved-${organizationId}`)}><Download size={16}/>書き出す</button><button className="button ghost" onClick={()=>onDiscard(organizationId)}>破棄</button></li>)}</ul></section>
}

function Connected({client,session}:{client:SupabaseClient<Database>;session:Session}){
  const repository=useMemo(()=>new SupabaseWorkspaceRepository(client),[client]),[organizations,setOrganizations]=useState<OrganizationSummary[]>([]),[selected,setSelected]=useState(''),[workspace,setWorkspace]=useState<LoadedWorkspace|null>(null),[pendingByOrganization,setPendingByOrganization]=useState<Record<string,ExportBundle>>({}),[busy,setBusy]=useState(true),[error,setError]=useState(''),[canvasDirty,setCanvasDirty]=useState(false)
  const requestRef=useRef(0),selectedRef=useRef(''),canvasDirtyRef=useRef(false);selectedRef.current=selected;canvasDirtyRef.current=canvasDirty
  const signOut=useCallback(()=>void client.auth.signOut(),[client])
  const accept=useCallback((value:LoadedWorkspace)=>{setWorkspace(value);if(!value.bundle)return'';const cached=writeCloudCache(value.organization.id,value.organization.stateVersion,value.bundle);return cached.ok?'':`クラウド読込みは成功しましたがcacheを更新できません: ${cached.error??'不明なエラー'}`},[])
  const loadOrganizations=useCallback(async()=>{setBusy(true);setError('');try{const list=await repository.listOrganizations();setOrganizations(list);const remembered=rememberedOrganization(),next=list.find((item)=>item.id===remembered)?.id??list[0]?.id??'';setSelected(next);if(next){const value=await repository.read(next);setError(accept(value))}else setWorkspace(null)}catch(cause){if(cause instanceof CloudRepositoryError&&cause.kind==='session_expired')signOut();setError(message(cause));setWorkspace(null)}finally{setBusy(false)}},[accept,repository,signOut])
  const accessRevoked=useCallback(async()=>{const revoked=selectedRef.current;if(revoked)repository.forget(revoked);setWorkspace(null);setError('organizationへのアクセス権が失効したためworkspaceを閉じました');try{const list=await repository.listOrganizations();setOrganizations(list);const next=list[0]?.id??'';setSelected(next);if(next){const value=await repository.read(next);setError(accept(value))}}catch(cause){setOrganizations([]);setSelected('');setError(message(cause))}},[accept,repository])
  const handleError=useCallback((cause:unknown)=>{if(cause instanceof CloudRepositoryError&&cause.kind==='session_expired'){signOut();return}if(cause instanceof CloudRepositoryError&&cause.kind==='access_revoked'){void accessRevoked();return}setError(message(cause))},[accessRevoked,signOut])
  const reload=useCallback(async(force=false)=>{if(canvasDirty){setError('キャンバスが未保存のためremote snapshot反映を停止しました。先にキャンバスを保存してください。');return}if(!selected||pendingByOrganization[selected]&&!force)return;const request=++requestRef.current;try{const value=await repository.read(selected,false);if(request===requestRef.current&&!canvasDirtyRef.current){repository.adopt(value);setError(accept(value))}else if(canvasDirtyRef.current)setError('remote読込み中にキャンバスが変更されたためsnapshot反映を停止しました。保存または破棄してから再読込してください。')}catch(cause){if(request===requestRef.current)handleError(cause)}},[accept,canvasDirty,handleError,pendingByOrganization,repository,selected])
  useEffect(()=>{void loadOrganizations()},[loadOrganizations])
  useEffect(()=>{if(!selected)return;rememberOrganization(selected);const timer=setInterval(()=>{if(document.visibilityState==='visible')void reload()},15_000),focus=()=>void reload(),visibility=()=>{if(document.visibilityState==='visible')void reload()};addEventListener('focus',focus);document.addEventListener('visibilitychange',visibility);return()=>{clearInterval(timer);removeEventListener('focus',focus);document.removeEventListener('visibilitychange',visibility)}},[reload,selected])
  const choose=async(id:string)=>{if(canvasDirty){setError('キャンバスが未保存のためorganization切替を停止しました。');return}setSelected(id);setBusy(true);setError('');try{const value=await repository.read(id);setError(accept(value));rememberOrganization(id)}catch(cause){setWorkspace(null);handleError(cause)}finally{setBusy(false)}}
  const setPending=(candidate:ExportBundle|null)=>setPendingByOrganization((current)=>{const next={...current};if(candidate)next[selected]=candidate;else delete next[selected];return next})
  const pending=pendingByOrganization[selected]??null
  const discardPending=(organizationId:string)=>setPendingByOrganization((current)=>{const next={...current};delete next[organizationId];return next}),recovery=<PendingRecoveryList pending={pendingByOrganization} organizations={organizations} onDiscard={discardPending}/>
  if(busy&&!workspace)return <>{recovery}<Screen title="共有データを確認しています"><p role="status">sessionとorganization membershipを確認中です…</p></Screen></>
  if(error&&!workspace)return <>{recovery}<Screen title="共有データを読み込めません"><p role="alert" className="cloud-error">{error}</p><div className="migration-actions"><button className="button primary" onClick={()=>void loadOrganizations()}>再試行</button><button className="button ghost" onClick={signOut}>ログアウト</button></div></Screen></>
  if(!organizations.length)return <>{recovery}<Screen title="利用できるorganizationがありません"><p>認証は完了していますが、有効なmembershipがありません。管理者が確認済みAuth user UUIDをmembershipへ追加する必要があります。</p><button className="button ghost" onClick={signOut}><LogOut size={16}/>ログアウト</button></Screen></>
  if(!workspace)return null
  if(workspace.organization.status==='archived')return <>{recovery}<Screen title="このorganizationはアーカイブ済みです"><p>共有データは変更できません。管理者にactive状態を確認してください。</p><div className="migration-actions"><button className="button ghost" onClick={()=>void reload(true)}>再確認</button><button className="button ghost" onClick={signOut}>ログアウト</button></div></Screen></>
  if(!workspace.bundle)return <>{recovery}<MigrationPreparation workspace={workspace} repository={repository} onImported={accept} onReload={()=>void reload(true)} onSignOut={signOut}/></>
  const controls:CloudControls={repository,workspace,pendingCandidate:pending,onPending:setPending,onConfirmed:setWorkspace,onReload:reload,onSignOut:signOut,onSessionExpired:signOut,onAccessRevoked:accessRevoked,onCanvasDirty:setCanvasDirty,organizations,selectedOrganizationId:selected,onSelectOrganization:choose,userEmail:session.user.email??'認証済みユーザー'}
  return <>{recovery}<MembershipManager workspace={workspace} repository={repository} sessionUserId={session.user.id} onConfirmed={setWorkspace} onFailure={handleError}/><App key={workspace.organization.id} initialBundle={workspace.bundle} cloud={controls}/>{error&&<div className="toast error" role="alert">{error}</div>}</>
}

export default function CloudRoot(){
  const callbackError=useMemo(()=>readAuthCallbackError(window.location),[]),config=useMemo(()=>readSupabaseConfig(),[]),client=useMemo(()=>config?createClient<Database>(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null,[config]),[session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[error,setError]=useState(callbackError)
  useEffect(()=>{if(callbackError)history.replaceState(history.state,'',location.pathname);if(!client){setReady(true);return}let active=true;void client.auth.getSession().then(({data,error:sessionError})=>{if(!active)return;if(sessionError)setError(sessionError.message);setSession(data.session);setReady(true)});const {data:{subscription}}=client.auth.onAuthStateChange((_event,next)=>{if(!active)return;setSession(next);setReady(true)});return()=>{active=false;subscription.unsubscribe()}},[callbackError,client])
  if(!config)return import.meta.env.PROD?<MissingConfig/>:<><div className="local-mode-note" role="note"><ShieldAlert size={16}/><span>Supabase未設定のため、開発用ローカルモードです。共有はされません。</span></div><App/></>
  if(!ready)return <Screen title="sessionを復元しています"><p role="status">認証状態を確認中です…</p></Screen>
  if(error&&session)return <Screen title="認証状態を確認できません"><p role="alert" className="cloud-error">{error}</p><button className="button ghost" onClick={()=>{setError('');void client?.auth.signOut()}}>ログイン画面へ戻る</button></Screen>
  return session?<Connected client={client!} session={session}/>:<Login client={client!} config={config} callbackError={error}/>
}
