// Derived from supabase/migrations/20260817144520_nexus_ops_shared_schema.sql.
// CI regenerates the public schema from a reset local database and checks this
// surface in both directions. Regenerate again after every remote migration.
export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[]
type Relationship={foreignKeyName:string;columns:string[];isOneToOne:boolean;referencedRelation:string;referencedColumns:string[]}
type Table<Row,Insert,Update,Relationships extends Relationship[]>={Row:Row;Insert:Insert;Update:Update;Relationships:Relationships}

type OrganizationsRow={id:string;name:string;slug:string;status:string;state_version:number;created_at:string;updated_at:string;created_by:string;updated_by:string}
type OrganizationMembershipsRow={organization_id:string;user_id:string;role:string;version:number;created_at:string;updated_at:string;created_by:string;updated_by:string}
type EntityRecordsRow={organization_id:string;entity_type:string;entity_id:string;payload:Json;ordinal:number;semantic_fingerprint:string|null;version:number;created_at:string;updated_at:string;created_by:string;updated_by:string}
type EntityRecordLinksRow={organization_id:string;from_entity_type:string;from_entity_id:string;link_kind:string;to_entity_type:string;to_entity_id:string;created_at:string;created_by:string}
type ImportManifestsRow={id:string;organization_id:string;run_id:string;source_schema:number;source_origin:string;source_size:number;source_entity_count:number;raw_sha256:string;semantic_fingerprint:string;status:string;imported_at:string;imported_by:string}
type MutationRunsRow={organization_id:string;run_id:string;operation:string;request_payload:Json;request_fingerprint:string;result:Json;actor_user_id:string;completed_at:string}
type ServerAuditEventsRow={event_id:number;organization_id:string;run_id:string;event_index:number;action:string;entity_type:string|null;entity_id:string|null;before_version:number|null;after_version:number|null;before_payload:Json|null;after_payload:Json|null;metadata:Json;actor_user_id:string;occurred_at:string}

export type Database={public:{Tables:{
  organizations:Table<OrganizationsRow,{id?:string;name:string;slug:string;status?:string;state_version?:number;created_at?:string;updated_at?:string;created_by:string;updated_by:string},{id?:string;name?:string;slug?:string;status?:string;state_version?:number;created_at?:string;updated_at?:string;created_by?:string;updated_by?:string},[]>
  organization_memberships:Table<OrganizationMembershipsRow,{organization_id:string;user_id:string;role:string;version?:number;created_at?:string;updated_at?:string;created_by:string;updated_by:string},{organization_id?:string;user_id?:string;role?:string;version?:number;created_at?:string;updated_at?:string;created_by?:string;updated_by?:string},[{foreignKeyName:'organization_memberships_organization_id_fkey';columns:['organization_id'];isOneToOne:false;referencedRelation:'organizations';referencedColumns:['id']}]>
  entity_records:Table<EntityRecordsRow,{organization_id:string;entity_type:string;entity_id:string;payload:Json;ordinal?:number;semantic_fingerprint?:string|null;version?:number;created_at?:string;updated_at?:string;created_by:string;updated_by:string},{organization_id?:string;entity_type?:string;entity_id?:string;payload?:Json;ordinal?:number;semantic_fingerprint?:string|null;version?:number;created_at?:string;updated_at?:string;created_by?:string;updated_by?:string},[{foreignKeyName:'entity_records_organization_id_fkey';columns:['organization_id'];isOneToOne:false;referencedRelation:'organizations';referencedColumns:['id']}]>
  entity_record_links:Table<EntityRecordLinksRow,{organization_id:string;from_entity_type:string;from_entity_id:string;link_kind?:string;to_entity_type:string;to_entity_id:string;created_at?:string;created_by:string},{organization_id?:string;from_entity_type?:string;from_entity_id?:string;link_kind?:string;to_entity_type?:string;to_entity_id?:string;created_at?:string;created_by?:string},[{foreignKeyName:'entity_record_links_organization_id_from_entity_type_from_entity_fkey';columns:['organization_id','from_entity_type','from_entity_id'];isOneToOne:false;referencedRelation:'entity_records';referencedColumns:['organization_id','entity_type','entity_id']},{foreignKeyName:'entity_record_links_organization_id_to_entity_type_to_entity_id_fkey';columns:['organization_id','to_entity_type','to_entity_id'];isOneToOne:false;referencedRelation:'entity_records';referencedColumns:['organization_id','entity_type','entity_id']}]>
  import_manifests:Table<ImportManifestsRow,{id?:string;organization_id:string;run_id:string;source_schema:number;source_origin:string;source_size:number;source_entity_count:number;raw_sha256:string;semantic_fingerprint:string;status?:string;imported_at?:string;imported_by:string},{id?:string;organization_id?:string;run_id?:string;source_schema?:number;source_origin?:string;source_size?:number;source_entity_count?:number;raw_sha256?:string;semantic_fingerprint?:string;status?:string;imported_at?:string;imported_by?:string},[{foreignKeyName:'import_manifests_organization_id_fkey';columns:['organization_id'];isOneToOne:false;referencedRelation:'organizations';referencedColumns:['id']}]>
  mutation_runs:Table<MutationRunsRow,{organization_id:string;run_id:string;operation:string;request_payload:Json;request_fingerprint:string;result:Json;actor_user_id:string;completed_at?:string},{organization_id?:string;run_id?:string;operation?:string;request_payload?:Json;request_fingerprint?:string;result?:Json;actor_user_id?:string;completed_at?:string},[{foreignKeyName:'mutation_runs_organization_id_fkey';columns:['organization_id'];isOneToOne:false;referencedRelation:'organizations';referencedColumns:['id']}]>
  server_audit_events:Table<ServerAuditEventsRow,{event_id?:never;organization_id:string;run_id:string;event_index:number;action:string;entity_type?:string|null;entity_id?:string|null;before_version?:number|null;after_version?:number|null;before_payload?:Json|null;after_payload?:Json|null;metadata?:Json;actor_user_id:string;occurred_at?:string},{event_id?:never;organization_id?:string;run_id?:string;event_index?:number;action?:string;entity_type?:string|null;entity_id?:string|null;before_version?:number|null;after_version?:number|null;before_payload?:Json|null;after_payload?:Json|null;metadata?:Json;actor_user_id?:string;occurred_at?:string},[{foreignKeyName:'server_audit_events_organization_id_fkey';columns:['organization_id'];isOneToOne:false;referencedRelation:'organizations';referencedColumns:['id']}]>
};Views:{[_ in never]:never};Functions:{
  rpc_organization_creation_capability:{Args:never;Returns:Json}
  rpc_create_organization:{Args:{p_name:string;p_slug:string;p_project_name:string;p_purpose:string;p_known_tasks:string;p_generator_version:string;p_workspace_config:Json;p_changes:Json;p_run_id:string};Returns:Json}
  rpc_update_workspace_settings:{Args:{p_organization_id:string;p_expected_state_version:number;p_workspace_profile:Json;p_workspace_config:Json;p_changes:Json;p_run_id:string};Returns:Json}
  rpc_bootstrap_organization:{Args:{p_name:string;p_slug:string;p_run_id:string};Returns:Json}
  rpc_list_my_organizations:{Args:never;Returns:Json}
  rpc_read_snapshot:{Args:{p_organization_id:string};Returns:Json}
  rpc_apply_changes:{Args:{p_organization_id:string;p_expected_state_version:number;p_changes:Json;p_run_id:string};Returns:Json}
  rpc_save_weekly:{Args:{p_organization_id:string;p_expected_state_version:number;p_changes:Json;p_run_id:string};Returns:Json}
  rpc_import_v4:{Args:{p_organization_id:string;p_expected_state_version:number;p_run_id:string;p_raw_sha256:string;p_semantic_fingerprint:string;p_source_origin:string;p_source_size:number;p_source_entity_count:number;p_entities:Json};Returns:Json}
  rpc_list_memberships:{Args:{p_organization_id:string};Returns:Json}
  rpc_manage_membership:{Args:{p_organization_id:string;p_user_id:string;p_role:string;p_action:string;p_expected_state_version:number;p_expected_membership_version:number;p_run_id:string};Returns:Json}
};Enums:{[_ in never]:never};CompositeTypes:{[_ in never]:never}}}

export type Tables<T extends keyof Database['public']['Tables']>=Database['public']['Tables'][T]['Row']
export type TablesInsert<T extends keyof Database['public']['Tables']>=Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']>=Database['public']['Tables'][T]['Update']
