import { describe, expect, it } from 'vitest'
import { initialAudit, initialEdges, initialKpis, initialNodes, initialTasks, initialViewport } from '../data'
import { validateBundle } from '../storage'
import type { ExportBundle } from '../types'
import { emptyWeeklyState, runWeeklyBundle } from '../weekly'
import { bundleToEntities, diffEntities, entitiesToBundle } from './entities'

const bundle=():ExportBundle=>({schemaVersion:4,exportedAt:'2026-08-17T00:00:00.000Z',tasks:structuredClone(initialTasks),taskResults:[],flow:{nodes:structuredClone(initialNodes),edges:structuredClone(initialEdges),viewport:structuredClone(initialViewport)},audit:structuredClone(initialAudit),kpis:structuredClone(initialKpis),reportBaseline:null,migrationArchive:[],weekly:emptyWeeklyState()})
const assertSqlPayload=(entity:ReturnType<typeof bundleToEntities>[number])=>{const payload=entity.payload as Record<string,unknown>;expect(payload.id,`${entity.entityType}:${entity.entityId}`).toBe(entity.entityId);expect(Object.keys(payload).length).toBeLessThanOrEqual(128);switch(entity.entityType){case'task':expect(payload).toMatchObject({title:expect.any(String),phase:expect.any(Number),teamId:expect.any(String),team:expect.any(String),rawTeam:expect.any(String),owner:expect.any(String),assignees:expect.any(Array),rawAssignees:expect.any(String),personKeys:expect.any(Array),urgency:expect.any(String),deadline:expect.any(String),status:expect.any(String),holdReason:expect.any(String),updatedAt:expect.any(String),dependencies:expect.any(Array),notes:expect.any(Array),sourceRefs:expect.any(Array)});break;case'flow_node':expect(payload).toMatchObject({position:{x:expect.any(Number),y:expect.any(Number)},data:expect.any(Object)});break;case'flow_edge':expect(payload).toMatchObject({source:expect.any(String),target:expect.any(String)});break;case'flow_viewport':expect(payload).toMatchObject({id:'singleton',x:expect.any(Number),y:expect.any(Number),zoom:expect.any(Number)});break;case'client_audit':expect(payload).toMatchObject({issueId:expect.any(String),classification:expect.any(String),targetVersion:expect.any(String),files:expect.any(Array),before:expect.any(String),after:expect.any(String),evidence:expect.any(Array),retest:expect.any(String),residualRisk:expect.any(String),round:expect.any(Number),at:expect.any(String),action:expect.any(String),detail:expect.any(String)});break;case'kpi':expect(payload).toMatchObject({label:expect.any(String),unit:expect.any(String),target:expect.any(Number)});expect(payload).toHaveProperty('actual');break;case'report_baseline':expect(payload.id).toBe('singleton');expect(payload).toHaveProperty('value');break;case'migration_archive':expect(payload).toMatchObject({fromSchema:expect.any(Number),migratedAt:expect.any(String),reason:expect.any(String),tasks:expect.any(Array)});break;case'weekly_run':expect(payload).toMatchObject({runId:entity.entityId,scheduledFor:expect.any(String),ranAt:expect.any(String),trigger:expect.stringMatching(/^(scheduled|catch-up|manual)$/),outcome:'success',missedWeekCount:expect.any(Number),addedStickyCount:expect.any(Number),autoTaskCount:expect.any(Number),reasons:expect.any(Array),snapshot:expect.any(Object)});break;case'weekly_completion':expect(payload).toMatchObject({taskId:entity.entityId,firstSeen:expect.any(String),lastConfirmed:expect.any(String),completedWeek:expect.any(String),basis:expect.stringMatching(/^(status-change|inferred-from-updatedAt)$/),currentStatus:expect.any(String)});break;case'weekly_tombstone':expect(payload).toMatchObject({fingerprint:entity.entityId});break;case'weekly_meta':expect(payload.id).toBe('singleton');expect(payload).toHaveProperty('lastRunId');break}}

describe('cloud entity adapter',()=>{
  it('reconstructs a schema v4 bundle and validates it',()=>{const source=bundle(),entities=bundleToEntities(source).map((entity)=>({...entity,version:1})),result=entitiesToBundle(entities,'2026-08-17T01:00:00.000Z');expect(result).toEqual({...source,exportedAt:'2026-08-17T01:00:00.000Z'})})
  it('creates versioned changes only for changed entities',()=>{const source=bundle(),entities=bundleToEntities(source).map((entity)=>({...entity,version:7})),candidate=structuredClone(source);candidate.tasks[0].status='進行中';candidate.tasks[0].updatedAt='2026-08-17T02:00:00.000Z';const changes=diffEntities(entities,candidate);expect(changes).toEqual([expect.objectContaining({entityType:'task',entityId:candidate.tasks[0].id,op:'upsert',expectedVersion:7})])})
  it('sends organization-scoped references for flow edges',()=>{const source=bundle(),changes=diffEntities([],source),edge=source.flow.edges[0],change=changes.find((value)=>value.entityType==='flow_edge'&&value.entityId===edge.id);expect(change?.references).toEqual([{kind:'source',entityType:'flow_node',entityId:edge.source},{kind:'target',entityType:'flow_node',entityId:edge.target}])})
  it('links valid task-targeted flow nodes, edges and every edge taskIds entry in the same diff batch',()=>{const source=bundle();source.flow.nodes.push({id:'task-target',position:{x:0,y:0},data:{label:'target',targetType:'task',targetId:'P0-01',taskId:'P0-01',taskIds:['P0-01']}});source.flow.edges.push({id:'task-edge',source:source.flow.nodes[0].id,target:'task-target',data:{taskId:'P0-02',targetType:'task',targetId:'P0-02',taskIds:['P0-01','P0-02']}});expect(validateBundle(source)).toEqual([]);const changes=diffEntities([],source),node=changes.find((item)=>item.entityType==='flow_node'&&item.entityId==='task-target'),edge=changes.find((item)=>item.entityType==='flow_edge'&&item.entityId==='task-edge');expect(node?.references).toContainEqual({kind:'task',entityType:'task',entityId:'P0-01'});expect(edge?.references).toEqual(expect.arrayContaining([{kind:'source',entityType:'flow_node',entityId:source.flow.nodes[0].id},{kind:'target',entityType:'flow_node',entityId:'task-target'},{kind:'task',entityType:'task',entityId:'P0-01'},{kind:'task',entityType:'task',entityId:'P0-02'}]));expect(changes.filter((change)=>change.entityType==='task').map((change)=>change.entityId)).toEqual(expect.arrayContaining(['P0-01','P0-02']))})
  it('rejects missing and mismatched managed task identities plus invalid edge taskIds',()=>{const missing=bundle();missing.flow.nodes.push({id:'missing-task-identity',position:{x:0,y:0},data:{label:'missing',targetType:'task',targetId:'P0-01'}});const mismatch=bundle();mismatch.flow.edges.push({id:'mismatch-task-edge',source:mismatch.flow.nodes[0].id,target:mismatch.flow.nodes[1].id,data:{targetType:'task',targetId:'P0-01',taskId:'P0-02'}});const invalidRefs=bundle();invalidRefs.flow.edges.push({id:'invalid-task-refs',source:invalidRefs.flow.nodes[0].id,target:invalidRefs.flow.nodes[1].id,data:{taskIds:['P0-01','P9-99']}});expect(validateBundle(missing).some((issue)=>issue.path.endsWith('.taskId'))).toBe(true);expect(validateBundle(missing).some((issue)=>issue.path.endsWith('.taskIds'))).toBe(true);expect(validateBundle(mismatch).some((issue)=>issue.message.includes('targetId'))).toBe(true);expect(validateBundle(invalidRefs).some((issue)=>issue.path.endsWith('.taskIds'))).toBe(true)})
  it('keeps surviving edge taskIds as cloud task references after a diff',()=>{const before=bundle();before.flow.edges[0]={...before.flow.edges[0],data:{...before.flow.edges[0].data,taskIds:['P0-01','P0-02']}};const current=bundleToEntities(before).map((entity)=>({...entity,version:4})),after=structuredClone(before);after.flow.edges[0].data={...after.flow.edges[0].data,taskIds:['P0-02']};const change=diffEntities(current,after).find((item)=>item.entityType==='flow_edge'&&item.entityId===after.flow.edges[0].id);expect(change?.references).toContainEqual({kind:'task',entityType:'task',entityId:'P0-02'});expect(change?.references).not.toContainEqual({kind:'task',entityType:'task',entityId:'P0-01'})})
  it('rejects duplicate cloud entity identities before applying state',()=>{const entities=bundleToEntities(bundle());expect(()=>entitiesToBundle([...entities,entities[0]],'2026-08-17T01:00:00.000Z')).toThrow('重複')})
  it('encodes required singleton payloads for an empty weekly bundle',()=>{const entities=bundleToEntities(bundle()),viewport=entities.find((entity)=>entity.entityType==='flow_viewport'),baseline=entities.find((entity)=>entity.entityType==='report_baseline'),meta=entities.find((entity)=>entity.entityType==='weekly_meta');expect(viewport).toMatchObject({entityId:'singleton',payload:{id:'singleton',x:initialViewport.x,y:initialViewport.y,zoom:initialViewport.zoom}});expect(baseline).toMatchObject({entityId:'singleton',payload:{id:'singleton',value:null}});expect(meta).toMatchObject({entityId:'singleton',payload:{id:'singleton',lastRunId:null}})})
  it('matches the SQL payload and link contract for every real entity type',()=>{const source=bundle();source.tasks[0]={...source.tasks[0],status:'完了',updatedAt:'2026-08-17T00:00:00.000Z'};source.reportBaseline={savedAt:'2026-08-17T00:00:00.000Z',statuses:{'P0-01':{status:'完了',updatedAt:'2026-08-17T00:00:00.000Z'}}};source.migrationArchive=[{fromSchema:2,migratedAt:'2026-08-17T00:00:00.000Z',reason:'contract fixture',tasks:[{id:'T-1'}]}];source.weekly.tombstones=['contract-tombstone'];const weekly=runWeeklyBundle(source,new Date('2026-08-17T12:00:00+09:00'),'manual'),entities=bundleToEntities(weekly),changes=diffEntities([],weekly),types=new Set(entities.map((entity)=>entity.entityType));expect(types).toEqual(new Set(['task','flow_node','flow_edge','flow_viewport','client_audit','kpi','report_baseline','migration_archive','weekly_run','weekly_completion','weekly_tombstone','weekly_meta']));for(const entity of entities)assertSqlPayload(entity);const decoded=entitiesToBundle(entities.map((entity)=>({...entity,version:3})),weekly.exportedAt);expect(decoded).toEqual(weekly);expect(diffEntities(entities.map((entity)=>({...entity,version:3})),decoded)).toEqual([]);const find=(type:string,id?:string)=>changes.find((change)=>change.entityType===type&&(!id||change.entityId===id))!;const auto=weekly.tasks.find((task)=>task.createdRunId&&task.provenance?.sourceTaskId)!;expect(find('task',auto.id).references).toEqual(expect.arrayContaining([{kind:'created_run',entityType:'weekly_run',entityId:auto.createdRunId!},{kind:'provenance_source',entityType:'task',entityId:auto.provenance!.sourceTaskId!}]));for(const id of auto.provenance!.dependencyIds)expect(find('task',auto.id).references).toContainEqual({kind:'provenance_dependency',entityType:'task',entityId:id});if(auto.provenance!.kpiId)expect(find('task',auto.id).references).toContainEqual({kind:'provenance_kpi',entityType:'kpi',entityId:auto.provenance!.kpiId});const summary=weekly.flow.nodes.find((node)=>typeof node.data.runId==='string')!;expect(find('flow_node',summary.id).references).toContainEqual({kind:'weekly_run',entityType:'weekly_run',entityId:summary.data.runId});expect(find('weekly_completion','P0-01').references).toContainEqual({kind:'task',entityType:'task',entityId:'P0-01'});expect(find('weekly_meta','singleton').references).toEqual([{kind:'last_run',entityType:'weekly_run',entityId:weekly.weekly.lastRun!.runId}]);expect(find('report_baseline','singleton').payload).toEqual({id:'singleton',value:weekly.reportBaseline});expect(find('weekly_run',weekly.weekly.lastRun!.runId).payload).toMatchObject({id:weekly.weekly.lastRun!.runId,runId:weekly.weekly.lastRun!.runId})})
})

describe('task result cloud entity',()=>{
  it('round-trips task_result payload and emits its task reference',()=>{
    const source=bundle(),result={id:'task-result:P0-01',taskId:'P0-01',resultBody:'完了',verificationState:'適合' as const,verificationSummary:'確認済み',deliverables:[{id:'deliverable:P0-01:1',title:'成果',type:'url' as const,href:'https://example.com/result',accessState:'利用可能' as const}],nextStep:'共有',completionCriteria:'承認',verificationMemo:'異常なし',updatedAt:'2026-08-17T00:00:00.000Z'}
    source.taskResults=[result as NonNullable<ExportBundle['taskResults']>[number]]
    const entities=bundleToEntities(source),entity=entities.find((item)=>item.entityType==='task_result'),change=diffEntities([],source).find((item)=>item.entityType==='task_result')
    expect(entity).toMatchObject({entityId:result.id,payload:result})
    expect(change?.references).toEqual([{kind:'task',entityType:'task',entityId:'P0-01'}])
    expect(entitiesToBundle(entities.map((item)=>({...item,version:1})),source.exportedAt).taskResults).toEqual([result])
  })
})
