import type { SupabaseClient } from '@supabase/supabase-js'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { initialAudit, initialEdges, initialKpis, initialNodes, initialTasks, initialViewport } from '../data'
import type { ExportBundle } from '../types'
import { emptyWeeklyState } from '../weekly'
import { bundleToEntities, diffEntities } from './entities'
import { cloudCacheKey } from './cache'
import { importMarkerKey } from './cache'
import { SupabaseWorkspaceRepository } from './repository'

const bundle=():ExportBundle=>({schemaVersion:4,exportedAt:'2026-08-17T00:00:00.000Z',tasks:structuredClone(initialTasks),flow:{nodes:structuredClone(initialNodes),edges:structuredClone(initialEdges),viewport:structuredClone(initialViewport)},audit:structuredClone(initialAudit),kpis:structuredClone(initialKpis),reportBaseline:null,migrationArchive:[],weekly:emptyWeeklyState()})
const response=(value:ExportBundle,stateVersion=1,role='editor')=>({schemaVersion:4,organization:{id:'11111111-1111-4111-8111-111111111111',name:'NEXUS',slug:'nexus',status:'active',stateVersion},role,entities:bundleToEntities(value).map((entity)=>({...entity,version:stateVersion})),importState:{status:'imported',manifestCount:1,lastManifestAt:'2026-08-17T00:00:00.000Z'},readAt:value.exportedAt})
const client=(rpc:ReturnType<typeof vi.fn>)=>({rpc}) as unknown as SupabaseClient

describe('Supabase workspace repository',()=>{
  beforeEach(()=>localStorage.clear())
  it('updates only the organization cache after a successful server read-back',async()=>{const source=bundle(),candidate=structuredClone(source),id='11111111-1111-4111-8111-111111111111';candidate.tasks[0].status='進行中';candidate.tasks[0].updatedAt='2026-08-17T01:00:00.000Z';candidate.exportedAt='2026-08-17T01:00:00.000Z';localStorage.setItem('nexus.bundle.v4','immutable-source');const rpc=vi.fn().mockResolvedValueOnce({data:response(source),error:null}).mockResolvedValueOnce({data:{organizationId:id,stateVersion:2,runId:'22222222-2222-4222-8222-222222222222',operation:'apply_changes',changedCount:1,idempotent:false,committedAt:'2026-08-17T01:00:00.000Z'},error:null}).mockResolvedValueOnce({data:response(candidate,2),error:null}),repository=new SupabaseWorkspaceRepository(client(rpc));await repository.read(id);const confirmed=await repository.save(candidate,id);expect(confirmed.bundle?.tasks[0].status).toBe('進行中');const cached=JSON.parse(localStorage.getItem(cloudCacheKey(id))!);expect(cached.bundle.tasks[0].status).toBe('進行中');expect(cached.organizationId).toBe(id);expect(cached.stateVersion).toBe(2);expect(localStorage.getItem('nexus.bundle.v4')).toBe('immutable-source')})
  it('preserves the cache when optimistic locking reports a conflict',async()=>{const source=bundle(),candidate=structuredClone(source),id='11111111-1111-4111-8111-111111111111';candidate.tasks[0].status='進行中';candidate.tasks[0].updatedAt='2026-08-17T01:00:00.000Z';const rpc=vi.fn().mockResolvedValueOnce({data:response(source),error:null}).mockResolvedValueOnce({data:null,error:{message:'state version conflict',code:'40001'}}),repository=new SupabaseWorkspaceRepository(client(rpc));await repository.read(id);await expect(repository.save(candidate,id)).rejects.toMatchObject({kind:'conflict'});expect(localStorage.getItem(cloudCacheKey(id))).toBeNull()})
  it('uses the dedicated weekly RPC and classifies revoked access',async()=>{const source=bundle(),candidate=structuredClone(source),id='11111111-1111-4111-8111-111111111111';candidate.tasks[0].status='進行中';candidate.tasks[0].updatedAt='2026-08-17T01:00:00.000Z';const rpc=vi.fn().mockResolvedValueOnce({data:response(source),error:null}).mockResolvedValueOnce({data:null,error:{message:'membership required',code:'42501',status:403}}),repository=new SupabaseWorkspaceRepository(client(rpc));await repository.read(id);await expect(repository.save(candidate,id,'weekly')).rejects.toMatchObject({kind:'access_revoked'});expect(rpc.mock.calls[1][0]).toBe('rpc_save_weekly')})
  it('treats 42501 as revoked before role wording but keeps a known viewer read-only',async()=>{const source=bundle(),candidate=structuredClone(source),id='11111111-1111-4111-8111-111111111111';candidate.tasks[0].status='進行中';candidate.tasks[0].updatedAt='2026-08-17T01:00:00.000Z';const revokedRpc=vi.fn().mockResolvedValueOnce({data:response(source),error:null}).mockResolvedValueOnce({data:null,error:{message:'owner role required',code:'42501'}}),revoked=new SupabaseWorkspaceRepository(client(revokedRpc));await revoked.read(id);await expect(revoked.save(candidate,id)).rejects.toMatchObject({kind:'access_revoked'});const viewerRpc=vi.fn().mockResolvedValueOnce({data:response(source,1,'viewer'),error:null}),viewer=new SupabaseWorkspaceRepository(client(viewerRpc));await viewer.read(id);await expect(viewer.save(candidate,id)).rejects.toMatchObject({kind:'read_only'});expect(viewerRpc).toHaveBeenCalledTimes(1)})
  it('imports only an empty owner workspace and records the verified manifest',async()=>{const source=bundle(),id='11111111-1111-4111-8111-111111111111',entities=diffEntities([],source),empty={...response(source,0,'owner'),entities:[],importState:{status:'empty',manifestCount:0,lastManifestAt:null}},rpc=vi.fn().mockResolvedValueOnce({data:empty,error:null}).mockResolvedValueOnce({data:{organizationId:id,stateVersion:1,runId:'22222222-2222-4222-8222-222222222222',operation:'import_v4',changedCount:entities.length,idempotent:false,committedAt:'2026-08-17T01:00:00.000Z',manifestId:'33333333-3333-4333-8333-333333333333',manifestStatus:'completed'},error:null}).mockResolvedValueOnce({data:response(source,1,'owner'),error:null}),repository=new SupabaseWorkspaceRepository(client(rpc));await repository.read(id);const result=await repository.importV4({storageKey:'nexus.bundle.v4',raw:'{}',sourceOrigin:'test#nexus.bundle.v4',rawSha256:'a'.repeat(64),semanticFingerprint:'b'.repeat(64),sourceSize:2,sourceEntityCount:entities.length,bundle:source,entities},id);expect(result.entities).toHaveLength(entities.length);expect(rpc.mock.calls[1][0]).toBe('rpc_import_v4');expect(rpc.mock.calls[1][1]).toMatchObject({p_expected_state_version:0,p_source_entity_count:entities.length,p_raw_sha256:'a'.repeat(64)});expect(localStorage.getItem(importMarkerKey(id))).toContain('33333333-3333-4333-8333-333333333333')})
})

describe('detached remote polling',()=>{
  it('does not replace the save baseline until the caller explicitly adopts the read',async()=>{const source=bundle(),remote=structuredClone(source),candidate=structuredClone(source),id='11111111-1111-4111-8111-111111111111';remote.exportedAt='2026-08-17T00:30:00.000Z';candidate.tasks[0].status='進行中';candidate.tasks[0].updatedAt='2026-08-17T01:00:00.000Z';candidate.exportedAt='2026-08-17T01:00:00.000Z';const rpc=vi.fn().mockResolvedValueOnce({data:response(source,1),error:null}).mockResolvedValueOnce({data:response(remote,2),error:null}).mockResolvedValueOnce({data:{organizationId:id,stateVersion:2,runId:'22222222-2222-4222-8222-222222222222',operation:'apply_changes',changedCount:1,idempotent:false,committedAt:candidate.exportedAt},error:null}).mockResolvedValueOnce({data:response(candidate,2),error:null}),repository=new SupabaseWorkspaceRepository(client(rpc));await repository.read(id);await repository.read(id,false);await repository.save(candidate,id);expect(rpc.mock.calls[2][1]).toMatchObject({p_expected_state_version:1})})
})

describe('task result repository round-trip',()=>{
  it('saves one task_result entity and confirms it by server read-back',async()=>{const source=bundle(),candidate=structuredClone(source),id='11111111-1111-4111-8111-111111111111';candidate.taskResults=[{id:'task-result:P0-01',taskId:'P0-01',resultBody:'完了',verificationState:'適合',verificationSummary:'確認済み',deliverables:[],nextStep:'共有',completionCriteria:'承認',verificationMemo:'異常なし',updatedAt:'2026-08-17T01:00:00.000Z'}];candidate.exportedAt='2026-08-17T01:00:00.000Z';const rpc=vi.fn().mockResolvedValueOnce({data:response(source),error:null}).mockResolvedValueOnce({data:{organizationId:id,stateVersion:2,runId:'22222222-2222-4222-8222-222222222222',operation:'apply_changes',changedCount:1,idempotent:false,committedAt:candidate.exportedAt},error:null}).mockResolvedValueOnce({data:response(candidate,2),error:null}),repository=new SupabaseWorkspaceRepository(client(rpc));await repository.read(id);const saved=await repository.save(candidate,id);expect(saved.bundle?.taskResults).toEqual(candidate.taskResults);expect((rpc.mock.calls[1][1].p_changes as Array<{entityType:string}>)[0].entityType).toBe('task_result')})
})
