import { expect, test, type Page } from '@playwright/test'

const boot=async(page:Page,{reducedMotion=false}:{reducedMotion?:boolean}={})=>{const problems:string[]=[];page.on('console',(message)=>{if(['error','warning'].includes(message.type()))problems.push(message.text())});if(reducedMotion)await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await page.evaluate(()=>localStorage.clear());await page.reload();return problems}

test('loads the authoritative 73-task plan at Phase 0 with source traceability',async({page})=>{const problems=await boot(page);expect(await page.locator('[data-task-id^="P"]').count()).toBeGreaterThan(0);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nexus.bundle.v4')!).tasks.filter((task:{id:string})=>/^P[0-6]-\d{2}$/.test(task.id)).length)).toBe(73);await expect(page.getByRole('tab',{name:/Phase 0/})).toHaveAttribute('aria-selected','true');await expect(page.getByText(/S4:88-88/)).toBeVisible();await expect(page.getByText('旧期限超過 / 改訂期限まで4日')).toBeVisible();await expect(page.getByRole('button',{name:/YUKISHIRO.*削除/})).toBeDisabled();expect(problems).toEqual([])})

test('phase, person, deadline and team views work without duplicating tasks',async({page})=>{const problems=await boot(page);await page.getByRole('tab',{name:/全体/}).click();await page.getByLabel('担当者フィルタ').getByRole('button',{name:/スン/}).click();await expect(page.locator('[data-task-id="P5-01"]')).toBeVisible();expect(await page.locator('[data-task-id^="P"]').count()).toBe(6);await page.getByLabel('担当者フィルタ').getByRole('button',{name:/スン/}).click();await page.getByRole('button',{name:'期限超過'}).click();await expect(page.locator('[data-task-id="P0-01"]')).toBeVisible();await page.getByRole('button',{name:'チーム別表示'}).click();await expect(page.getByRole('heading',{name:'キャスティング・渉外チーム'})).toBeVisible();expect(problems).toEqual([])})

test('status and required hold reason persist across reload',async({page})=>{const problems=await boot(page);await page.locator('#status-card-P0-01').selectOption('進行中');await expect(page.getByRole('status')).toContainText('進行中');page.once('dialog',async(dialog)=>{expect(dialog.type()).toBe('prompt');await dialog.accept('外部回答待ち')});await page.locator('#status-card-P0-01').selectOption('保留');await page.reload();expect(await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);const task=value.tasks.find((item:{id:string})=>item.id==='P0-01');return{status:task.status,holdReason:task.holdReason}})).toEqual({status:'保留',holdReason:'外部回答待ち'});expect(problems).toEqual([])})

test('CRUD preserves canonical fields and audits custom deletion',async({page})=>{const problems=await boot(page);await page.getByRole('button',{name:'新規タスク'}).click();await page.getByLabel('タスク名 *').fill('E2E追加タスク');await page.getByLabel('担当者（読点区切り）').fill('鈴木、浜名');await page.getByRole('button',{name:'保存する'}).click();await page.getByRole('tab',{name:/全体/}).click();await expect(page.getByRole('heading',{name:'E2E追加タスク'})).toBeVisible();await page.getByRole('button',{name:'E2E追加タスクを編集'}).click();await page.getByLabel('タスク名 *').fill('E2E編集済み');await page.getByRole('button',{name:'保存する'}).click();page.once('dialog',(dialog)=>dialog.accept());await page.getByRole('button',{name:'E2E編集済みを削除'}).click();await page.reload();const result=await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);return{exists:value.tasks.some((task:{title:string})=>task.title==='E2E編集済み'),deleteAudit:value.audit.some((item:{issueId:string})=>item.issueId==='OP-TASK-DELETE')}});expect(result).toEqual({exists:false,deleteAudit:true});expect(problems).toEqual([])})

test('validated JSON import is audited and malicious import remains atomic',async({page})=>{const problems=await boot(page);await page.locator('#status-card-P0-01').selectOption('進行中');const valid=await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4')!);await page.locator('#json-import').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(valid)});await expect(page.getByRole('status')).toContainText('データを読み込みました');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nexus.bundle.v4')!).audit.some((item:{issueId:string})=>item.issueId==='OP-JSON-IMPORT'))).toBe(true);const before=await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'));const bad=JSON.parse(valid);bad.tasks[0].sourceRefs=[];await page.locator('#json-import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await expect(page.getByRole('alert')).toContainText('sourceRefs');expect(await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'))).toBe(before);expect(problems).toEqual([])})

test('migrates v2 custom data once without mixing it into the authoritative 73',async({page})=>{const problems=await boot(page);await page.evaluate(()=>{localStorage.setItem('nexus.bundle.v2',JSON.stringify({schemaVersion:2,exportedAt:new Date().toISOString(),tasks:[{id:'T-777',title:'利用者の変更',status:'レビュー',memo:'保持'}],flow:{nodes:[],edges:[],viewport:{x:3,y:4,zoom:1.2}},audit:[]}));localStorage.removeItem('nexus.bundle.v4');localStorage.removeItem('nexus.bundle.v3')});await page.reload();const first=await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);return{authoritative:value.tasks.filter((task:{id:string})=>/^P[0-6]-\d{2}$/.test(task.id)).length,archive:value.migrationArchive,viewport:value.flow.viewport}});expect(first).toMatchObject({authoritative:73,viewport:{x:3,y:4,zoom:1.2}});expect(first.archive[0].tasks[0]).toEqual({id:'T-777',title:'利用者の変更',status:'レビュー',memo:'保持'});await page.reload();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nexus.bundle.v4')!).migrationArchive.length)).toBe(1);expect(problems).toEqual([])})

test('KPI actuals and biweekly baseline/report persist with audit entries',async({page})=>{const problems=await boot(page);await page.getByLabel('同時接続の実績').fill('1234');await page.getByRole('button',{name:'KPI保存'}).click();await page.getByRole('button',{name:'隔週報告'}).first().click();await page.getByRole('button',{name:/現在を比較基準に保存/}).click();await page.getByRole('button',{name:'進行表'}).first().click();await page.locator('#status-card-P0-01').selectOption('進行中');await page.getByRole('button',{name:'隔週報告'}).first().click();await expect(page.getByLabel('LINE貼付用テキスト')).toHaveValue(/P0-01.*状態 未着手→進行中/);await page.reload();const result=await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);return{actual:value.kpis.find((kpi:{id:string})=>kpi.id==='concurrent').actual,audits:['OP-KPI-SAVE','OP-REPORT-BASELINE'].every((id)=>value.audit.some((item:{issueId:string})=>item.issueId===id))}});expect(result).toEqual({actual:1234,audits:true});expect(problems).toEqual([])})

test('canvas persistence, audit and mobile Phase 5 controls remain usable',async({page})=>{const problems=await boot(page);await page.getByRole('button',{name:'キャンバス'}).first().click();await page.getByLabel('接続元').selectOption('phase-0');await page.getByLabel('接続先').selectOption('phase-5');await page.getByRole('button',{name:'接続',exact:true}).click();await page.getByRole('button',{name:'保存',exact:true}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nexus.bundle.v4')!).audit.some((item:{issueId:string})=>item.issueId==='OP-CANVAS-SAVE'))).toBe(true);await page.setViewportSize({width:360,height:800});await page.getByRole('button',{name:'進行表'}).first().click();await page.getByRole('tab',{name:/Phase 5/}).click();await expect(page.locator('[data-task-id^="P5-"]')).toHaveCount(8);const heights=await page.locator('[data-task-id^="P5-"] .status-select').evaluateAll((items)=>items.map((item)=>item.getBoundingClientRect().height));expect(heights.every((height)=>height>=44)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(problems).toEqual([])})

test('weekly update freezes snapshot, is a full no-op for identical input and shows reopened truthfully',async({page})=>{const problems=await boot(page),initialRun=await page.evaluate(()=>JSON.parse(localStorage.getItem('nexus.bundle.v4')!).weekly.lastRun);await page.locator('#status-card-P0-01').selectOption('完了');const beforeManual=await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'));await page.getByRole('button',{name:'今すぐ週次更新'}).click();expect(await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'))).toBe(beforeManual);await page.getByRole('button',{name:'キャンバス'}).first().click();await expect(page.getByLabel('ノード種別')).toBeVisible();let state=await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);return{complete:value.flow.nodes.filter((node:{id:string})=>node.id==='weekly-complete:P0-01').length,summary:value.flow.nodes.filter((node:{id:string})=>node.id===`weekly-summary:${value.weekly.lastRun.runId}`).length,run:value.weekly.lastRun,current:value.weekly.completions['P0-01'].currentStatus}});expect(state).toMatchObject({complete:1,summary:1,current:'完了'});expect(state.run).toEqual(initialRun);await page.getByRole('button',{name:'進行表'}).first().click();await page.locator('#status-card-P0-01').selectOption('進行中');const beforeReopenManual=await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'));await page.getByRole('button',{name:'今すぐ週次更新'}).click();expect(await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'))).toBe(beforeReopenManual);state=await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);const node=value.flow.nodes.find((item:{id:string})=>item.id==='weekly-complete:P0-01');return{complete:value.flow.nodes.filter((item:{id:string})=>item.id==='weekly-complete:P0-01').length,summary:value.flow.nodes.filter((item:{id:string})=>item.id===`weekly-summary:${value.weekly.lastRun.runId}`).length,label:node.data.label,current:value.weekly.completions['P0-01'].currentStatus,run:value.weekly.lastRun}});expect(state).toMatchObject({complete:1,summary:1,current:'進行中'});expect(state.run).toEqual(initialRun);expect(state.label).toContain('再オープン');expect(problems).toEqual([])})

test('automatic tasks can be deleted and tombstoned without touching authoritative tasks',async({page})=>{const problems=await boot(page);await page.getByRole('tab',{name:/全体/}).click();const selected=await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);const task=value.tasks.find((item:{createdByDepartment?:string})=>item.createdByDepartment==='esports_progress_control');return{id:task.id,fingerprint:task.fingerprint}});page.once('dialog',(dialog)=>dialog.accept());await page.locator(`[data-task-id="${selected.id}"]`).getByRole('button',{name:/削除/}).click();await page.getByRole('button',{name:'今すぐ週次更新'}).click();const result=await page.evaluate(({id,fingerprint})=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);return{exists:value.tasks.some((task:{id:string})=>task.id===id),fingerprintExists:value.tasks.some((task:{fingerprint?:string})=>task.fingerprint===fingerprint),tombstoned:value.weekly.tombstones.includes(fingerprint),authoritative:value.tasks.filter((task:{id:string})=>/^P[0-6]-\d{2}$/.test(task.id)).length}},selected);expect(result).toEqual({exists:false,fingerprintExists:false,tombstoned:true,authoritative:73});expect(problems).toEqual([])})

test('reduced motion disables decorative animation',async({page})=>{const problems=await boot(page,{reducedMotion:true});const values=await page.locator('.hero').evaluate((hero)=>({opacity:(hero as HTMLElement).style.opacity,transform:(hero as HTMLElement).style.transform,duration:getComputedStyle(document.querySelector('.page-panel')!).animationDuration}));expect(values.opacity).toBe('');expect(values.transform).toBe('');expect(Number.parseFloat(values.duration)).toBeLessThanOrEqual(.001);expect(problems).toEqual([])})
