import { expect, test, type Page } from '@playwright/test'

const boot=async(page:Page,{reducedMotion=false}:{reducedMotion?:boolean}={})=>{const problems:string[]=[];page.on('console',(message)=>{if(['error','warning'].includes(message.type()))problems.push(message.text())});if(reducedMotion)await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await page.evaluate(()=>localStorage.clear());await page.reload();return problems}

test('loads the authoritative 73-task plan at Phase 0 with source traceability',async({page})=>{await page.clock.setFixedTime(new Date('2026-08-14T12:00:00+09:00'));const problems=await boot(page);expect(await page.locator('[data-task-id^="P"]').count()).toBeGreaterThan(0);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nexus.bundle.v4')!).tasks.filter((task:{id:string})=>/^P[0-6]-\d{2}$/.test(task.id)).length)).toBe(73);await expect(page.getByRole('tab',{name:/Phase 0/})).toHaveAttribute('aria-selected','true');await expect(page.getByText(/S4:88-88/)).toBeVisible();await expect(page.getByText('旧期限超過 / 改訂期限まで4日')).toBeVisible();await expect(page.getByRole('button',{name:/YUKISHIRO.*削除/})).toBeDisabled();expect(problems).toEqual([])})

test('phase, person, deadline and team views work without duplicating tasks',async({page})=>{const problems=await boot(page);await page.getByRole('tab',{name:/全体/}).click();await page.getByLabel('担当者フィルタ').getByRole('button',{name:/スン/}).click();await expect(page.locator('[data-task-id="P5-01"]')).toBeVisible();expect(await page.locator('[data-task-id^="P"]').count()).toBe(6);await page.getByLabel('担当者フィルタ').getByRole('button',{name:/スン/}).click();await page.getByRole('button',{name:'期限超過'}).click();await expect(page.locator('[data-task-id="P0-01"]')).toBeVisible();await page.getByRole('button',{name:'チーム別表示'}).click();await expect(page.getByRole('heading',{name:'キャスティング・渉外チーム'})).toBeVisible();expect(problems).toEqual([])})

test('status and required hold reason persist across reload',async({page})=>{const problems=await boot(page);await page.locator('#status-card-P0-01').selectOption('進行中');await expect(page.getByRole('status')).toContainText('進行中');page.once('dialog',async(dialog)=>{expect(dialog.type()).toBe('prompt');await dialog.accept('外部回答待ち')});await page.locator('#status-card-P0-01').selectOption('保留');await page.reload();expect(await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);const task=value.tasks.find((item:{id:string})=>item.id==='P0-01');return{status:task.status,holdReason:task.holdReason}})).toEqual({status:'保留',holdReason:'外部回答待ち'});expect(problems).toEqual([])})

test('CRUD preserves canonical fields and audits custom deletion',async({page})=>{const problems=await boot(page);await page.getByRole('button',{name:'新規タスク'}).click();await page.getByLabel('タスク名 *').fill('E2E追加タスク');await page.getByLabel('担当者（読点区切り）').fill('鈴木、浜名');await page.getByRole('button',{name:'保存する'}).click();await page.getByRole('tab',{name:/全体/}).click();await expect(page.getByRole('heading',{name:'E2E追加タスク'})).toBeVisible();await page.getByRole('button',{name:'E2E追加タスクを編集'}).click();await page.getByLabel('タスク名 *').fill('E2E編集済み');await page.getByRole('button',{name:'保存する'}).click();page.once('dialog',(dialog)=>dialog.accept());await page.getByRole('button',{name:'E2E編集済みを削除'}).click();await page.reload();const result=await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);return{exists:value.tasks.some((task:{title:string})=>task.title==='E2E編集済み'),deleteAudit:value.audit.some((item:{issueId:string})=>item.issueId==='OP-TASK-DELETE')}});expect(result).toEqual({exists:false,deleteAudit:true});expect(problems).toEqual([])})

test('validated JSON import is audited and malicious import remains atomic',async({page})=>{const problems=await boot(page);await page.locator('#status-card-P0-01').selectOption('進行中');const valid=await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4')!);await page.locator('#json-import').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(valid)});await expect(page.getByRole('status')).toContainText('データを読み込みました');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nexus.bundle.v4')!).audit.some((item:{issueId:string})=>item.issueId==='OP-JSON-IMPORT'))).toBe(true);const before=await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'));const bad=JSON.parse(valid);bad.tasks[0].sourceRefs=[];await page.locator('#json-import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await expect(page.getByRole('alert')).toContainText('sourceRefs');expect(await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'))).toBe(before);expect(problems).toEqual([])})

test('migrates v2 custom data once without mixing it into the authoritative 73',async({page})=>{const problems=await boot(page);await page.evaluate(()=>{localStorage.setItem('nexus.bundle.v2',JSON.stringify({schemaVersion:2,exportedAt:new Date().toISOString(),tasks:[{id:'T-777',title:'利用者の変更',status:'レビュー',memo:'保持'}],flow:{nodes:[],edges:[],viewport:{x:3,y:4,zoom:1.2}},audit:[]}));localStorage.removeItem('nexus.bundle.v4');localStorage.removeItem('nexus.bundle.v3')});await page.reload();const first=await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);return{authoritative:value.tasks.filter((task:{id:string})=>/^P[0-6]-\d{2}$/.test(task.id)).length,archive:value.migrationArchive,viewport:value.flow.viewport}});expect(first).toMatchObject({authoritative:73,viewport:{x:3,y:4,zoom:1.2}});expect(first.archive[0].tasks[0]).toEqual({id:'T-777',title:'利用者の変更',status:'レビュー',memo:'保持'});await page.reload();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nexus.bundle.v4')!).migrationArchive.length)).toBe(1);expect(problems).toEqual([])})

test('KPI actuals and biweekly baseline/report persist with audit entries',async({page})=>{const problems=await boot(page);await page.getByLabel('同時接続の実績').fill('1234');await page.getByRole('button',{name:'KPI保存'}).click();await page.getByRole('button',{name:'隔週報告'}).first().click();await page.getByRole('button',{name:/現在を比較基準に保存/}).click();await page.getByRole('button',{name:'進行表'}).first().click();await page.locator('#status-card-P0-01').selectOption('進行中');await page.getByRole('button',{name:'隔週報告'}).first().click();await expect(page.getByLabel('LINE貼付用テキスト')).toHaveValue(/P0-01.*状態 未着手→進行中/);await page.reload();const result=await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);return{actual:value.kpis.find((kpi:{id:string})=>kpi.id==='concurrent').actual,audits:['OP-KPI-SAVE','OP-REPORT-BASELINE'].every((id)=>value.audit.some((item:{issueId:string})=>item.issueId===id))}});expect(result).toEqual({actual:1234,audits:true});expect(problems).toEqual([])})

test('canvas persistence, audit and mobile Phase 5 controls remain usable',async({page})=>{const problems=await boot(page);await page.getByRole('button',{name:'キャンバス'}).first().click();await page.getByLabel('接続元').selectOption('phase-0');await page.getByLabel('接続先').selectOption('phase-5');await page.getByRole('button',{name:'接続',exact:true}).click();await page.getByRole('button',{name:'保存',exact:true}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nexus.bundle.v4')!).audit.some((item:{issueId:string})=>item.issueId==='OP-CANVAS-SAVE'))).toBe(true);await page.setViewportSize({width:360,height:800});await page.getByRole('button',{name:'進行表'}).first().click();await page.getByRole('tab',{name:/Phase 5/}).click();await expect(page.locator('[data-task-id^="P5-"]')).toHaveCount(8);const heights=await page.locator('[data-task-id^="P5-"] .status-select').evaluateAll((items)=>items.map((item)=>item.getBoundingClientRect().height));expect(heights.every((height)=>height>=44)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(problems).toEqual([])})

test('weekly update freezes snapshot, updates managed truth once, then becomes a full no-op',async({page})=>{const problems=await boot(page),initialRun=await page.evaluate(()=>JSON.parse(localStorage.getItem('nexus.bundle.v4')!).weekly.lastRun);await page.locator('#status-card-P0-01').selectOption('完了');const beforeManual=await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'));await page.getByRole('button',{name:'今すぐ週次更新'}).click();const afterManaged=await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'));expect(afterManaged).not.toBe(beforeManual);await page.getByRole('button',{name:'今すぐ週次更新'}).click();expect(await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'))).toBe(afterManaged);await page.getByRole('button',{name:'キャンバス'}).first().click();let state=await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);return{complete:value.flow.nodes.filter((node:{id:string})=>node.id==='weekly-complete:P0-01').length,summary:value.flow.nodes.filter((node:{id:string})=>node.id===`weekly-summary:${value.weekly.lastRun.runId}`).length,managed:String(value.flow.nodes.find((node:{id:string})=>node.id==='weekly-project:task:P0-01')?.data.label),run:value.weekly.lastRun,current:value.weekly.completions['P0-01'].currentStatus}});expect(state).toMatchObject({complete:1,summary:1,current:'完了'});expect(state.managed).toContain('成果未登録');expect(state.run).toEqual(initialRun);await page.getByRole('button',{name:'進行表'}).first().click();await page.locator('#status-card-P0-01').selectOption('進行中');await page.getByRole('button',{name:'今すぐ週次更新'}).click();const afterReopen=await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'));await page.getByRole('button',{name:'今すぐ週次更新'}).click();expect(await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'))).toBe(afterReopen);state=await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);const node=value.flow.nodes.find((item:{id:string})=>item.id==='weekly-complete:P0-01');return{label:node.data.label,current:value.weekly.completions['P0-01'].currentStatus,run:value.weekly.lastRun}});expect(state.current).toBe('進行中');expect(state.run).toEqual(initialRun);expect(state.label).toContain('再オープン');expect(problems).toEqual([])})

test('automatic tasks can be deleted and tombstoned without touching authoritative tasks',async({page})=>{const problems=await boot(page);await page.getByRole('tab',{name:/全体/}).click();const selected=await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);const task=value.tasks.find((item:{createdByDepartment?:string})=>item.createdByDepartment==='esports_progress_control');return{id:task.id,fingerprint:task.fingerprint}});page.once('dialog',(dialog)=>dialog.accept());await page.locator(`[data-task-id="${selected.id}"]`).getByRole('button',{name:/削除/}).click();await page.getByRole('button',{name:'今すぐ週次更新'}).click();const result=await page.evaluate(({id,fingerprint})=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);return{exists:value.tasks.some((task:{id:string})=>task.id===id),fingerprintExists:value.tasks.some((task:{fingerprint?:string})=>task.fingerprint===fingerprint),tombstoned:value.weekly.tombstones.includes(fingerprint),authoritative:value.tasks.filter((task:{id:string})=>/^P[0-6]-\d{2}$/.test(task.id)).length}},selected);expect(result).toEqual({exists:false,fingerprintExists:false,tombstoned:true,authoritative:73});expect(problems).toEqual([])})

test('dirty canvas blocks weekly and navigation until explicit discard or save',async({page})=>{const problems=await boot(page);await page.getByRole('button',{name:'キャンバス'}).first().click();const before=await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'));await page.getByRole('button',{name:'カード追加'}).click();await expect(page.getByText('未保存の変更があります')).toBeVisible();await expect(page.getByRole('button',{name:'進行表'}).first()).toBeDisabled();await page.getByRole('button',{name:'今すぐ週次更新'}).click();await expect(page.getByRole('alert')).toContainText('週次更新を停止');expect(await page.evaluate(()=>localStorage.getItem('nexus.bundle.v4'))).toBe(before);await page.getByRole('button',{name:'未保存変更を破棄'}).click();await expect(page.getByText('未保存の変更があります')).toHaveCount(0);await expect(page.getByText('新しいカード')).toHaveCount(0);await page.getByRole('button',{name:'カード追加'}).click();await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByText('未保存の変更があります')).toHaveCount(0);await page.getByRole('button',{name:'今すぐ週次更新'}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nexus.bundle.v4')!).flow.nodes.some((node:{id:string})=>node.id==='user-node:1'))).toBe(true);expect(problems).toEqual([])})

test('task result sheet supports hash navigation, multiple HTTPS links and keyboard canvas fallback',async({page})=>{const problems=await boot(page);await page.getByRole('button',{name:/YUKISHIRO.*成果シート/}).click();await expect(page).toHaveURL(/#task-result\/P0-01$/);await page.getByRole('textbox',{name:/^結果/}).fill('成果確認済み');for(const [index,url] of ['https://example.com/one','https://example.com/two'].entries()){await page.getByRole('button',{name:'成果物を追加'}).click();const editors=page.locator('.deliverable-editor');await editors.nth(index).getByLabel('タイトル').fill(`成果${index+1}`);await editors.nth(index).getByLabel('HTTPS URL').fill(url)}await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByRole('link',{name:/URLを開く/})).toHaveCount(2);await page.reload();await expect(page.getByRole('heading',{name:'P0-01 成果シート'})).toBeVisible();await page.getByRole('button',{name:'進行表に戻る'}).click();await page.getByRole('button',{name:'キャンバス'}).first().click();await page.getByText('キャンバス一覧（キーボード・モバイル用）').click();await page.getByRole('button',{name:'P0-01 の成果シート'}).first().focus();await page.keyboard.press('Enter');await expect(page).toHaveURL(/#task-result\/P0-01$/);expect(problems).toEqual([])})

test('milestone checklist gates completion, saves once, and preserves its parent status',async({page})=>{
  const problems=await boot(page)
  await page.getByRole('tab',{name:/全体/}).click()
  const selected=await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);const task=value.tasks.find((item:{provenance?:{ruleId?:string}})=>item.provenance?.ruleId==='milestone-checklist'),parent=value.tasks.find((item:{id:string})=>item.id===task.provenance.sourceTaskId);return{id:task.id,status:task.status,parentId:parent.id,parentStatus:parent.status}})
  const status=page.locator(`#status-card-${selected.id}`),card=page.locator(`[data-task-id="${selected.id}"]`)
  await status.selectOption('完了')
  await expect(page.getByRole('alert')).toContainText('完了にできません')
  await expect(status).toHaveValue(selected.status)
  await card.getByRole('button',{name:/編集/}).click()
  let dialog=page.getByRole('dialog')
  await dialog.getByLabel('状態').selectOption('完了')
  await dialog.getByRole('button',{name:'保存する'}).click()
  await expect(dialog.getByRole('alert')).toContainText('完了にできません')
  await expect(dialog.getByLabel('状態')).toHaveValue('完了')
  expect(await page.evaluate(({id,parentId})=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);return{status:value.tasks.find((task:{id:string})=>task.id===id).status,parentStatus:value.tasks.find((task:{id:string})=>task.id===parentId).status}},selected)).toEqual({status:selected.status,parentStatus:selected.parentStatus})
  await dialog.getByRole('button',{name:'変更を破棄'}).click()
  await card.locator('.card-actions button').filter({hasText:/^チェックリスト/}).click()
  await page.getByRole('button',{name:'テンプレートを使用'}).click()
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuetext','0/3 完了')
  await page.getByRole('button',{name:'保存',exact:true}).click()
  await page.reload()
  await expect(page.getByRole('heading',{name:new RegExp(`${selected.id} チェックリスト`)})).toBeVisible()
  expect(await page.evaluate((taskId)=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!),results=value.taskResults.filter((result:{taskId:string})=>result.taskId===taskId);return{count:results.length,items:results[0].checklistItems.length,status:value.tasks.find((task:{id:string})=>task.id===taskId).status}},selected.id)).toEqual({count:1,items:3,status:selected.status})
  await page.getByRole('button',{name:'編集'}).click()
  const editors=page.locator('.checklist-editor')
  for(let index=0;index<await editors.count();index++){
    const editor=editors.nth(index)
    await editor.getByLabel('状態').selectOption('完了')
    await editor.getByLabel('確認者').fill('E2E確認者')
    await editor.getByLabel('確認日時').fill('2026-08-19T12:00')
    await editor.getByLabel('証跡メモ').fill(`E2E証跡${index+1}`)
  }
  await page.getByLabel('確認状態').selectOption('適合')
  await page.getByRole('button',{name:'保存',exact:true}).click()
  await page.getByRole('button',{name:'進行表に戻る'}).click()
  await page.getByRole('tab',{name:/全体/}).click()
  await page.locator(`[data-task-id="${selected.id}"]`).getByRole('button',{name:/編集/}).click()
  dialog=page.getByRole('dialog')
  await dialog.getByLabel('状態').selectOption('完了')
  await dialog.getByRole('button',{name:'保存する'}).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('status')).toContainText('タスクを保存しました')
  expect(await page.evaluate(({id,parentId})=>{const value=JSON.parse(localStorage.getItem('nexus.bundle.v4')!);return{status:value.tasks.find((task:{id:string})=>task.id===id).status,parentStatus:value.tasks.find((task:{id:string})=>task.id===parentId).status}},selected)).toEqual({status:'完了',parentStatus:selected.parentStatus})
  await page.setViewportSize({width:360,height:800})
  await page.locator(`[data-task-id="${selected.id}"]`).getByRole('button',{name:/チェックリスト 3\/3/}).click()
  expect(await page.locator('.result-sheet').evaluate((element)=>element.scrollWidth<=element.clientWidth)).toBe(true)
  expect(problems).toEqual([])
})

test('clean visible canvas adopts managed result metadata after weekly update',async({page})=>{const problems=await boot(page);await page.locator('#status-card-P0-01').selectOption('完了');await page.getByRole('button',{name:/YUKISHIRO.*成果シート/}).click();await page.getByRole('textbox',{name:/^結果/}).fill('登録済み');await page.getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('button',{name:'進行表に戻る'}).click();await page.getByRole('button',{name:'キャンバス'}).first().click();const managed=page.locator('[data-id="weekly-project:task:P0-01"]');await expect(managed).not.toContainText('成果登録あり');await page.getByRole('button',{name:'今すぐ週次更新'}).click();await expect(managed).toContainText('成果登録あり');expect(problems).toEqual([])})

test('hashchange navigation and 200 percent zoom remain usable without result overflow',async({page})=>{const problems=await boot(page);await page.evaluate(()=>{document.body.style.zoom='200%';location.hash='#task-result/P0-02'});await expect(page.getByRole('heading',{name:'P0-02 成果シート'})).toBeVisible();const back=page.getByRole('button',{name:'進行表に戻る'});await back.scrollIntoViewIfNeeded();await expect(back).toBeVisible();const metrics=await page.locator('.result-sheet').evaluate((sheet)=>{const rect=(sheet.querySelector('button') as HTMLElement).getBoundingClientRect();return{overflow:sheet.scrollWidth-sheet.clientWidth,buttonHeight:rect.height}});expect(metrics.overflow).toBeLessThanOrEqual(1);expect(metrics.buttonHeight).toBeGreaterThanOrEqual(44);await page.evaluate(()=>{location.hash=''});await expect(page.getByRole('heading',{name:'タスク進行表',exact:true})).toBeVisible();expect(problems).toEqual([])})

test('KPI, task modal and result sheet enforce source-specific save and explicit discard',async({page})=>{const problems=await boot(page);const kpi=page.getByLabel('同時接続の実績');await kpi.fill('12');await expect(page.locator('[data-dirty-sources="kpi"]')).toBeVisible();await page.getByRole('button',{name:'今すぐ週次更新'}).click();await expect(page.locator('.toast.error')).toContainText('週次更新を停止');await page.getByRole('button',{name:'KPI変更を破棄'}).click();await expect(kpi).toHaveValue('');await kpi.fill('12');await page.getByRole('button',{name:'KPI保存'}).click();await expect(page.getByText('未保存の変更があります')).toHaveCount(0);await page.getByRole('button',{name:'新規タスク'}).click();await page.getByLabel('タスク名 *').fill('dirty test');await expect(page.locator('[data-dirty-sources="modal"]')).toBeVisible();await page.getByRole('button',{name:'閉じる'}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator('.toast.error')).toContainText('タスク編集に未保存');await page.getByRole('button',{name:'変更を破棄'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:/YUKISHIRO.*成果シート/}).click();await page.getByRole('textbox',{name:/^結果/}).fill('draft');await expect(page.locator('[data-dirty-sources="result"]')).toBeVisible();const accepted=page.url();await page.getByRole('button',{name:'進行表に戻る'}).click();await expect(page.getByRole('heading',{name:'P0-01 成果シート'})).toBeVisible();expect(page.url()).toBe(accepted);await page.getByRole('button',{name:'変更を破棄して戻る'}).click();await expect(page.getByRole('heading',{name:'タスク進行表',exact:true})).toBeVisible();expect(problems).toEqual([])})

test('dirty hashchange restores the last accepted URL immediately',async({page})=>{const problems=await boot(page);await page.getByRole('button',{name:/YUKISHIRO.*成果シート/}).click();await page.getByRole('textbox',{name:/^結果/}).fill('draft');const accepted=page.url();await page.evaluate(()=>{location.hash='#task-result/P0-02'});await expect.poll(()=>page.url()).toBe(accepted);await expect(page.getByRole('heading',{name:'P0-01 成果シート'})).toBeVisible();expect(problems).toEqual([])})

test('dirty task modal blocks Escape and backdrop dismissal until explicit discard',async({page})=>{const problems=await boot(page);await page.getByRole('button',{name:'新規タスク'}).click();await page.getByLabel('タスク名 *').fill('draft');await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toBeVisible();await page.locator('.modal-backdrop').click({position:{x:2,y:2}});await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'変更を破棄'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(problems).toEqual([])})

test('reduced motion disables decorative animation',async({page})=>{const problems=await boot(page,{reducedMotion:true});const values=await page.locator('.hero').evaluate((hero)=>({opacity:(hero as HTMLElement).style.opacity,transform:(hero as HTMLElement).style.transform,duration:getComputedStyle(document.querySelector('.page-panel')!).animationDuration}));expect(values.opacity).toBe('');expect(values.transform).toBe('');expect(Number.parseFloat(values.duration)).toBeLessThanOrEqual(.001);expect(problems).toEqual([])})
