import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { addEdge, applyEdgeChanges, applyNodeChanges, Background, Controls, MiniMap, ReactFlow, useEdgesState, useNodesState, type Connection, type Edge, type EdgeChange, type Node, type NodeChange, type Viewport } from '@xyflow/react'
import { Link2, Map as MapIcon, Plus, RotateCcw, Save, StickyNote, Trash2 } from 'lucide-react'
import type { FlowData, Task, TaskResultSheet } from '../types'
import { checklistProgress, isMilestoneChecklist } from '../checklistTemplates'
import { flowsEqualForDirty } from './flowDirty'

type Props={initialFlow:FlowData;tasks:Task[];taskResults?:TaskResultSheet[];readOnly?:boolean;onOpenResult?:(taskId:string)=>void;onDirty?:(dirty:boolean)=>void;onSave:(flow:FlowData)=>Promise<boolean>|boolean}
const persistedNodeChange=(change:NodeChange)=>change.type==='remove'||change.type==='add'||change.type==='replace'||change.type==='position'&&change.dragging===false
const persistedEdgeChange=(change:EdgeChange)=>change.type==='remove'||change.type==='add'||change.type==='replace'

export function ProjectCanvas({initialFlow,tasks,taskResults=[],readOnly=false,onOpenResult,onDirty,onSave}:Props){
 const [nodes,setNodes]=useNodesState(initialFlow.nodes),[edges,setEdges]=useEdgesState(initialFlow.edges)
 const [isDirty,setIsDirty]=useState(false),[saving,setSaving]=useState(false),saveLock=useRef(false)
 const [selected,setSelected]=useState<{nodes:Node[];edges:Edge[]}>({nodes:[],edges:[]}),[taskRef,setTaskRef]=useState(''),[sourceId,setSourceId]=useState(''),[targetId,setTargetId]=useState(''),[viewport,setViewport]=useState<Viewport>(initialFlow.viewport)
 const [fallbackOpen,setFallbackOpen]=useState(false),[referenceOpen,setReferenceOpen]=useState(false),[connectionOpen,setConnectionOpen]=useState(false)
 const largeGraph=nodes.length>80,[minimapVisible,setMinimapVisible]=useState(()=>initialFlow.nodes.length<=80&&!(typeof matchMedia==='function'&&matchMedia('(max-width: 700px)').matches))
 const taskById=useMemo(()=>new Map(tasks.map((task)=>[task.id,task])),[tasks]),resultByTask=useMemo(()=>new Map(taskResults.map((result)=>[result.taskId,result])),[taskResults]),nodeOptions=useMemo(()=>nodes.map((node)=>({id:node.id,label:String(node.data.label).split('\n')[0]})),[nodes])
 const dirty=useCallback((nextNodes=nodes,nextEdges=edges,nextViewport=viewport)=>{const next=!flowsEqualForDirty({nodes:nextNodes,edges:nextEdges,viewport:nextViewport},initialFlow);setIsDirty(next);onDirty?.(next)},[edges,initialFlow,nodes,onDirty,viewport])
 useEffect(()=>{if(isDirty)return;setNodes(initialFlow.nodes);setEdges(initialFlow.edges);setViewport(initialFlow.viewport)},[initialFlow,isDirty,setEdges,setNodes])
 const connect=useCallback((connection:Connection)=>{const next=connection.source&&connection.target&&connection.source!==connection.target&&!edges.some((edge)=>edge.source===connection.source&&edge.target===connection.target)?addEdge({...connection,animated:false},edges):edges;setEdges(next);dirty(nodes,next,viewport)},[dirty,edges,nodes,setEdges,viewport])
 const addNode=useCallback((kind:'card'|'text')=>{const task=taskById.get(taskRef);let index=1;const used=new Set(nodes.map((node)=>node.id));while(used.has(`user-node:${index}`))index++;const id=`user-node:${index}`,next=[...nodes,{id,position:{x:160+nodes.length*24,y:120+nodes.length*18},data:{label:task?`${task.title}\n${task.id}`:kind==='card'?'新しいカード':'テキストメモ',taskIds:task?[task.id]:[]},className:kind==='text'?'flow-text':'flow-card'}];setNodes(next);dirty(next,edges,viewport)},[dirty,edges,nodes,setNodes,taskById,taskRef,viewport])
 const openNode=useCallback((node:Node)=>{const data=node.data as {taskId?:unknown;taskIds?:unknown};const id=typeof data.taskId==='string'?data.taskId:Array.isArray(data.taskIds)&&typeof data.taskIds[0]==='string'?data.taskIds[0]:'';if(id)onOpenResult?.(id)},[onOpenResult])
 const remove=useCallback(()=>{const nodeIds=new Set(selected.nodes.map((node)=>node.id)),edgeIds=new Set(selected.edges.map((edge)=>edge.id)),nextNodes=nodes.filter((node)=>!nodeIds.has(node.id)),nextEdges=edges.filter((edge)=>!edgeIds.has(edge.id)&&!nodeIds.has(edge.source)&&!nodeIds.has(edge.target));setNodes(nextNodes);setEdges(nextEdges);dirty(nextNodes,nextEdges,viewport);setSelected({nodes:[],edges:[]})},[dirty,edges,nodes,selected,setEdges,setNodes,viewport])
 const connectSelected=useCallback(()=>{if(!sourceId||!targetId||sourceId===targetId)return;connect({source:sourceId,target:targetId,sourceHandle:null,targetHandle:null})},[connect,sourceId,targetId])
 const disconnectSelected=useCallback(()=>{if(!sourceId||!targetId)return;const next=edges.filter((edge)=>!(edge.source===sourceId&&edge.target===targetId));setEdges(next);dirty(nodes,next,viewport)},[dirty,edges,nodes,setEdges,sourceId,targetId,viewport])
 const moveSelected=useCallback((dx:number,dy:number)=>{const ids=new Set(selected.nodes.map((node)=>node.id)),next=nodes.map((node)=>ids.has(node.id)?{...node,position:{x:node.position.x+dx,y:node.position.y+dy}}:node);setNodes(next);dirty(next,edges,viewport)},[dirty,edges,nodes,selected.nodes,setNodes,viewport])
 const save=useCallback(async()=>{if(saveLock.current)return;saveLock.current=true;setSaving(true);try{if(await onSave({nodes,edges,viewport})){setIsDirty(false);onDirty?.(false)}}finally{saveLock.current=false;setSaving(false)}},[edges,nodes,onDirty,onSave,viewport])
 const discard=useCallback(()=>{setNodes(initialFlow.nodes);setEdges(initialFlow.edges);setViewport(initialFlow.viewport);setSelected({nodes:[],edges:[]});setSourceId('');setTargetId('');setIsDirty(false);onDirty?.(false)},[initialFlow,onDirty,setEdges,setNodes])
 const nodesChange=useCallback((changes:NodeChange[])=>{const next=applyNodeChanges(changes,nodes);setNodes(next);if(changes.some(persistedNodeChange))dirty(next,edges,viewport)},[dirty,edges,nodes,setNodes,viewport])
 const edgesChange=useCallback((changes:EdgeChange[])=>{const next=applyEdgeChanges(changes,edges);setEdges(next);if(changes.some(persistedEdgeChange))dirty(nodes,next,viewport)},[dirty,edges,nodes,setEdges,viewport])
 const keyDown=useCallback((event:React.KeyboardEvent)=>{if(event.key!=='Enter'&&event.key!==' ')return;const id=(event.target as HTMLElement).closest<HTMLElement>('.react-flow__node')?.dataset.id,node=nodes.find((item)=>item.id===id);if(node){event.preventDefault();openNode(node)}},[nodes,openNode])
 return <section className="canvas-section" aria-labelledby="canvas-title">
  <div className="section-heading"><div><span className="eyebrow">IDEATION SPACE</span><h2 id="canvas-title">プロジェクトキャンバス</h2><p><b>企画補助用です。進捗の正本ではありません。</b> タスク状態は「タスク進行表」で管理してください。</p></div><div className="form-actions"><button className="button primary" disabled={readOnly||saving} onClick={()=>void save()}><Save size={17}/>{saving?'保存中…':'保存'}</button><button className="button ghost" disabled={readOnly||saving} onClick={discard}><RotateCcw size={17}/>未保存変更を破棄</button></div></div>
  <div className="canvas-legend" aria-label="ノード種別"><span><i className="legend-user"/>通常ノード</span><span><i className="legend-complete"/>完了付箋（再オープン表示あり）</span><span><i className="legend-summary"/>週次summary</span></div>
  <div className="canvas-toolbar" aria-label="キャンバス操作"><button className="button ghost" disabled={readOnly} onClick={()=>addNode('card')}><Plus size={17}/>カード追加</button><button className="button ghost" disabled={readOnly} onClick={()=>addNode('text')}><StickyNote size={17}/>テキスト追加</button><button className="button danger" onClick={remove} disabled={readOnly||!selected.nodes.length&&!selected.edges.length}><Trash2 size={17}/>選択を削除</button><button className="button ghost" type="button" aria-pressed={minimapVisible} onClick={()=>setMinimapVisible((value)=>!value)}><MapIcon size={17}/>{minimapVisible?'ミニマップを隠す':'ミニマップを表示'}</button>{largeGraph&&<span className="toolbar-hint">大規模グラフのためミニマップは初期非表示です。</span>}</div>
  <details className="canvas-lazy-tools" open={referenceOpen} onToggle={(event)=>setReferenceOpen(event.currentTarget.open)}><summary>カードのタスク参照を設定</summary>{referenceOpen&&<div className="canvas-toolbar"><label htmlFor="canvas-task-ref">参照するタスク</label><select id="canvas-task-ref" value={taskRef} onChange={(event)=>setTaskRef(event.target.value)}><option value="">タスク参照なし</option>{tasks.map((task)=><option value={task.id} key={task.id}>{task.id} {task.title}</option>)}</select></div>}</details>
  <details className="canvas-lazy-tools" open={connectionOpen} onToggle={(event)=>setConnectionOpen(event.currentTarget.open)}><summary>ドラッグを使わない接続と移動</summary>{connectionOpen&&<div className="canvas-toolbar keyboard-tools" aria-label="ドラッグを使わない接続と移動"><div><label htmlFor="edge-source">接続元</label><select id="edge-source" value={sourceId} onChange={(event)=>setSourceId(event.target.value)}><option value="">選択</option>{nodeOptions.map((node)=><option key={node.id} value={node.id}>{node.label}</option>)}</select></div><div><label htmlFor="edge-target">接続先</label><select id="edge-target" value={targetId} onChange={(event)=>setTargetId(event.target.value)}><option value="">選択</option>{nodeOptions.map((node)=><option key={node.id} value={node.id}>{node.label}</option>)}</select></div><button className="button ghost" onClick={connectSelected} disabled={readOnly||!sourceId||!targetId||sourceId===targetId}><Link2 size={15}/>接続</button><button className="button ghost" onClick={disconnectSelected} disabled={readOnly||!sourceId||!targetId}>接続解除</button><fieldset><legend>選択ノードを移動</legend><button type="button" onClick={()=>moveSelected(0,-20)} disabled={readOnly||!selected.nodes.length} aria-label="上へ移動">↑</button><button type="button" onClick={()=>moveSelected(-20,0)} disabled={readOnly||!selected.nodes.length} aria-label="左へ移動">←</button><button type="button" onClick={()=>moveSelected(20,0)} disabled={readOnly||!selected.nodes.length} aria-label="右へ移動">→</button><button type="button" onClick={()=>moveSelected(0,20)} disabled={readOnly||!selected.nodes.length} aria-label="下へ移動">↓</button></fieldset></div>}</details>
  <div className="flow-shell"><ReactFlow nodes={nodes} edges={edges} viewport={viewport} onlyRenderVisibleElements nodesDraggable={!readOnly} nodesConnectable={!readOnly} nodesFocusable onNodeClick={(_,node)=>openNode(node)} onKeyDown={keyDown} onMoveEnd={(_,next)=>{setViewport(next);if(!readOnly)dirty(nodes,edges,next)}} onNodesChange={nodesChange} onEdgesChange={edgesChange} onConnect={connect} onSelectionChange={setSelected} deleteKeyCode={readOnly?null:['Backspace','Delete']} aria-label="プロジェクトフローキャンバス"><Background color="#25365f" gap={28}/><Controls position="bottom-left"/>{minimapVisible&&<MiniMap aria-label="キャンバスミニマップ" pannable zoomable nodeColor="#4f7cff" maskColor="rgba(6,9,19,.72)"/>}</ReactFlow></div>
  <details className="canvas-fallback" open={fallbackOpen} onToggle={(event)=>setFallbackOpen(event.currentTarget.open)}><summary>キャンバス一覧（キーボード・モバイル用）</summary>{fallbackOpen&&<ul>{nodes.map((node)=>{const data=node.data as {taskId?:unknown;taskIds?:unknown};const taskId=typeof data.taskId==='string'?data.taskId:Array.isArray(data.taskIds)&&typeof data.taskIds[0]==='string'?data.taskIds[0]:'',task=taskById.get(taskId),result=resultByTask.get(taskId),progress=checklistProgress(result?.checklistItems),label=task&&isMilestoneChecklist(task)?result?.checklistItems===undefined?'チェックリストを作成':progress.total===0?'チェック項目を追加':`チェックリスト ${progress.completed}/${progress.total}`:'成果シート';return <li key={node.id}><span>{String(node.data.label).split('\n')[0]}</span>{taskId&&<button className="button ghost" onClick={()=>onOpenResult?.(taskId)}>{taskId} の{label}</button>}</li>})}</ul>}</details>
 </section>
}
