import { useEffect, useRef, useState } from 'react'
import { addEdge, applyEdgeChanges, applyNodeChanges, Background, Controls, MiniMap, ReactFlow, useEdgesState, useNodesState, type Connection, type Edge, type Node, type Viewport } from '@xyflow/react'
import { Link2, Plus, RotateCcw, Save, StickyNote, Trash2 } from 'lucide-react'
import type { FlowData, Task, TaskResultSheet } from '../types'
import { checklistProgress, isMilestoneChecklist } from '../checklistTemplates'
import { flowsEqualForDirty } from './flowDirty'

type Props={initialFlow:FlowData;tasks:Task[];taskResults?:TaskResultSheet[];readOnly?:boolean;onOpenResult?:(taskId:string)=>void;onDirty?:(dirty:boolean)=>void;onSave:(flow:FlowData)=>Promise<boolean>|boolean}
export function ProjectCanvas({initialFlow,tasks,taskResults=[],readOnly=false,onOpenResult,onDirty,onSave}:Props){
 const [nodes,setNodes]=useNodesState(initialFlow.nodes),[edges,setEdges]=useEdgesState(initialFlow.edges)
 const [isDirty,setIsDirty]=useState(false),[saving,setSaving]=useState(false),saveLock=useRef(false)
 const [selected,setSelected]=useState<{nodes:Node[];edges:Edge[]}>({nodes:[],edges:[]})
 const [taskRef,setTaskRef]=useState(''),[sourceId,setSourceId]=useState(''),[targetId,setTargetId]=useState(''),[viewport,setViewport]=useState<Viewport>(initialFlow.viewport)
 const dirty=(nextNodes=nodes,nextEdges=edges,nextViewport=viewport)=>{const next=!flowsEqualForDirty({nodes:nextNodes,edges:nextEdges,viewport:nextViewport},initialFlow);setIsDirty(next);onDirty?.(next)}
 useEffect(()=>{if(isDirty)return;setNodes(initialFlow.nodes);setEdges(initialFlow.edges);setViewport(initialFlow.viewport)},[initialFlow,isDirty,setEdges,setNodes])
 const connect=(connection:Connection)=>{const next=connection.source&&connection.target&&connection.source!==connection.target&&!edges.some((edge)=>edge.source===connection.source&&edge.target===connection.target)?addEdge({...connection,animated:true},edges):edges;setEdges(next);dirty(nodes,next,viewport)}
 const addNode=(kind:'card'|'text')=>{const task=tasks.find((item)=>item.id===taskRef);let index=1;const used=new Set(nodes.map((node)=>node.id));while(used.has(`user-node:${index}`))index++;const id=`user-node:${index}`,next=[...nodes,{id,position:{x:160+nodes.length*24,y:120+nodes.length*18},data:{label:task?`${task.title}\n${task.id}`:kind==='card'?'新しいカード':'テキストメモ',taskIds:task?[task.id]:[]},className:kind==='text'?'flow-text':'flow-card'}];setNodes(next);dirty(next,edges,viewport)}
 const openNode=(node:Node)=>{const data=node.data as {taskId?:unknown;taskIds?:unknown};const id=typeof data.taskId==='string'?data.taskId:Array.isArray(data.taskIds)&&typeof data.taskIds[0]==='string'?data.taskIds[0]:'';if(id)onOpenResult?.(id)}
 const remove=()=>{const nodeIds=new Set(selected.nodes.map((node)=>node.id)),edgeIds=new Set(selected.edges.map((edge)=>edge.id)),nextNodes=nodes.filter((node)=>!nodeIds.has(node.id)),nextEdges=edges.filter((edge)=>!edgeIds.has(edge.id)&&!nodeIds.has(edge.source)&&!nodeIds.has(edge.target));setNodes(nextNodes);setEdges(nextEdges);dirty(nextNodes,nextEdges,viewport);setSelected({nodes:[],edges:[]})}
 const connectSelected=()=>{if(!sourceId||!targetId||sourceId===targetId)return;connect({source:sourceId,target:targetId,sourceHandle:null,targetHandle:null})}
 const disconnectSelected=()=>{if(!sourceId||!targetId)return;const next=edges.filter((edge)=>!(edge.source===sourceId&&edge.target===targetId));setEdges(next);dirty(nodes,next,viewport)}
 const moveSelected=(dx:number,dy:number)=>{const ids=new Set(selected.nodes.map((node)=>node.id)),next=nodes.map((node)=>ids.has(node.id)?{...node,position:{x:node.position.x+dx,y:node.position.y+dy}}:node);setNodes(next);dirty(next,edges,viewport)}
 const save=async()=>{if(saveLock.current)return;saveLock.current=true;setSaving(true);try{if(await onSave({nodes,edges,viewport})){setIsDirty(false);onDirty?.(false)}}finally{saveLock.current=false;setSaving(false)}}
 const discard=()=>{setNodes(initialFlow.nodes);setEdges(initialFlow.edges);setViewport(initialFlow.viewport);setSelected({nodes:[],edges:[]});setSourceId('');setTargetId('');setIsDirty(false);onDirty?.(false)}
 return <section className="canvas-section" aria-labelledby="canvas-title">
  <div className="section-heading"><div><span className="eyebrow">IDEATION SPACE</span><h2 id="canvas-title">プロジェクトキャンバス</h2><p><b>企画補助用です。進捗の正本ではありません。</b> タスク状態は「タスク進行表」で管理してください。</p></div><div className="form-actions"><button className="button primary" disabled={readOnly||saving} onClick={()=>void save()}><Save size={17}/>{saving?'保存中…':'保存'}</button><button className="button ghost" disabled={readOnly||saving} onClick={discard}><RotateCcw size={17}/>未保存変更を破棄</button></div></div>
  <div className="canvas-legend" aria-label="ノード種別"><span><i className="legend-user"/>通常ノード</span><span><i className="legend-complete"/>完了付箋（再オープン表示あり）</span><span><i className="legend-summary"/>週次summary</span></div>
  <div className="canvas-toolbar" aria-label="キャンバス操作">
    <div><label className="sr-only" htmlFor="canvas-task-ref">参照するタスク</label><select id="canvas-task-ref" value={taskRef} onChange={(event)=>setTaskRef(event.target.value)}><option value="">タスク参照なし</option>{tasks.map((task)=><option value={task.id} key={task.id}>{task.id} {task.title}</option>)}</select></div>
    <button className="button ghost" disabled={readOnly} onClick={()=>addNode('card')}><Plus size={17}/>カード追加</button><button className="button ghost" disabled={readOnly} onClick={()=>addNode('text')}><StickyNote size={17}/>テキスト追加</button><button className="button danger" onClick={remove} disabled={readOnly||!selected.nodes.length&&!selected.edges.length}><Trash2 size={17}/>選択を削除</button>
  </div>
  <div className="canvas-toolbar keyboard-tools" aria-label="ドラッグを使わない接続と移動">
    <div><label htmlFor="edge-source">接続元</label><select id="edge-source" value={sourceId} onChange={(event)=>setSourceId(event.target.value)}><option value="">選択</option>{nodes.map((node)=><option key={node.id} value={node.id}>{String(node.data.label).split('\n')[0]}</option>)}</select></div>
    <div><label htmlFor="edge-target">接続先</label><select id="edge-target" value={targetId} onChange={(event)=>setTargetId(event.target.value)}><option value="">選択</option>{nodes.map((node)=><option key={node.id} value={node.id}>{String(node.data.label).split('\n')[0]}</option>)}</select></div>
    <button className="button ghost" onClick={connectSelected} disabled={readOnly||!sourceId||!targetId||sourceId===targetId}><Link2 size={15}/>接続</button><button className="button ghost" onClick={disconnectSelected} disabled={readOnly||!sourceId||!targetId}>接続解除</button>
    <fieldset><legend>選択ノードを移動</legend><button type="button" onClick={()=>moveSelected(0,-20)} disabled={readOnly||!selected.nodes.length} aria-label="上へ移動">↑</button><button type="button" onClick={()=>moveSelected(-20,0)} disabled={readOnly||!selected.nodes.length} aria-label="左へ移動">←</button><button type="button" onClick={()=>moveSelected(20,0)} disabled={readOnly||!selected.nodes.length} aria-label="右へ移動">→</button><button type="button" onClick={()=>moveSelected(0,20)} disabled={readOnly||!selected.nodes.length} aria-label="下へ移動">↓</button></fieldset>
  </div>
  <p className="toolbar-hint"><Link2 size={15}/>ドラッグ操作の代わりに、上の選択欄と移動ボタンを利用できます。</p>
  <div className="flow-shell">
   <ReactFlow nodes={nodes} edges={edges} viewport={viewport} nodesDraggable={!readOnly} nodesConnectable={!readOnly} nodesFocusable onNodeClick={(_,node)=>openNode(node)} onKeyDown={(event)=>{if(event.key!=='Enter'&&event.key!==' ')return;const id=(event.target as HTMLElement).closest<HTMLElement>('.react-flow__node')?.dataset.id,node=nodes.find((item)=>item.id===id);if(node){event.preventDefault();openNode(node)}}} onMoveEnd={(_,next)=>{setViewport(next);if(!readOnly)dirty(nodes,edges,next)}} onNodesChange={(changes)=>{const next=applyNodeChanges(changes,nodes);setNodes(next);dirty(next,edges,viewport)}} onEdgesChange={(changes)=>{const next=applyEdgeChanges(changes,edges);setEdges(next);dirty(nodes,next,viewport)}} onConnect={connect} onSelectionChange={setSelected} deleteKeyCode={readOnly?null:['Backspace','Delete']} aria-label="プロジェクトフローキャンバス">
    <Background color="#25365f" gap={28}/><Controls position="bottom-left"/><MiniMap aria-label="キャンバスミニマップ" pannable zoomable nodeColor="#4f7cff" maskColor="rgba(6,9,19,.72)"/>
   </ReactFlow>
  </div>
  <details className="canvas-fallback"><summary>キャンバス一覧（キーボード・モバイル用）</summary><ul>{nodes.map((node)=>{const data=node.data as {taskId?:unknown;taskIds?:unknown};const taskId=typeof data.taskId==='string'?data.taskId:Array.isArray(data.taskIds)&&typeof data.taskIds[0]==='string'?data.taskIds[0]:'',task=tasks.find((item)=>item.id===taskId),result=taskResults.find((item)=>item.taskId===taskId),progress=checklistProgress(result?.checklistItems),label=task&&isMilestoneChecklist(task)?`チェックリスト${progress.total?` ${progress.completed}/${progress.total}`:''}`:'成果シート';return <li key={node.id}><span>{String(node.data.label).split('\n')[0]}</span>{taskId&&<button className="button ghost" onClick={()=>onOpenResult?.(taskId)}>{taskId} の{label}</button>}</li>})}</ul></details>
 </section>
}
