import { useState } from 'react'
import { fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it, vi } from 'vitest'
import { initialTasks } from '../data'
import type { Task, ValidationIssue } from '../types'
import { TaskBoard, deadlineState } from './TaskBoard'

const props=()=>({tasks:initialTasks,view:'list' as const,search:'',department:'',status:'',phase:'0',person:'',dueView:'' as const,groupByTeam:false,setSearch:vi.fn(),setDepartment:vi.fn(),setStatus:vi.fn(),setPhase:vi.fn(),setPerson:vi.fn(),setDueView:vi.fn(),onAdd:vi.fn(),onSave:vi.fn().mockResolvedValue([]),onDelete:vi.fn(),onStatus:vi.fn().mockResolvedValue({ok:true})})
function FilterHarness({mode}:{mode:'search'|'team'}){const original=initialTasks[0],[tasks,setTasks]=useState<Task[]>([structuredClone(original)]),[search,setSearch]=useState(mode==='search'?'YUKISHIROさん': ''),[department,setDepartment]=useState(mode==='team'?original.teamId:'');return <TaskBoard {...props()} tasks={tasks} search={search} department={department} phase="0" setSearch={setSearch} setDepartment={setDepartment} onSave={async(task)=>{setTasks([task]);return[]}}/>}
describe('TaskBoard UI',()=>{
  it('defaults to a phase-filtered view and supports all phase',()=>{const value=props();render(<TaskBoard {...value}/>);expect(screen.getByText('9 / 73 件を表示')).toBeVisible();fireEvent.click(screen.getByRole('tab',{name:/全体/}));expect(value.setPhase).toHaveBeenCalledWith('')})
  it('supports phase tab arrow, Home and End keyboard navigation',()=>{const value=props();render(<TaskBoard {...value}/>);const phase0=screen.getByRole('tab',{name:/Phase 0/});fireEvent.keyDown(phase0,{key:'ArrowRight'});expect(value.setPhase).toHaveBeenCalledWith('1');fireEvent.keyDown(phase0,{key:'End'});expect(value.setPhase).toHaveBeenCalledWith('6')})
  it('uses stable team IDs and person filters with assignee-only badges',()=>{const value=props();render(<TaskBoard {...value}/>);fireEvent.change(screen.getByLabelText('チームで絞り込み'),{target:{value:'administration'}});expect(value.setDepartment).toHaveBeenCalledWith('administration');const button=within(screen.getByLabelText('担当者フィルタ')).getByRole('button',{name:/スン/});expect(button).toHaveTextContent('3 高 / 6件');fireEvent.click(button);expect(value.setPerson).toHaveBeenCalledWith('スン')})
  it('filters only assignee personKeys and never mixes in the owner',()=>{const value=props();render(<TaskBoard {...value} search="P0-01" person="ロブ"/>);expect(screen.getByText('該当するタスクがありません')).toBeVisible();expect(initialTasks.find((task)=>task.id==='P5-01')?.personKeys).toEqual(['鈴木','ユウタ','ウメノ','ロブ','浜名','ウニュ','原田','スン'])})
  it('separates owner and assignees and exposes blocker state',()=>{const value=props();render(<TaskBoard {...value} phase="3" search="P3-05"/>);const card=screen.getByText(/告知用クリエイティブ制作/).closest('article')!;expect(within(card).getByText(/責任者/)).toHaveTextContent('鈴木');expect(within(card).getByText(/担当/)).toHaveTextContent('スン');expect(within(card).getByText(/ブロック中/)).toHaveTextContent('P0-07');expect(within(card).getByText(/解除条件/)).toBeVisible()})
  it('shows old overdue and revised deadline independently for P0-01',()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-08-14T12:00:00+09:00'));try{expect(deadlineState(initialTasks[0])).toMatchObject({kind:'overdue',label:'旧期限超過 / 改訂期限まで4日',days:4});const value=props();render(<TaskBoard {...value} search="P0-01" dueView="soon"/>);expect(screen.getByText('即時（〜8/18）')).toBeVisible();expect(screen.getByText('旧期限超過 / 改訂期限まで4日')).toBeVisible()}finally{vi.useRealTimers()}})
  it('provides explicit status labels and 44px-ready controls',()=>{const value=props();render(<TaskBoard {...value} phase="5"/>);expect(screen.getAllByLabelText(/ステータス/)).toHaveLength(8);expect(document.querySelectorAll('.phase5-check').length).toBe(8)})
  it('preserves raw assignee annotations and disables deletion of authoritative tasks',()=>{const value=props();render(<TaskBoard {...value} phase="3" search="P3-05"/>);expect(screen.getByRole('button',{name:'担当者を直接編集'})).toHaveTextContent('鈴木、ウメノ、（スン※契約後）');expect(screen.getByRole('button',{name:/告知用クリエイティブ制作.*削除/})).toBeDisabled()})
  it('opens by keyboard, ignores IME Enter, restores its trigger after Ctrl+Enter, and continues Tab order',async()=>{const value=props(),dirty=vi.fn(),user=userEvent.setup();render(<TaskBoard {...value} search="P0-01" onDirty={dirty}/>);const trigger=screen.getByRole('button',{name:'タスク名を直接編集'});trigger.focus();await user.keyboard('{Enter}');const title=screen.getByLabelText('タスク名');expect(title).toHaveFocus();fireEvent.change(title,{target:{value:'直接編集済み'}});expect(dirty).toHaveBeenCalledWith(true);fireEvent.keyDown(title,{key:'Enter',ctrlKey:true,isComposing:true,keyCode:229});expect(value.onSave).not.toHaveBeenCalled();fireEvent.keyDown(title,{key:'Enter',ctrlKey:true});await vi.waitFor(()=>expect(value.onSave).toHaveBeenCalled());expect(value.onSave.mock.calls[0][0]).toMatchObject({id:'P0-01',title:'直接編集済み',sourceRefs:initialTasks[0].sourceRefs});await vi.waitFor(()=>expect(screen.getByRole('button',{name:'タスク名を直接編集'})).toHaveFocus());await user.tab();expect(screen.getByRole('button',{name:'担当チームを直接編集'})).toHaveFocus()})
  it('keeps the controlled inline draft and restores the save button focus when saving fails',async()=>{const value=props();value.onSave.mockResolvedValue([{path:'title',message:'競合のため保存できません'}]);render(<TaskBoard {...value} search="P0-01"/>);fireEvent.click(screen.getByRole('button',{name:'タスク名を直接編集'}));const title=screen.getByLabelText('タスク名');fireEvent.change(title,{target:{value:'失敗後も保持するdraft'}});const save=screen.getByRole('button',{name:'変更を保存'});fireEvent.click(save);expect(await screen.findByRole('alert')).toHaveTextContent('競合のため保存できません');expect(title).toHaveValue('失敗後も保持するdraft');await vi.waitFor(()=>expect(save).toHaveFocus())})
  it('disables inline fields while a delayed save is pending and restores its trigger focus',async()=>{const value=props(),user=userEvent.setup();let finish:(issues:ValidationIssue[])=>void=()=>undefined;value.onSave.mockImplementation(()=>new Promise((resolve)=>{finish=resolve}));render(<TaskBoard {...value} search="P0-01"/>);await user.click(screen.getByRole('button',{name:'タスク名を直接編集'}));const title=screen.getByLabelText('タスク名'),form=title.closest('form')!;await user.clear(title);await user.type(title,'送信snapshot');await user.click(screen.getByRole('button',{name:'変更を保存'}));await vi.waitFor(()=>expect(form).toHaveAttribute('aria-busy','true'));expect(title).toBeDisabled();await user.type(title,'追加入力');expect(title).toHaveValue('送信snapshot');expect(value.onSave.mock.calls[0][0].title).toBe('送信snapshot');finish([]);await vi.waitFor(()=>expect(screen.getByRole('button',{name:'タスク名を直接編集'})).toHaveFocus())})
  it('focuses search, announces filter exclusion, and preserves Tab order after a Ctrl+Enter title save',async()=>{const user=userEvent.setup();render(<FilterHarness mode="search"/>);await user.click(screen.getByRole('button',{name:'タスク名を直接編集'}));const title=screen.getByLabelText('タスク名');await user.clear(title);await user.type(title,'検索条件に一致しない名前');fireEvent.keyDown(title,{key:'Enter',ctrlKey:true});await vi.waitFor(()=>expect(document.querySelector('[data-task-id]')).not.toBeInTheDocument());const search=screen.getByPlaceholderText('ID・タスク・担当・出典を検索');await vi.waitFor(()=>expect(search).toHaveFocus());expect(screen.getByRole('status')).toHaveTextContent('現在の絞り込み条件に一致しなくなりました');await user.tab();expect(screen.getByLabelText('チームで絞り込み')).toHaveFocus()})
  it('focuses search when a saved team change removes the card from the team filter',async()=>{const user=userEvent.setup();render(<FilterHarness mode="team"/>);await user.click(screen.getByRole('button',{name:'担当チームを直接編集'}));const team=screen.getByLabelText('担当チーム'),next=[...team.querySelectorAll('option')].find((option)=>option.value!==initialTasks[0].teamId)!.value;await user.selectOptions(team,next);fireEvent.keyDown(team,{key:'Enter',ctrlKey:true});await vi.waitFor(()=>expect(document.querySelector('[data-task-id]')).not.toBeInTheDocument());const search=screen.getByPlaceholderText('ID・タスク・担当・出典を検索');await vi.waitFor(()=>expect(search).toHaveFocus());expect(screen.getByRole('status')).toHaveTextContent('現在の絞り込み条件に一致しなくなりました');await user.tab();expect(screen.getByLabelText('チームで絞り込み')).toHaveFocus()})
  it('restores the confirmed status when immediate persistence fails',async()=>{const value=props();value.onStatus.mockResolvedValue({ok:false,issues:['状態保存に失敗しました']});render(<TaskBoard {...value} search="P0-01"/>);const status=screen.getByLabelText(/ステータス/);fireEvent.change(status,{target:{value:'進行中'}});expect(await screen.findByRole('alert')).toHaveTextContent('状態保存に失敗しました');expect(status).toHaveValue(initialTasks[0].status)})
  it('labels milestone navigation as checklist with textual progress',()=>{const value=props(),task={...initialTasks[0],id:'AUTO-2026-W33-01',title:'milestone',sourceRefs:[],provenance:{ruleId:'milestone-checklist',sourceTaskId:'P0-01',dependencyIds:[]}},item={id:'c1',title:'item',status:'完了' as const,acceptanceCriteria:'criteria',assignee:'owner',reviewer:'reviewer',reviewedAt:'2026-08-17T00:00:00.000Z',evidenceMemo:'evidence',holdReason:''};render(<TaskBoard {...value} tasks={[task]} taskResults={[{id:'task-result:AUTO-2026-W33-01',taskId:task.id,resultBody:'',verificationState:'未確認',verificationSummary:'',deliverables:[],checklistItems:[item,{...item,id:'c2',status:'未着手'}],nextStep:'',completionCriteria:'',verificationMemo:'',updatedAt:'2026-08-17T00:00:00.000Z'}]} search="milestone" onResult={vi.fn()}/>);expect(screen.getByRole('button',{name:/チェックリスト 1\/2/})).toBeVisible()})
  it('warns about a legacy invalid completed milestone while allowing correction away from complete',()=>{const value=props(),task={...initialTasks[0],id:'AUTO-2026-W33-01',title:'legacy milestone',status:'完了' as const,sourceRefs:[],provenance:{ruleId:'milestone-checklist',sourceTaskId:'P0-01',dependencyIds:[]}};render(<TaskBoard {...value} tasks={[task]} taskResults={[]} search="legacy milestone"/>);const warning=screen.getByText(/完了状態とチェックリストが不整合/).closest('.milestone-completion-warning')!,select=screen.getByLabelText('legacy milestoneのステータス');expect(warning).toHaveTextContent('構造化チェックリストを1件以上');expect(select).toHaveAttribute('aria-describedby',warning.id);fireEvent.change(select,{target:{value:'進行中'}});expect(value.onStatus).toHaveBeenCalledWith(task.id,'進行中')})
})
