import { useEffect, useRef, useState } from 'react'
import { ArrowDown, ArrowLeft, ArrowUp, ExternalLink, Plus, RotateCcw, Save, Trash2 } from 'lucide-react'
import { checklistProgress, checklistTemplate, isMilestoneChecklist } from '../checklistTemplates'
import { checklistStatuses, deliverableAccessStates, deliverableTypes, verificationStates, type ChecklistItem, type Deliverable, type Task, type TaskResultSheet as Result } from '../types'

type Props={task:Task;sourceTask?:Task;value?:Result;readOnly?:boolean;busy?:boolean;error?:string;dirty?:boolean;onBack:()=>void;onDiscardAndBack?:()=>void;onSave:(value:Result)=>Promise<boolean>|boolean;onDirty?:(dirty:boolean)=>void}
type FormError={fieldId:string;message:string}
const emptyTaskResult=(taskId:string):Result=>({id:`task-result:${taskId}`,taskId,resultBody:'',verificationState:'未確認',verificationSummary:'',deliverables:[],nextStep:'',completionCriteria:'',verificationMemo:'',updatedAt:new Date(0).toISOString()})
const nextId=(prefix:string,items:{id:string}[])=>{let index=1;const used=new Set(items.map((item)=>item.id));while(used.has(`${prefix}:${index}`))index++;return`${prefix}:${index}`}
const meaningful=(value:string)=>value.replace(/[\s\u200b-\u200d\ufeff]/gu,'').length>0

export function TaskResultSheet({task,sourceTask,value,readOnly=false,busy=false,error,dirty=false,onBack,onDiscardAndBack,onSave,onDirty}:Props){
 const heading=useRef<HTMLHeadingElement>(null),saveButton=useRef<HTMLButtonElement>(null),restoreSaveFocus=useRef(false),submitting=useRef(false),[draft,setDraft]=useState<Result>(()=>value??emptyTaskResult(task.id)),baseline=useRef<Result>(structuredClone(draft)),[localError,setLocalError]=useState(''),[formErrors,setFormErrors]=useState<FormError[]>([]),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),milestone=isMilestoneChecklist(task),items=draft.checklistItems,progress=checklistProgress(items),localDirty=JSON.stringify(draft)!==JSON.stringify(baseline.current),isSaving=busy||saving
 useEffect(()=>{heading.current?.focus()},[])
 useEffect(()=>{onDirty?.(localDirty)},[localDirty,onDirty])
 useEffect(()=>{if(localDirty||!value&&saved)return;const next=value??emptyTaskResult(task.id);baseline.current=structuredClone(next);setDraft(next)},[localDirty,saved,task.id,value])
 useEffect(()=>{if(isSaving||!restoreSaveFocus.current)return;const frame=requestAnimationFrame(()=>{saveButton.current?.focus();restoreSaveFocus.current=false});return()=>cancelAnimationFrame(frame)},[isSaving])
 const set=(field:keyof Result,next:unknown)=>{setSaved(false);setDraft((current)=>({...current,[field]:next}))}
 const setChecklist=(next:ChecklistItem[])=>set('checklistItems',next)
 const updateChecklist=(index:number,field:keyof ChecklistItem,next:string)=>setChecklist((items??[]).map((item,itemIndex)=>itemIndex===index?{...item,[field]:next}:item))
 const updateChecklistStatus=(index:number,next:ChecklistItem['status'])=>{const item=(items??[])[index];if(!item)return;const errors:FormError[]=[];if(next==='完了'){if(!meaningful(item.reviewer))errors.push({fieldId:`checklist-${index}-reviewer`,message:`項目${index+1}: 完了には確認者が必要です。`});if(!item.reviewedAt)errors.push({fieldId:`checklist-${index}-reviewed-at`,message:`項目${index+1}: 完了には確認日時が必要です。`});if(!meaningful(item.evidenceMemo))errors.push({fieldId:`checklist-${index}-evidence`,message:`項目${index+1}: 完了には証跡メモが必要です。`})}if(next==='保留'&&!meaningful(item.holdReason))errors.push({fieldId:`checklist-${index}-hold`,message:`項目${index+1}: 保留理由を入力してから状態を確定してください。`});if(errors.length){setFormErrors((current)=>[...current.filter((entry)=>!entry.fieldId.startsWith(`checklist-${index}-`)),...errors]);requestAnimationFrame(()=>document.getElementById(errors[0].fieldId)?.focus());return}setFormErrors((current)=>current.filter((entry)=>!entry.fieldId.startsWith(`checklist-${index}-`)));updateChecklist(index,'status',next)}
 const addChecklist=()=>{const current=items??[];setChecklist([...current,{id:nextId(`checklist:${task.id}`,current),title:'',status:'未着手',acceptanceCriteria:'',assignee:'',reviewer:'',reviewedAt:'',evidenceMemo:'',holdReason:''}])}
 const moveChecklist=(index:number,delta:number)=>{const next=[...(items??[])],target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setChecklist(next)}
 const updateDeliverable=(index:number,field:keyof Deliverable,next:string)=>set('deliverables',draft.deliverables.map((item,itemIndex)=>itemIndex===index?{...item,[field]:next}:item))
 const addDeliverable=()=>set('deliverables',[...draft.deliverables,{id:nextId(`deliverable:${task.id}`,draft.deliverables),title:'',type:'url',href:'https://',accessState:'未確認'}])
 const moveDeliverable=(index:number,delta:number)=>{const next=[...draft.deliverables],target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];set('deliverables',next)}
 const validate=()=>{const errors:FormError[]=[];if(milestone&&(items??[]).length>64)errors.push({fieldId:'checklist-add',message:'チェックリストは64件以下にしてください。'});const ids=new Set<string>();(items??[]).forEach((item,index)=>{const number=index+1,prefix=`checklist-${index}`;if(!meaningful(item.id)||item.id.length>100||ids.has(item.id))errors.push({fieldId:`${prefix}-title`,message:`項目${number}: 一意な安定IDが必要です。`});ids.add(item.id);if(!meaningful(item.title))errors.push({fieldId:`${prefix}-title`,message:`項目${number}: 実施項目を入力してください。`});if(!meaningful(item.acceptanceCriteria))errors.push({fieldId:`${prefix}-acceptance`,message:`項目${number}: 受入条件を入力してください。`});if(item.status==='完了'){if(!meaningful(item.reviewer))errors.push({fieldId:`${prefix}-reviewer`,message:`項目${number}: 完了には確認者が必要です。`});if(!item.reviewedAt)errors.push({fieldId:`${prefix}-reviewed-at`,message:`項目${number}: 完了には確認日時が必要です。`});if(!meaningful(item.evidenceMemo))errors.push({fieldId:`${prefix}-evidence`,message:`項目${number}: 完了には証跡メモが必要です。`})}if(item.status==='保留'&&!meaningful(item.holdReason))errors.push({fieldId:`${prefix}-hold`,message:`項目${number}: 保留理由を入力してください。`})});setFormErrors(errors);return errors}
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(submitting.current)return;const errors=validate();if(errors.length){document.getElementById(errors[0].fieldId)?.focus();return}submitting.current=true;setSaving(true);setLocalError('');setSaved(false);try{const next={...draft,updatedAt:new Date().toISOString()},ok=await onSave(next);if(ok){baseline.current=structuredClone(next);onDirty?.(false);setDraft(next);setSaved(true)}else setLocalError('保存できませんでした。入力内容は保持しています。')}finally{submitting.current=false;restoreSaveFocus.current=true;setSaving(false)}}
 const discard=()=>{const next=value??baseline.current;setDraft(structuredClone(next));baseline.current=structuredClone(next);setFormErrors([]);setLocalError('');setSaved(false);onDirty?.(false)}
 const fieldError=(id:string)=>formErrors.find((item)=>item.fieldId===id),templates=milestone?checklistTemplate(task,sourceTask):[]
 return <section className="result-sheet" aria-labelledby="result-sheet-title">
  <header className="result-sheet-header"><div className="result-back-actions"><button className="button ghost" type="button" onClick={onBack}><ArrowLeft size={17}/>進行表に戻る</button>{(dirty||localDirty)&&<button className="button ghost" type="button" disabled={busy} onClick={onDiscardAndBack??onBack}>変更を破棄して戻る</button>}</div><div><span className="eyebrow">{milestone?'MILESTONE CHECKLIST':'TASK RESULT'}</span><h2 id="result-sheet-title" tabIndex={-1} ref={heading}>{task.id} {milestone?'チェックリスト':'成果シート'}</h2><p>{task.title}</p>{sourceTask&&<p className="source-task-summary"><b>元タスク {sourceTask.id}</b> {sourceTask.title}<br/>担当: {sourceTask.rawAssignees||sourceTask.owner} / 期限: {sourceTask.deadline}</p>}</div><span className={`verification-state state-${draft.verificationState}`}>{milestone?`${progress.completed}/${progress.total} 完了`:value?draft.verificationState:'未登録'}</span></header>
  {milestone&&<div className="result-workflow" aria-label="成果シートの流れ"><b>チェックリスト</b><span>→</span><span>結果</span><span>→</span><span>成果物</span><span>→</span><span>全体確認</span><span>→</span><span>次工程</span></div>}
  <nav className="result-section-nav" aria-label="成果シート内メニュー">{milestone&&<a href="#result-checklist">チェックリスト</a>}<a href="#result-body">結果</a><a href="#result-deliverables">成果物</a><a href="#result-verification">全体確認</a><a href="#result-next">次工程</a></nav>
  {readOnly&&<p className="read-only-banner" role="status">viewerは読み取り専用です。</p>}{isSaving&&<p role="status">成果シートを保存中です。編集欄は一時的に無効です。</p>}{saved&&<p className="cloud-success" role="status">成果シートを保存しました。引き続き直接編集できます。</p>}{(localError||error)&&<p className="cloud-error" role="alert">{localError||error}</p>}
  {readOnly?<ResultView milestone={milestone} draft={draft}/>:<form className="result-sheet-form" aria-busy={isSaving} onSubmit={submit} noValidate><fieldset className="result-edit-fields" disabled={isSaving}><legend className="sr-only">成果シート編集項目</legend>
   {milestone&&<fieldset id="result-checklist"><legend>マイルストーンチェックリスト</legend>{items===undefined?<div className="checklist-template"><p>元タスクから作った推奨テンプレートです。実績、確認者、確認日時、証跡は未入力です。</p><ol>{templates.map((item)=><li key={item.id}><b>{item.title}</b><span>受入条件: {item.acceptanceCriteria}</span></li>)}</ol><div className="form-actions"><button type="button" className="button primary" onClick={()=>setChecklist(templates)}>テンプレートを使用</button><button type="button" className="button ghost" onClick={()=>setChecklist([])}>空で作成</button></div></div>:<><ChecklistProgress items={items}/>{formErrors.length>0&&<div className="checklist-errors" role="alert" aria-labelledby="checklist-errors-title"><b id="checklist-errors-title">入力エラー {formErrors.length}件</b><ul>{formErrors.map((item,index)=><li key={`${item.fieldId}-${index}`}><a href={`#${item.fieldId}`}>{item.message}</a></li>)}</ul></div>}{items.map((item,index)=><ChecklistEditor key={item.id} item={item} index={index} count={items.length} update={updateChecklist} updateStatus={updateChecklistStatus} move={moveChecklist} remove={()=>setChecklist(items.filter((_,itemIndex)=>itemIndex!==index))} error={fieldError}/>)}<button id="checklist-add" className="button ghost" type="button" onClick={addChecklist} disabled={items.length>=64}><Plus size={17}/>項目を追加</button></>}</fieldset>}
   <section id="result-body"><TextArea label="結果" value={draft.resultBody} maxLength={10000} onChange={(next)=>set('resultBody',next)}/></section>
   <div id="result-deliverables"><DeliverableEditor draft={draft} update={updateDeliverable} move={moveDeliverable} add={addDeliverable} set={set}/></div>
   <fieldset id="result-verification"><legend>全体確認</legend><label>確認状態<select value={draft.verificationState} onChange={(event)=>set('verificationState',event.target.value)}>{verificationStates.map((state)=><option key={state}>{state}</option>)}</select></label><TextArea label="確認概要" value={draft.verificationSummary} maxLength={4000} onChange={(next)=>set('verificationSummary',next)}/><label>確認者<input maxLength={200} value={draft.verifiedBy??''} onChange={(event)=>set('verifiedBy',event.target.value||undefined)}/></label><label>確認日時<input type="datetime-local" value={draft.verifiedAt?.slice(0,16)??''} onChange={(event)=>set('verifiedAt',event.target.value?new Date(event.target.value).toISOString():undefined)}/></label></fieldset>
   <section id="result-next"><TextArea label="次工程" value={draft.nextStep} maxLength={4000} onChange={(next)=>set('nextStep',next)}/><TextArea label="完了条件" value={draft.completionCriteria} maxLength={4000} onChange={(next)=>set('completionCriteria',next)}/><TextArea label="検証メモ" value={draft.verificationMemo} maxLength={10000} onChange={(next)=>set('verificationMemo',next)}/></section>
   </fieldset><div className="result-save-bar" aria-label="成果シート保存"><span>{isSaving?'保存中です':localDirty?'未保存の変更があります':saved?'保存済み':'変更は保存済みです'}</span><button ref={saveButton} className="button primary" disabled={isSaving}><Save size={17}/>{isSaving?'保存中…':'保存'}</button>{localDirty&&<button className="button ghost" type="button" disabled={isSaving} onClick={discard}><RotateCcw size={17}/>変更を破棄</button>}</div>
  </form>}
 </section>
}

function ResultView({milestone,draft}:{milestone:boolean;draft:Result}){return <div className="result-sheet-view">{milestone&&<ChecklistView items={draft.checklistItems??[]}/>}<ResultSection id="result-body" title="結果" text={draft.resultBody}/><DeliverableView items={draft.deliverables}/><ResultSection id="result-verification" title="全体確認" text={draft.verificationSummary}/><ResultSection id="result-next" title="次工程" text={draft.nextStep}/><ResultSection title="完了条件" text={draft.completionCriteria}/><ResultSection title="検証メモ" text={draft.verificationMemo}/><section><h3>同期・監査</h3><p>更新: {draft.updatedAt}{draft.verifiedBy&&` / 確認者: ${draft.verifiedBy}`}{draft.verifiedAt&&` / 確認日時: ${draft.verifiedAt}`}</p></section></div>}
function ChecklistProgress({items}:{items:ChecklistItem[]}){const progress=checklistProgress(items),value=progress.total?Math.round(progress.completed/progress.total*100):0;return <div className="checklist-progress"><b>進捗 {progress.completed}/{progress.total}</b>{progress.total>0&&<div role="progressbar" aria-label="チェックリスト進捗" aria-valuemin={0} aria-valuemax={progress.total} aria-valuenow={progress.completed} aria-valuetext={`${progress.completed}/${progress.total} 完了`}><i style={{width:`${value}%`}}/></div>}<span>{progress.total===0?'チェック項目なし':progress.completed===progress.total?'全項目完了':'未完了項目あり'}</span></div>}
function ChecklistEditor({item,index,count,update,updateStatus,move,remove,error}:{item:ChecklistItem;index:number;count:number;update:(index:number,field:keyof ChecklistItem,next:string)=>void;updateStatus:(index:number,next:ChecklistItem['status'])=>void;move:(index:number,delta:number)=>void;remove:()=>void;error:(id:string)=>FormError|undefined}){const f=(suffix:string)=>`checklist-${index}-${suffix}`,a=(id:string)=>error(id)?{'aria-invalid':true as const,'aria-describedby':`${id}-error`}:{},inline=(id:string)=>error(id)&&<small id={`${id}-error`} className="field-error">{error(id)?.message}</small>;return <div className="checklist-editor"><div className="checklist-editor-head"><div><b>項目 {index+1}</b><span>{item.title||'実施項目を入力してください'}</span></div><label htmlFor={f('status')}>状態<select id={f('status')} value={item.status} onChange={(event)=>updateStatus(index,event.target.value as ChecklistItem['status'])}>{checklistStatuses.map((status)=><option key={status}>{status}</option>)}</select></label></div><label htmlFor={f('title')}>実施項目<input id={f('title')} maxLength={500} value={item.title} {...a(f('title'))} onChange={(event)=>update(index,'title',event.target.value)}/>{inline(f('title'))}</label><label htmlFor={f('acceptance')}>受入条件<textarea id={f('acceptance')} maxLength={1000} value={item.acceptanceCriteria} {...a(f('acceptance'))} onChange={(event)=>update(index,'acceptanceCriteria',event.target.value)}/>{inline(f('acceptance'))}</label><label htmlFor={f('assignee')}>実施担当<input id={f('assignee')} maxLength={200} value={item.assignee} onChange={(event)=>update(index,'assignee',event.target.value)}/></label><label htmlFor={f('reviewer')}>確認者<input id={f('reviewer')} maxLength={200} value={item.reviewer} {...a(f('reviewer'))} onChange={(event)=>update(index,'reviewer',event.target.value)}/>{inline(f('reviewer'))}</label><label htmlFor={f('reviewed-at')}>確認日時<input id={f('reviewed-at')} type="datetime-local" value={item.reviewedAt.slice(0,16)} {...a(f('reviewed-at'))} onChange={(event)=>update(index,'reviewedAt',event.target.value?new Date(event.target.value).toISOString():'')}/>{inline(f('reviewed-at'))}</label><label htmlFor={f('evidence')}>証跡メモ<textarea id={f('evidence')} maxLength={2000} value={item.evidenceMemo} {...a(f('evidence'))} onChange={(event)=>update(index,'evidenceMemo',event.target.value)}/>{inline(f('evidence'))}</label><label htmlFor={f('hold')}>保留理由<textarea id={f('hold')} maxLength={1000} value={item.holdReason} {...a(f('hold'))} onChange={(event)=>update(index,'holdReason',event.target.value)}/>{inline(f('hold'))}</label><div className="deliverable-actions"><button type="button" aria-label={`項目${index+1}を上へ`} onClick={()=>move(index,-1)} disabled={!index}><ArrowUp/></button><button type="button" aria-label={`項目${index+1}を下へ`} onClick={()=>move(index,1)} disabled={index===count-1}><ArrowDown/></button><button type="button" aria-label={`項目${index+1}を削除`} onClick={remove}><Trash2/></button></div></div>}
function ChecklistView({items}:{items:ChecklistItem[]}){return <section id="result-checklist"><h3>チェックリスト</h3><ChecklistProgress items={items}/>{items.length?<ol className="checklist-view">{items.map((item)=><li key={item.id}><div><b>{item.title}</b><span>状態: {item.status}</span></div><dl><div><dt>受入条件</dt><dd>{item.acceptanceCriteria}</dd></div><div><dt>実施担当</dt><dd>{item.assignee||'未入力'}</dd></div><div><dt>確認</dt><dd>{item.reviewer||'未入力'}{item.reviewedAt&&` / ${item.reviewedAt}`}</dd></div><div><dt>証跡メモ</dt><dd>{item.evidenceMemo||'未入力'}</dd></div>{item.status==='保留'&&<div><dt>保留理由</dt><dd>{item.holdReason}</dd></div>}</dl></li>)}</ol>:<p className="empty-inline">チェック項目は未登録です。</p>}</section>}
function DeliverableView({items}:{items:Deliverable[]}){return <section id="result-deliverables"><h3>成果物 ({items.length})</h3>{items.length?<ul className="deliverable-list">{items.map((item)=><li key={item.id}><div><b>{item.title}</b><span>{item.type} / {item.accessState}</span></div><a href={item.href} target="_blank" rel="noopener noreferrer">URLを開く <ExternalLink size={15}/></a>{item.note&&<p>{item.note}</p>}</li>)}</ul>:<p className="empty-inline">成果物は未登録です。</p>}</section>}
function DeliverableEditor({draft,update,move,add,set}:{draft:Result;update:(index:number,field:keyof Deliverable,next:string)=>void;move:(index:number,delta:number)=>void;add:()=>void;set:(field:keyof Result,next:unknown)=>void}){return <fieldset><legend>成果物</legend>{draft.deliverables.map((item,index)=><div className="deliverable-editor" key={item.id}><label>タイトル<input required maxLength={200} value={item.title} onChange={(event)=>update(index,'title',event.target.value)}/></label><label>種別<select value={item.type} onChange={(event)=>update(index,'type',event.target.value)}>{deliverableTypes.map((type)=><option key={type}>{type}</option>)}</select></label><label>HTTPS URL<input required type="url" maxLength={2048} value={item.href} onChange={(event)=>update(index,'href',event.target.value)}/></label><label>アクセス<select value={item.accessState} onChange={(event)=>update(index,'accessState',event.target.value)}>{deliverableAccessStates.map((state)=><option key={state}>{state}</option>)}</select></label><label>メモ<textarea maxLength={1000} value={item.note??''} onChange={(event)=>update(index,'note',event.target.value)}/></label><div className="deliverable-actions"><button type="button" aria-label={`${item.title||'成果物'}を上へ`} onClick={()=>move(index,-1)} disabled={!index}><ArrowUp/></button><button type="button" aria-label={`${item.title||'成果物'}を下へ`} onClick={()=>move(index,1)} disabled={index===draft.deliverables.length-1}><ArrowDown/></button><button type="button" aria-label={`${item.title||'成果物'}を削除`} onClick={()=>set('deliverables',draft.deliverables.filter((_,itemIndex)=>itemIndex!==index))}><Trash2/></button></div></div>)}<button className="button ghost" type="button" onClick={add} disabled={draft.deliverables.length>=32}><Plus size={17}/>成果物を追加</button></fieldset>}
function TextArea({label,value,maxLength,onChange}:{label:string;value:string;maxLength:number;onChange:(value:string)=>void}){return <label>{label}<textarea rows={5} maxLength={maxLength} value={value} onChange={(event)=>onChange(event.target.value)}/><small>{value.length} / {maxLength}</small></label>}
function ResultSection({id,title,text}:{id?:string;title:string;text:string}){return <section id={id}><h3>{title}</h3><p className="result-copy">{text||'未入力'}</p></section>}
