import { fireEvent, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it, vi } from 'vitest'
import { initialTasks } from '../data'
import { TaskResultSheet } from './TaskResultSheet'
import type { Task, TaskResultSheet as Result } from '../types'

const milestone=():{task:Task;source:Task}=>{const source=initialTasks[0];return{source,task:{...source,id:'AUTO-2026-W33-01',title:'P0-01 マイルストーンチェックリスト作成',status:'完了',sourceRefs:[],provenance:{ruleId:'milestone-checklist',sourceTaskId:'P0-01',dependencyIds:[]},createdBy:'esports_progress_control',createdByDepartment:'esports_progress_control'}}}

describe('TaskResultSheet UI',()=>{
 it('creates a logical empty sheet, keeps input after failure, and restores save focus',async()=>{const save=vi.fn().mockResolvedValue(false);render(<TaskResultSheet task={initialTasks[0]} onBack={vi.fn()} onSave={save}/>);const result=screen.getByRole('textbox',{name:/^結果/});await userEvent.type(result,'試験結果');const saveButton=screen.getByRole('button',{name:'保存'});await userEvent.click(saveButton);expect(await screen.findByRole('alert')).toHaveTextContent('入力内容は保持');expect(result).toHaveValue('試験結果');expect(save.mock.calls[0][0].id).toBe(`task-result:${initialTasks[0].id}`);await vi.waitFor(()=>expect(saveButton).toHaveFocus())})
 it('renders external links safely and viewer controls as read-only',()=>{render(<TaskResultSheet task={initialTasks[0]} readOnly value={{id:`task-result:${initialTasks[0].id}`,taskId:initialTasks[0].id,resultBody:'ok',verificationState:'確認不能',verificationSummary:'-',deliverables:[{id:'d1',title:'sheet',type:'url',href:'https://example.com',accessState:'権限不足'}],nextStep:'-',completionCriteria:'-',verificationMemo:'-',updatedAt:'2026-08-17T00:00:00.000Z'}} onBack={vi.fn()} onSave={vi.fn()}/>);const link=screen.getByRole('link',{name:/URLを開く/});expect(link).toHaveAttribute('target','_blank');expect(link).toHaveAttribute('rel','noopener noreferrer');expect(screen.queryByRole('button',{name:'編集'})).not.toBeInTheDocument();expect(screen.getByRole('status')).toHaveTextContent('viewer')})
 it('reports dirty edits, suppresses a duplicate save, and restores focus after success',async()=>{let resolve:(value:boolean)=>void=()=>{};const save=vi.fn(()=>new Promise<boolean>((done)=>{resolve=done})),dirty=vi.fn();render(<TaskResultSheet task={initialTasks[0]} onDirty={dirty} onBack={vi.fn()} onSave={save}/>);await userEvent.type(screen.getByRole('textbox',{name:/^結果/}),'x');const saveButton=screen.getByRole('button',{name:'保存'}),form=saveButton.closest('form')!;fireEvent.submit(form);fireEvent.submit(form);expect(save).toHaveBeenCalledTimes(1);expect(dirty).toHaveBeenCalledWith(true);resolve(true);expect(await screen.findByText('成果シートを保存しました。引き続き直接編集できます。')).toBeVisible();await vi.waitFor(()=>expect(saveButton).toHaveFocus())})
 it('disables every result field while a delayed save is pending, preserves its snapshot and restores focus',async()=>{let finish:(ok:boolean)=>void=()=>undefined;const save=vi.fn<(value:Result)=>Promise<boolean>>(()=>new Promise<boolean>((resolve)=>{finish=resolve})),user=userEvent.setup();render(<TaskResultSheet task={initialTasks[0]} onBack={vi.fn()} onSave={save}/>);const result=screen.getByRole('textbox',{name:/^結果/}),form=result.closest('form')!;await user.type(result,'送信snapshot');const saveButton=screen.getByRole('button',{name:'保存'});await user.click(saveButton);await vi.waitFor(()=>expect(form).toHaveAttribute('aria-busy','true'));expect(result).toBeDisabled();expect(screen.getByLabelText('確認状態')).toBeDisabled();await user.type(result,'追加入力');expect(result).toHaveValue('送信snapshot');expect(save.mock.calls[0][0].resultBody).toBe('送信snapshot');finish(true);expect(await screen.findByText('成果シートを保存しました。引き続き直接編集できます。')).toBeVisible();expect(result).toBeEnabled();expect(result).toHaveValue('送信snapshot');await vi.waitFor(()=>expect(saveButton).toHaveFocus())})
 it('uses a milestone template, supports add/move/delete, progress and saves without completing tasks',async()=>{const {task,source}=milestone(),save=vi.fn().mockResolvedValue(true);render(<TaskResultSheet task={task} sourceTask={source} onBack={vi.fn()} onSave={save}/>);expect(screen.getAllByText(/YUKISHIROさんへ開催時期変更/).length).toBeGreaterThan(0);await userEvent.click(screen.getByRole('button',{name:'テンプレートを使用'}));expect(screen.getByRole('progressbar')).toHaveAttribute('aria-valuetext','0/3 完了');await userEvent.click(screen.getByRole('button',{name:'項目を追加'}));expect(screen.getAllByText(/^項目 \d$/)).toHaveLength(4);await userEvent.click(screen.getByRole('button',{name:'項目4を上へ'}));await userEvent.click(screen.getByRole('button',{name:'項目3を削除'}));expect(screen.getAllByText(/^項目 \d$/)).toHaveLength(3);await userEvent.click(screen.getByRole('button',{name:'保存'}));expect(save).toHaveBeenCalledWith(expect.objectContaining({taskId:task.id,checklistItems:expect.any(Array)}));expect(task.status).toBe('完了')})
 it('keeps workflow, navigation and editor DOM in the same section order',()=>{const {task,source}=milestone();render(<TaskResultSheet task={task} sourceTask={source} onBack={vi.fn()} onSave={vi.fn()}/>);expect(screen.getByLabelText('成果シートの流れ')).toHaveTextContent('チェックリスト→結果→成果物→全体確認→次工程');expect([...document.querySelectorAll<HTMLElement>('.result-edit-fields > [id]')].map((element)=>element.id)).toEqual(['result-checklist','result-body','result-deliverables','result-verification','result-next']);expect([...screen.getByRole('navigation',{name:'成果シート内メニュー'}).querySelectorAll('a')].map((link)=>link.getAttribute('href'))).toEqual(['#result-checklist','#result-body','#result-deliverables','#result-verification','#result-next'])})
 it('keeps completion and hold states unconfirmed until evidence and a hold reason exist',async()=>{const {task,source}=milestone(),save=vi.fn();render(<TaskResultSheet task={task} sourceTask={source} onBack={vi.fn()} onSave={save}/>);await userEvent.click(screen.getByRole('button',{name:'テンプレートを使用'}));const states=screen.getAllByLabelText('状態');await userEvent.selectOptions(states[0],'完了');await userEvent.selectOptions(states[1],'保留');const alert=screen.getByRole('alert');expect(alert).toHaveTextContent('確認者');expect(alert).toHaveTextContent('証跡メモ');expect(alert).toHaveTextContent('保留理由');expect(states[0]).toHaveValue('未着手');expect(states[1]).toHaveValue('未着手');expect(document.getElementById('checklist-0-reviewer')).toHaveAttribute('aria-describedby','checklist-0-reviewer-error');expect(save).not.toHaveBeenCalled()})
 it('renders a saved checklist read-only with textual progress',()=>{const {task}=milestone();render(<TaskResultSheet task={task} readOnly value={{id:`task-result:${task.id}`,taskId:task.id,resultBody:'',verificationState:'未確認',verificationSummary:'',deliverables:[],checklistItems:[{id:'c1',title:'item',status:'完了',acceptanceCriteria:'criteria',assignee:'owner',reviewer:'reviewer',reviewedAt:'2026-08-17T00:00:00.000Z',evidenceMemo:'evidence',holdReason:''}],nextStep:'',completionCriteria:'',verificationMemo:'',updatedAt:'2026-08-17T00:00:00.000Z'}} onBack={vi.fn()} onSave={vi.fn()}/>);expect(screen.getByRole('progressbar')).toHaveAttribute('aria-valuetext','1/1 完了');expect(screen.getByText('全項目完了')).toBeVisible();expect(screen.queryByRole('button',{name:'編集'})).not.toBeInTheDocument()})
 it('omits the progressbar for an empty saved checklist',()=>{const {task}=milestone();render(<TaskResultSheet task={task} value={{id:`task-result:${task.id}`,taskId:task.id,resultBody:'',verificationState:'未確認',verificationSummary:'',deliverables:[],checklistItems:[],nextStep:'',completionCriteria:'',verificationMemo:'',updatedAt:'2026-08-17T00:00:00.000Z'}} onBack={vi.fn()} onSave={vi.fn()}/>);expect(screen.queryByRole('progressbar')).not.toBeInTheDocument();expect(screen.getByText('チェック項目なし')).toBeVisible()})
 it('keeps an unregistered milestone sheet non-editable for viewers',()=>{const {task,source}=milestone();render(<TaskResultSheet task={task} sourceTask={source} readOnly onBack={vi.fn()} onSave={vi.fn()}/>);expect(screen.getByRole('status')).toHaveTextContent('viewer');expect(screen.getByText('チェック項目は未登録です。')).toBeVisible();expect(screen.queryByRole('button',{name:'テンプレートを使用'})).not.toBeInTheDocument()})
})
