import { fireEvent, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it, vi } from 'vitest'
import { initialTasks } from '../data'
import { TaskResultSheet } from './TaskResultSheet'
import type { Task } from '../types'

const milestone=():{task:Task;source:Task}=>{const source=initialTasks[0];return{source,task:{...source,id:'AUTO-2026-W33-01',title:'P0-01 マイルストーンチェックリスト作成',status:'完了',sourceRefs:[],provenance:{ruleId:'milestone-checklist',sourceTaskId:'P0-01',dependencyIds:[]},createdBy:'esports_progress_control',createdByDepartment:'esports_progress_control'}}}

describe('TaskResultSheet UI',()=>{
 it('creates a logical empty sheet and keeps input after save failure',async()=>{const save=vi.fn().mockResolvedValue(false);render(<TaskResultSheet task={initialTasks[0]} onBack={vi.fn()} onSave={save}/>);const result=screen.getByRole('textbox',{name:/^結果/});await userEvent.type(result,'試験結果');await userEvent.click(screen.getByRole('button',{name:'保存'}));expect(await screen.findByRole('alert')).toHaveTextContent('入力内容は保持');expect(result).toHaveValue('試験結果');expect(save.mock.calls[0][0].id).toBe(`task-result:${initialTasks[0].id}`)})
 it('renders external links safely and viewer controls as read-only',()=>{render(<TaskResultSheet task={initialTasks[0]} readOnly value={{id:`task-result:${initialTasks[0].id}`,taskId:initialTasks[0].id,resultBody:'ok',verificationState:'確認不能',verificationSummary:'-',deliverables:[{id:'d1',title:'sheet',type:'url',href:'https://example.com',accessState:'権限不足'}],nextStep:'-',completionCriteria:'-',verificationMemo:'-',updatedAt:'2026-08-17T00:00:00.000Z'}} onBack={vi.fn()} onSave={vi.fn()}/>);const link=screen.getByRole('link',{name:/URLを開く/});expect(link).toHaveAttribute('target','_blank');expect(link).toHaveAttribute('rel','noopener noreferrer');expect(screen.queryByRole('button',{name:'編集'})).not.toBeInTheDocument();expect(screen.getByRole('status')).toHaveTextContent('viewer')})
 it('reports dirty edits and suppresses a same-tick duplicate save',async()=>{let resolve:(value:boolean)=>void=()=>{};const save=vi.fn(()=>new Promise<boolean>((done)=>{resolve=done})),dirty=vi.fn();render(<TaskResultSheet task={initialTasks[0]} onDirty={dirty} onBack={vi.fn()} onSave={save}/>);await userEvent.type(screen.getByRole('textbox',{name:/^結果/}),'x');const form=screen.getByRole('button',{name:'保存'}).closest('form')!;fireEvent.submit(form);fireEvent.submit(form);expect(save).toHaveBeenCalledTimes(1);expect(dirty).toHaveBeenCalledWith(true);resolve(true);expect(await screen.findByRole('status')).toHaveTextContent('保存しました')})
 it('uses a milestone template, supports add/move/delete, progress and saves without completing tasks',async()=>{const {task,source}=milestone(),save=vi.fn().mockResolvedValue(true);render(<TaskResultSheet task={task} sourceTask={source} onBack={vi.fn()} onSave={save}/>);expect(screen.getAllByText(/YUKISHIROさんへ開催時期変更/).length).toBeGreaterThan(0);await userEvent.click(screen.getByRole('button',{name:'テンプレートを使用'}));expect(screen.getByRole('progressbar')).toHaveAttribute('aria-valuetext','0/3 完了');await userEvent.click(screen.getByRole('button',{name:'項目を追加'}));expect(screen.getAllByText(/^項目 \d$/)).toHaveLength(4);await userEvent.click(screen.getByRole('button',{name:'項目4を上へ'}));await userEvent.click(screen.getByRole('button',{name:'項目3を削除'}));expect(screen.getAllByText(/^項目 \d$/)).toHaveLength(3);await userEvent.click(screen.getByRole('button',{name:'保存'}));expect(save).toHaveBeenCalledWith(expect.objectContaining({taskId:task.id,checklistItems:expect.any(Array)}));expect(task.status).toBe('完了')})
 it('requires completion evidence and hold reasons with linked inline errors',async()=>{const {task,source}=milestone(),save=vi.fn();render(<TaskResultSheet task={task} sourceTask={source} onBack={vi.fn()} onSave={save}/>);await userEvent.click(screen.getByRole('button',{name:'テンプレートを使用'}));await userEvent.selectOptions(screen.getAllByLabelText('状態')[0],'完了');await userEvent.selectOptions(screen.getAllByLabelText('状態')[1],'保留');await userEvent.click(screen.getByRole('button',{name:'保存'}));const alert=screen.getByRole('alert');expect(alert).toHaveTextContent('確認者');expect(alert).toHaveTextContent('証跡メモ');expect(alert).toHaveTextContent('保留理由');expect(document.getElementById('checklist-0-reviewer')).toHaveAttribute('aria-describedby','checklist-0-reviewer-error');expect(save).not.toHaveBeenCalled()})
 it('renders a saved checklist read-only with textual progress',()=>{const {task}=milestone();render(<TaskResultSheet task={task} readOnly value={{id:`task-result:${task.id}`,taskId:task.id,resultBody:'',verificationState:'未確認',verificationSummary:'',deliverables:[],checklistItems:[{id:'c1',title:'item',status:'完了',acceptanceCriteria:'criteria',assignee:'owner',reviewer:'reviewer',reviewedAt:'2026-08-17T00:00:00.000Z',evidenceMemo:'evidence',holdReason:''}],nextStep:'',completionCriteria:'',verificationMemo:'',updatedAt:'2026-08-17T00:00:00.000Z'}} onBack={vi.fn()} onSave={vi.fn()}/>);expect(screen.getByRole('progressbar')).toHaveAttribute('aria-valuetext','1/1 完了');expect(screen.getByText('全項目完了')).toBeVisible();expect(screen.queryByRole('button',{name:'編集'})).not.toBeInTheDocument()})
 it('omits the progressbar for an empty saved checklist',()=>{const {task}=milestone();render(<TaskResultSheet task={task} value={{id:`task-result:${task.id}`,taskId:task.id,resultBody:'',verificationState:'未確認',verificationSummary:'',deliverables:[],checklistItems:[],nextStep:'',completionCriteria:'',verificationMemo:'',updatedAt:'2026-08-17T00:00:00.000Z'}} onBack={vi.fn()} onSave={vi.fn()}/>);expect(screen.queryByRole('progressbar')).not.toBeInTheDocument();expect(screen.getByText('チェック項目なし')).toBeVisible()})
 it('keeps an unregistered milestone sheet non-editable for viewers',()=>{const {task,source}=milestone();render(<TaskResultSheet task={task} sourceTask={source} readOnly onBack={vi.fn()} onSave={vi.fn()}/>);expect(screen.getByRole('status')).toHaveTextContent('viewer');expect(screen.getByText('チェック項目は未登録です。')).toBeVisible();expect(screen.queryByRole('button',{name:'テンプレートを使用'})).not.toBeInTheDocument()})
})
