import { fireEvent, render, screen, within } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import { initialTasks } from '../data'
import { TaskBoard, deadlineState } from './TaskBoard'

const props=()=>({tasks:initialTasks,view:'list' as const,search:'',department:'',status:'',phase:'0',person:'',dueView:'' as const,groupByTeam:false,setSearch:vi.fn(),setDepartment:vi.fn(),setStatus:vi.fn(),setPhase:vi.fn(),setPerson:vi.fn(),setDueView:vi.fn(),onAdd:vi.fn(),onEdit:vi.fn(),onDelete:vi.fn(),onStatus:vi.fn()})
describe('TaskBoard UI',()=>{
  it('defaults to a phase-filtered view and supports all phase',()=>{const value=props();render(<TaskBoard {...value}/>);expect(screen.getByText('9 / 73 件を表示')).toBeVisible();fireEvent.click(screen.getByRole('tab',{name:/全体/}));expect(value.setPhase).toHaveBeenCalledWith('')})
  it('supports phase tab arrow, Home and End keyboard navigation',()=>{const value=props();render(<TaskBoard {...value}/>);const phase0=screen.getByRole('tab',{name:/Phase 0/});fireEvent.keyDown(phase0,{key:'ArrowRight'});expect(value.setPhase).toHaveBeenCalledWith('1');fireEvent.keyDown(phase0,{key:'End'});expect(value.setPhase).toHaveBeenCalledWith('6')})
  it('uses stable team IDs and person filters with assignee-only badges',()=>{const value=props();render(<TaskBoard {...value}/>);fireEvent.change(screen.getByLabelText('チームで絞り込み'),{target:{value:'administration'}});expect(value.setDepartment).toHaveBeenCalledWith('administration');const button=within(screen.getByLabelText('担当者フィルタ')).getByRole('button',{name:/スン/});expect(button).toHaveTextContent('3 高 / 6件');fireEvent.click(button);expect(value.setPerson).toHaveBeenCalledWith('スン')})
  it('filters only assignee personKeys and never mixes in the owner',()=>{const value=props();render(<TaskBoard {...value} search="P0-01" person="ロブ"/>);expect(screen.getByText('該当するタスクがありません')).toBeVisible();expect(initialTasks.find((task)=>task.id==='P5-01')?.personKeys).toEqual(['鈴木','ユウタ','ウメノ','ロブ','浜名','ウニュ','原田','スン'])})
  it('separates owner and assignees and exposes blocker state',()=>{const value=props();render(<TaskBoard {...value} phase="3" search="P3-05"/>);const card=screen.getByText(/告知用クリエイティブ制作/).closest('article')!;expect(within(card).getByText(/責任者/)).toHaveTextContent('鈴木');expect(within(card).getByText(/担当/)).toHaveTextContent('スン');expect(within(card).getByText(/ブロック中/)).toHaveTextContent('P0-07');expect(within(card).getByText(/解除条件/)).toBeVisible()})
  it('shows old overdue and revised deadline independently for P0-01',()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-08-14T12:00:00+09:00'));try{expect(deadlineState(initialTasks[0])).toMatchObject({kind:'overdue',label:'旧期限超過 / 改訂期限まで4日',days:4});const value=props();render(<TaskBoard {...value} search="P0-01" dueView="soon"/>);expect(screen.getByText('即時（〜8/18）')).toBeVisible();expect(screen.getByText('旧期限超過 / 改訂期限まで4日')).toBeVisible()}finally{vi.useRealTimers()}})
  it('provides explicit status labels and 44px-ready controls',()=>{const value=props();render(<TaskBoard {...value} phase="5"/>);expect(screen.getAllByLabelText(/ステータス/)).toHaveLength(8);expect(document.querySelectorAll('.phase5-check').length).toBe(8)})
  it('preserves raw assignee annotations and disables deletion of authoritative tasks',()=>{const value=props();render(<TaskBoard {...value} phase="3" search="P3-05"/>);expect(screen.getByText(/担当 鈴木、ウメノ、（スン※契約後）/)).toBeVisible();expect(screen.getByRole('button',{name:/告知用クリエイティブ制作.*削除/})).toBeDisabled()})
  it('labels milestone navigation as checklist with textual progress',()=>{const value=props(),task={...initialTasks[0],id:'AUTO-2026-W33-01',title:'milestone',sourceRefs:[],provenance:{ruleId:'milestone-checklist',sourceTaskId:'P0-01',dependencyIds:[]}},item={id:'c1',title:'item',status:'完了' as const,acceptanceCriteria:'criteria',assignee:'owner',reviewer:'reviewer',reviewedAt:'2026-08-17T00:00:00.000Z',evidenceMemo:'evidence',holdReason:''};render(<TaskBoard {...value} tasks={[task]} taskResults={[{id:'task-result:AUTO-2026-W33-01',taskId:task.id,resultBody:'',verificationState:'未確認',verificationSummary:'',deliverables:[],checklistItems:[item,{...item,id:'c2',status:'未着手'}],nextStep:'',completionCriteria:'',verificationMemo:'',updatedAt:'2026-08-17T00:00:00.000Z'}]} search="milestone" onResult={vi.fn()}/>);expect(screen.getByRole('button',{name:/チェックリスト 1\/2/})).toBeVisible()})
  it('warns about a legacy invalid completed milestone while allowing correction away from complete',()=>{const value=props(),task={...initialTasks[0],id:'AUTO-2026-W33-01',title:'legacy milestone',status:'完了' as const,sourceRefs:[],provenance:{ruleId:'milestone-checklist',sourceTaskId:'P0-01',dependencyIds:[]}};render(<TaskBoard {...value} tasks={[task]} taskResults={[]} search="legacy milestone"/>);const warning=screen.getByText(/完了状態とチェックリストが不整合/).closest('.milestone-completion-warning')!,select=screen.getByLabelText('legacy milestoneのステータス');expect(warning).toHaveTextContent('構造化チェックリストを1件以上');expect(select).toHaveAttribute('aria-describedby',warning.id);fireEvent.change(select,{target:{value:'進行中'}});expect(value.onStatus).toHaveBeenCalledWith(task.id,'進行中')})
})
