import { fireEvent,render,screen,waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { useState } from 'react'
import { afterEach,describe,expect,it,vi } from 'vitest'
import { generateWorkspaceDraft } from '../workspace'
import { WorkspaceSettingsDialog } from './WorkspaceSettingsDialog'

const draft=()=>generateWorkspaceDraft({organizationName:'商品開発部',slug:'product-team',projectName:'秋の新商品',purpose:'顧客の声を反映した新商品を安全に発売するための十分に長い計画です。',knownTasks:'顧客調査\n試作品レビュー\n発売準備\n公開\n改善',phaseCount:3,taskTerm:'作業',phaseTerm:'段階',departmentTerm:'担当'},'2026-08-26T00:00:00.000Z')
afterEach(()=>vi.restoreAllMocks())

describe('WorkspaceSettingsDialog',()=>{
  it('traps focus from the heading and outside in both directions, confirms dirty Escape, and restores the opener',async()=>{const source=draft();function Harness(){const [open,setOpen]=useState(false);return <><button onClick={()=>setOpen(true)}>設定を開く</button>{open&&<WorkspaceSettingsDialog profile={source.profile} config={source.config} busy={false} onSave={vi.fn()} onClose={()=>setOpen(false)}/>}</>}render(<Harness/>);const opener=screen.getByRole('button',{name:'設定を開く'});opener.focus();fireEvent.click(opener);expect(screen.getByRole('heading',{name:'組織設定を編集'})).toHaveFocus();const close=screen.getByRole('button',{name:'組織設定を閉じる'}),save=screen.getByRole('button',{name:'組織設定を保存'});await userEvent.keyboard('{Shift>}{Tab}{/Shift}');expect(save).toHaveFocus();opener.focus();await userEvent.keyboard('{Tab}');expect(close).toHaveFocus();opener.focus();await userEvent.keyboard('{Shift>}{Tab}{/Shift}');expect(save).toHaveFocus();fireEvent.change(screen.getByLabelText('プロジェクト名'),{target:{value:'変更中'}});const confirm=vi.spyOn(window,'confirm').mockReturnValueOnce(false).mockReturnValueOnce(true);await userEvent.keyboard('{Escape}');expect(screen.getByRole('dialog')).toBeVisible();expect(screen.getByRole('status')).toHaveTextContent('未保存の変更を保持');await userEvent.keyboard('{Escape}');await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());expect(confirm).toHaveBeenCalledTimes(2);expect(opener).toHaveFocus()})
  it('focuses an accessible validation summary and associates invalid fields',async()=>{const source=draft();render(<WorkspaceSettingsDialog profile={source.profile} config={source.config} busy={false} onSave={vi.fn()} onClose={vi.fn()}/>);const purpose=screen.getByLabelText('目的');fireEvent.change(purpose,{target:{value:'短い'}});fireEvent.click(screen.getByRole('button',{name:'組織設定を保存'}));const alert=await screen.findByRole('alert');await waitFor(()=>expect(alert).toHaveFocus());expect(purpose).toHaveAttribute('aria-invalid','true');expect(purpose).toHaveAccessibleDescription('目的は20〜4000文字で入力してください')})
  it('announces why busy close and duplicate saves are blocked',()=>{const source=draft(),save=vi.fn();render(<WorkspaceSettingsDialog profile={source.profile} config={source.config} busy onSave={save} onClose={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'組織設定を閉じる'}));expect(screen.getByRole('status')).toHaveTextContent('保存中は組織設定を閉じられません');const saveButton=screen.getByRole('button',{name:'保存中…'});fireEvent.click(saveButton);fireEvent.click(saveButton);expect(save).not.toHaveBeenCalled();expect(screen.getByRole('status')).toHaveTextContent('保存処理中です')})
  it.each(['','   ','\u200b'])('rejects a non-visible default owner %#',async(owner)=>{const source=draft(),save=vi.fn();render(<WorkspaceSettingsDialog profile={source.profile} config={source.config} busy={false} onSave={save} onClose={vi.fn()}/>);const input=screen.getAllByLabelText('既定責任者')[0];fireEvent.change(input,{target:{value:owner}});fireEvent.click(screen.getByRole('button',{name:'組織設定を保存'}));expect(save).not.toHaveBeenCalled();expect(await screen.findByRole('alert')).toHaveTextContent('既定責任者は1〜120文字で入力してください');expect(input).toHaveAttribute('aria-invalid','true')})
})
