import { useCallback, useEffect, useLayoutEffect, useRef, useState, type KeyboardEvent } from 'react'
import gsap from 'gsap'
import { Activity, AlertTriangle, BarChart3, CalendarClock, ChevronDown, Columns3, Download, FileUp, List, LogOut, Network, Play, RefreshCw, RotateCcw, Save, ScrollText, ShieldCheck, UsersRound } from 'lucide-react'
import { AuditLog } from './components/AuditLog'
import { ProjectCanvas } from './components/ProjectCanvas'
import { QuestBoard } from './components/QuestBoard'
import { TaskBoard, deadlineState, type DueView } from './components/TaskBoard'
import { TaskModal } from './components/TaskModal'
import { TaskResultSheet } from './components/TaskResultSheet'
import { milestoneStatusTransitionIssues } from './checklistTemplates'
import { currentPhaseFor, initialTasks } from './data'
import { createOperationAuditEntry } from './operationAudit'
import { buildBiweeklyReport } from './report'
import { pruneTaskReferences } from './pruneTask'
import { KEYS, parseImport, readBundle, resetBundle, saveBundle, validateTaskCandidate } from './storage'
import { type ExportBundle, type FlowData, type ReportSnapshot, type Status, type Task, type TaskResultSheet as ResultSheet, type ValidationIssue } from './types'
import { runWeeklyBundle, shouldCatchUp, syncTaskCompletion, weeklySchedule } from './weekly'
import type { OrganizationSummary } from './cloud/contracts'
import { CloudRepositoryError, type LoadedWorkspace, type SupabaseWorkspaceRepository } from './cloud/repository'

type Page='tasks'|'canvas'|'report'|'audit'|'result'
type DirtySource='canvas'|'result'|'modal'|'task'|'kpi'
export type StatusChangeResult={ok:boolean;issues?:string[]}
const nav=[{id:'tasks' as Page,label:'進行表',icon:Columns3},{id:'canvas' as Page,label:'キャンバス',icon:Network},{id:'report' as Page,label:'隔週報告',icon:BarChart3},{id:'audit' as Page,label:'修正ログ',icon:ScrollText}]
const initialResult=readBundle(),now=()=>new Date().toISOString(),meaningful=(value:string)=>value.replace(/[\s\u200B-\u200D\uFEFF]/g,'').length>0
const snapshot=(tasks:Task[]):ReportSnapshot=>({savedAt:now(),statuses:Object.fromEntries(tasks.map((task)=>[task.id,{status:task.status,updatedAt:task.updatedAt}]))})
const authoritativeIds=new Set(initialTasks.map((task)=>task.id))

export interface CloudControls {
  repository:SupabaseWorkspaceRepository
  workspace:LoadedWorkspace
  organizations:OrganizationSummary[]
  selectedOrganizationId:string
  userEmail:string
  onSelectOrganization:(id:string)=>void|Promise<void>
  onConfirmed:(workspace:LoadedWorkspace)=>void
  pendingCandidate:ExportBundle|null
  onPending:(candidate:ExportBundle|null)=>void
  onReload:(force?:boolean)=>void|Promise<void>
  onSignOut:()=>void
  onSessionExpired:()=>void
  onAccessRevoked:()=>void|Promise<void>
  onCanvasDirty?:(dirty:boolean)=>void
}

function ReportMode({tasks,baseline,onBaseline,readOnly=false}:{tasks:Task[];baseline:ReportSnapshot|null;onBaseline:()=>void;readOnly?:boolean}){
  const report=buildBiweeklyReport(tasks,baseline)
  return <section aria-labelledby="report-title"><div className="section-heading"><div><span className="eyebrow">BIWEEKLY REPORT</span><h2 id="report-title">隔週報告モード</h2><p>{baseline?`前回基準から ${report.changed.length}件変化`:'最初に比較基準を保存してください'}</p></div><button className="button primary" disabled={readOnly} onClick={onBaseline}><Save size={16}/>現在を比較基準に保存</button></div><div className="report-grid"><div className="report-summary"><article><b>{report.completed.length}</b><span>完了</span></article><article><b>{report.progressing.length}</b><span>進行中</span></article><article><b>{report.blockedChanged.length}</b><span>保留・ブロック</span></article><article><b>{report.upcoming.length}</b><span>次の2週間</span></article></div><label htmlFor="line-report">LINE貼付用テキスト</label><textarea id="line-report" readOnly value={report.text} rows={18}/><button className="button ghost" onClick={async()=>navigator.clipboard?.writeText(report.text)}>テキストをコピー</button></div></section>
}

export default function App({initialBundle,cloud,onDirtyChange}:{initialBundle?:ExportBundle;cloud?:CloudControls;onDirtyChange?:(dirty:boolean)=>void}={}){
  const source=initialBundle??initialResult.value,readOnly=cloud?.workspace.organization.role==='viewer',notifyCanvasDirty=cloud?.onCanvasDirty,hashResultId=location.hash.startsWith('#task-result/')?decodeURIComponent(location.hash.slice('#task-result/'.length)):''
  const [exportedAt,setExportedAt]=useState(source.exportedAt),[tasks,setTasks]=useState(source.tasks),[taskResults,setTaskResults]=useState(source.taskResults??[]),[flow,setFlow]=useState(source.flow),[audit,setAudit]=useState(source.audit),[kpis,setKpis]=useState(source.kpis),[reportBaseline,setReportBaseline]=useState(source.reportBaseline),[migrationArchive,setMigrationArchive]=useState(source.migrationArchive),[weekly,setWeekly]=useState(source.weekly)
  const [page,setPage]=useState<Page>(source.tasks.some((task)=>task.id===hashResultId)?'result':'tasks'),[taskMode,setTaskMode]=useState<'quest'|'all'>('quest'),[operationsExpanded,setOperationsExpanded]=useState(false),[view,setView]=useState<'kanban'|'list'>('kanban'),[search,setSearch]=useState(''),[department,setDepartment]=useState(''),[status,setStatus]=useState(''),[phase,setPhase]=useState(String(currentPhaseFor(new Date()))),[person,setPerson]=useState(''),[dueView,setDueView]=useState<DueView>(''),[groupByTeam,setGroupByTeam]=useState(false)
  const [modal,setModal]=useState<{open:boolean;task?:Task|null}>({open:false}),[resultTaskId,setResultTaskId]=useState(hashResultId),[notice,setNotice]=useState(''),[error,setError]=useState(initialBundle?'':initialResult.error??''),[busy,setBusy]=useState(false),[dirtyRegistry,setDirtyRegistry]=useState<Set<DirtySource>>(new Set())
  const dirtySourcesRef=useRef<Set<DirtySource>>(new Set()),hasDirty=dirtyRegistry.size>0,setDirtySource=useCallback((source:DirtySource,dirty:boolean)=>{const current=dirtySourcesRef.current;if(current.has(source)===dirty)return;const next=new Set(current);if(dirty)next.add(source);else next.delete(source);dirtySourcesRef.current=next;setDirtyRegistry(next)},[]),setCanvasDirty=useCallback((dirty:boolean)=>setDirtySource('canvas',dirty),[setDirtySource]),setTaskDirty=useCallback((dirty:boolean)=>setDirtySource('task',dirty),[setDirtySource]),setResultDirty=useCallback((dirty:boolean)=>setDirtySource('result',dirty),[setDirtySource]),setModalDirty=useCallback((dirty:boolean)=>setDirtySource('modal',dirty),[setDirtySource])
  const shell=useRef<HTMLDivElement>(null),fileRef=useRef<HTMLInputElement>(null),weeklyLock=useRef(false),startupWeeklyHandled=useRef(false),mutationLock=useRef(false),taskSaveLock=useRef(false),kpiSaveLock=useRef(false),acceptedUrl=useRef(`${location.pathname}${location.search}${location.hash}`),kpiBaseline=useRef(structuredClone(source.kpis))
  useLayoutEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const context=gsap.context(()=>gsap.from('[data-shell-anim]',{y:10,autoAlpha:0,duration:.36,ease:'power2.out',stagger:.035}),shell);return()=>context.revert()},[])
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),2600);return()=>clearTimeout(timer)},[notice])
  useEffect(()=>{const beforeUnload=(event:BeforeUnloadEvent)=>{if(!dirtySourcesRef.current.size)return;event.preventDefault();event.returnValue=''};addEventListener('beforeunload',beforeUnload);return()=>removeEventListener('beforeunload',beforeUnload)},[])
  useEffect(()=>{const onPop=()=>{if(dirtySourcesRef.current.size){history.replaceState(history.state,'',acceptedUrl.current);setError('未保存の変更があるためURL遷移を停止しました。編集中の画面で保存または明示的に破棄してください。');return}const id=location.hash.startsWith('#task-result/')?decodeURIComponent(location.hash.slice('#task-result/'.length)):'';if(id&&tasks.some((task)=>task.id===id)){setResultTaskId(id);setPage('result');acceptedUrl.current=`${location.pathname}${location.search}${location.hash}`}else{const canonical=`${location.pathname}${location.search}`;history.replaceState(history.state,'',canonical);acceptedUrl.current=canonical;setPage('tasks')}};addEventListener('popstate',onPop);addEventListener('hashchange',onPop);return()=>{removeEventListener('popstate',onPop);removeEventListener('hashchange',onPop)}},[tasks])
  useEffect(()=>{notifyCanvasDirty?.(hasDirty);onDirtyChange?.(hasDirty);return()=>{notifyCanvasDirty?.(false);onDirtyChange?.(false)}},[hasDirty,notifyCanvasDirty,onDirtyChange])
  const bundle=(changes:Partial<ExportBundle>={}):ExportBundle=>({schemaVersion:4,exportedAt,tasks,taskResults,flow,audit,kpis,reportBaseline,migrationArchive,weekly,...changes})
  const applyBundle=(next:ExportBundle)=>{setExportedAt(next.exportedAt);setTasks(next.tasks);setTaskResults(next.taskResults??[]);setFlow(next.flow);setAudit(next.audit);setKpis(next.kpis);if(!dirtySourcesRef.current.has('kpi'))kpiBaseline.current=structuredClone(next.kpis);setReportBaseline(next.reportBaseline);setMigrationArchive(next.migrationArchive);setWeekly(next.weekly)}
  useEffect(()=>{if(cloud&&initialBundle&&dirtySourcesRef.current.size===0&&initialBundle.exportedAt!==exportedAt)applyBundle(initialBundle)
  // App drafts are authoritative while dirty; clean cloud read-back may refresh state.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[initialBundle,dirtyRegistry])
  const acquireMutation=()=>{if(mutationLock.current){setError('別の保存処理が完了するまでお待ちください');return false}mutationLock.current=true;setBusy(true);return true},releaseMutation=()=>{mutationLock.current=false;setBusy(false)}
  const commit=async(changes:Partial<ExportBundle>,success:string,operation:'changes'|'weekly'='changes',exact=false,saveSource?:DirtySource,lockHeld=false)=>{const dirty=dirtySourcesRef.current;if(dirty.size&&!(saveSource&&dirty.size===1&&dirty.has(saveSource))){setError('別の編集元に未保存の変更があるため保存を停止しました。編集中の画面で保存または明示的に破棄してください。');return false}const ownsLock=!lockHeld;if(ownsLock&&!acquireMutation())return false;try{await Promise.resolve();const next=exact?changes as ExportBundle:bundle({...changes,exportedAt:now()});if(readOnly){setError('viewerは読み取り専用です');return false}setError('');if(cloud){try{const confirmed=await cloud.repository.save(next,cloud.workspace.organization.id,operation);if(!confirmed.bundle)throw new Error('保存後のbundleを確認できません');applyBundle(confirmed.bundle);cloud.onConfirmed(confirmed);cloud.onPending(null);setNotice(confirmed.cacheWarning?`${success}（${confirmed.cacheWarning}）`:success);return true}catch(cause){cloud.onPending(next);if(cause instanceof CloudRepositoryError&&cause.kind==='session_expired')cloud.onSessionExpired();if(cause instanceof CloudRepositoryError&&cause.kind==='access_revoked')await cloud.onAccessRevoked();setError(cause instanceof Error?cause.message:'クラウド保存に失敗しました');return false}}const result=saveBundle(next);if(!result.ok){setError(result.error??'保存に失敗しました');return false}applyBundle(next);setError('');setNotice(success);return true}finally{if(ownsLock)releaseMutation()}}
  const persistTask=async(task:Task,saveSource:'modal'|'task'):Promise<ValidationIssue[]>=>{if(taskSaveLock.current)return[{path:'save',message:'保存処理中です'}];const previous=tasks.find((item)=>item.id===task.id),completionIssues=milestoneStatusTransitionIssues(previous,task,taskResults.find((item)=>item.taskId===task.id));if(completionIssues.length)return[{path:'status',message:`完了にできません。${completionIssues.slice(0,3).join(' ')}`}];const issues=validateTaskCandidate(task,tasks);if(issues.length)return issues;taskSaveLock.current=true;try{const exists=!!previous,nextTasks=exists?tasks.map((item)=>item.id===task.id?task:item):[...tasks,task],nextAudit=[createOperationAuditEntry(exists?'OP-TASK-UPDATE':'OP-TASK-CREATE','validation',exists?'タスク編集':'タスク追加',`${task.id} ${task.title}`,['src/App.tsx'],exists?'旧値':'未登録','検証済み値'),...audit],ok=await commit({tasks:nextTasks,audit:nextAudit},'タスクを保存しました','changes',false,saveSource);if(ok){setDirtySource(saveSource,false);return[]}return[{path:'save',message:'保存できませんでした。入力内容は保持しています'}]}finally{taskSaveLock.current=false}}
  const saveInlineTask=(task:Task)=>persistTask(task,'task')
  const saveModalTask=async(task:Task)=>{const issues=await persistTask(task,'modal');if(!issues.length)setModal({open:false});return issues}
  const removeTask=(task:Task)=>{if(authoritativeIds.has(task.id)){setError('S4正本タスクは削除できません。状態変更または編集を使用してください。');return}if(!confirm(`「${task.title}」を削除しますか？`))return;const pruned=pruneTaskReferences(bundle(),task.id),nextWeekly={...pruned.weekly,tombstones:task.fingerprint&&!pruned.weekly.tombstones.includes(task.fingerprint)?[...pruned.weekly.tombstones,task.fingerprint]:pruned.weekly.tombstones},nextAudit=[createOperationAuditEntry('OP-TASK-DELETE','validation','タスク削除',`${task.id} ${task.title}`,['src/App.tsx','src/pruneTask.ts'],'custom task登録済み','result/completion/managed node/edge/task参照/dependency/provenanceを原子的にprune'),...audit];commit({tasks:pruned.tasks,taskResults:pruned.taskResults,flow:pruned.flow,weekly:nextWeekly,audit:nextAudit},task.fingerprint?'自動タスクを削除し、同根拠での再生成を停止しました':'カスタムタスクと全参照を削除しました')}
  const navigationBlocked=(allowed?:DirtySource)=>{const dirty=dirtySourcesRef.current;return dirty.size>0&&!(allowed&&dirty.size===1&&dirty.has(allowed))}
  const setAppPage=(next:Page)=>{const allowed=next==='canvas'?'canvas':undefined;if(navigationBlocked(allowed)){setError('未保存の変更があるため画面移動を停止しました。編集中の画面で保存または明示的に破棄してください。');return}setPage(next);if(next!=='result'){const url=`${location.pathname}${location.search}`;history.replaceState(history.state,'',url);acceptedUrl.current=url}}
  const taskModeKey=(event:KeyboardEvent<HTMLButtonElement>)=>{const next=event.key==='ArrowRight'||event.key==='End'?'all':event.key==='ArrowLeft'||event.key==='Home'?'quest':null;if(!next)return;event.preventDefault();if(next==='quest')setOperationsExpanded(false);setTaskMode(next);requestAnimationFrame(()=>document.getElementById(`task-mode-${next}`)?.focus())}
  const openResult=(task:Task)=>{if(navigationBlocked('result')){setError('未保存の変更があるため成果シートへの移動を停止しました。編集中の画面で保存または明示的に破棄してください。');return}setResultTaskId(task.id);setPage('result');const url=`${location.pathname}${location.search}#task-result/${encodeURIComponent(task.id)}`;history.pushState(history.state,'',url);acceptedUrl.current=url}
  const closeResult=(discard=false)=>{if(!discard&&dirtySourcesRef.current.has('result')){setError('成果シートに未保存の変更があります。「変更を破棄して戻る」または保存を選んでください。');return}setDirtySource('result',false);setPage('tasks');const url=`${location.pathname}${location.search}`;history.replaceState(history.state,'',url);acceptedUrl.current=url}
  const closeModal=(discard=false)=>{if(!discard&&dirtySourcesRef.current.has('modal')){setError('タスク編集に未保存の変更があります。「変更を破棄」または保存を選んでください。');return}setDirtySource('modal',false);setModal({open:false})}
  const openModal=(task?:Task)=>{if(navigationBlocked('modal')){setError('別の編集元に未保存の変更があるためタスク編集を開けません。先に保存または明示的に破棄してください。');return}setModal({open:true,task})}
  const saveResult=async(result:ResultSheet)=>{const nextResults=taskResults.some((item)=>item.taskId===result.taskId)?taskResults.map((item)=>item.taskId===result.taskId?result:item):[...taskResults,result],nextAudit=[createOperationAuditEntry('OP-TASK-RESULT','persistence','成果シート保存',`${result.taskId} / チェックリスト${result.checklistItems?.length??0}件 / 成果物${result.deliverables.length}件`,['src/components/TaskResultSheet.tsx'],'保存前成果シート','検証済み成果シート'),...audit];return commit({taskResults:nextResults,audit:nextAudit},'成果シートを保存しました','changes',false,'result')}
  const changeStatus=async(id:string,nextStatus:Status,requestedHoldReason?:string):Promise<StatusChangeResult>=>{const task=tasks.find((item)=>item.id===id);if(!task)return{ok:false};if(task.status===nextStatus)return{ok:true};if(dirtySourcesRef.current.size){setError('未保存のタスク編集があるため状態保存を停止しました。先に保存または破棄してください。');return{ok:false}}const candidate={...task,status:nextStatus},completionIssues=milestoneStatusTransitionIssues(task,candidate,taskResults.find((item)=>item.taskId===id));if(completionIssues.length){setError(`完了にできません。${completionIssues.slice(0,3).join(' ')}`);return{ok:false,issues:completionIssues}}const holdReason=nextStatus==='保留'?(requestedHoldReason??''):task.holdReason;if(nextStatus==='保留'&&!meaningful(holdReason)){setError('保留理由は空白以外で入力してください');return{ok:false,issues:['保留理由を入力してください。']}}const at=now(),changed={...candidate,holdReason,updatedAt:at},nextTasks=tasks.map((item)=>item.id===id?changed:item),synced=syncTaskCompletion(flow,weekly,changed,at),nextAudit=[createOperationAuditEntry('OP-TASK-STATUS','validation','状態変更',`${id}: ${task.status} → ${nextStatus}`,['src/App.tsx'],task.status,nextStatus),...audit],ok=await commit({tasks:nextTasks,flow:synced.flow,weekly:synced.weekly,audit:nextAudit},`${id} を「${nextStatus}」に変更しました`);return{ok}}
  const saveCanvas=async(nextFlow:FlowData)=>{const nextAudit=[createOperationAuditEntry('OP-CANVAS-SAVE','persistence','キャンバス保存',`ノード${nextFlow.nodes.length}件・接続${nextFlow.edges.length}件`,['src/components/ProjectCanvas.tsx'],'保存前canvas','検証済みflow/viewport'),...audit],saved=await commit({flow:nextFlow,audit:nextAudit},'キャンバスを保存しました','changes',false,'canvas');if(saved)setCanvasDirty(false);return saved}
  const saveKpis=async()=>{if(kpiSaveLock.current)return;kpiSaveLock.current=true;try{const nextAudit=[createOperationAuditEntry('OP-KPI-SAVE','persistence','KPI実績更新',kpis.map((kpi)=>`${kpi.id}:${kpi.actual??'未入力'}`).join(', '),['src/App.tsx'],'保存前KPI','finiteかつ0以上のKPI'),...audit],ok=await commit({kpis,audit:nextAudit},'KPI実績を保存しました','changes',false,'kpi');if(ok){kpiBaseline.current=structuredClone(kpis);setDirtySource('kpi',false)}}finally{kpiSaveLock.current=false}}
  const discardKpis=()=>{setKpis(structuredClone(kpiBaseline.current));setDirtySource('kpi',false);setError('');setNotice('KPIの未保存変更を破棄しました')}
  const saveReportBaseline=()=>{const nextBaseline=snapshot(tasks),nextAudit=[createOperationAuditEntry('OP-REPORT-BASELINE','persistence','隔週報告基準更新',nextBaseline.savedAt,['src/App.tsx','src/report.ts'],'旧比較基準','現タスク状態を比較基準化'),...audit];commit({reportBaseline:nextBaseline,audit:nextAudit},'隔週報告の比較基準を保存しました')}
  const reset=async()=>{if(cloud){setError('共有版の全量初期復元は無効です。必要なentityを編集するか、管理者の移行手順を使用してください。');return}if(!acquireMutation())return;try{await Promise.resolve();if(!confirm('ローカルの変更を破棄してS4の初期73件へ復元しますか？'))return;const result=resetBundle();if(!result.ok){setError(result.error??'初期化できません');return}applyBundle(result.value);setPhase(String(currentPhaseFor(new Date())));setNotice('初期73件へ復元しました')}finally{releaseMutation()}}
  const exportJson=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(bundle(),null,2)],{type:'application/json'})),anchor=document.createElement('a');anchor.href=url;anchor.download=`nexus-ops-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url);setNotice('JSONを書き出しました')}
  const recoveryBundle=cloud?.pendingCandidate??null
  const exportRecovery=()=>{if(!recoveryBundle)return;const url=URL.createObjectURL(new Blob([JSON.stringify(recoveryBundle,null,2)],{type:'application/json'})),anchor=document.createElement('a');anchor.href=url;anchor.download=`nexus-ops-unsaved-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url)}
  const importJson=async(file?:File)=>{if(!file||!acquireMutation())return;setError('');try{const result=parseImport(await file.text());if(!result.ok){setError(result.error??'読み込みに失敗しました');return}const imported=result.value,importAudit=createOperationAuditEntry('OP-JSON-IMPORT','validation','JSONインポート',`${imported.tasks.length}件を原子的に読込`,['src/storage.ts','src/App.tsx'],'既存bundle','完全検証済みbundle'),next={...imported,exportedAt:now(),audit:[importAudit,...imported.audit]};if(cloud){await commit(next,'データをクラウドへ読み込みました','changes',false,undefined,true);return}const saved=saveBundle(next);if(!saved.ok){setError(saved.error??'保存できません');return}applyBundle(next);setNotice('データを読み込みました')}catch(cause){setError(cause instanceof Error?cause.message:'JSONを読み込めませんでした')}finally{releaseMutation();if(fileRef.current)fileRef.current.value=''}}
  const executeWeekly=async(trigger:'scheduled'|'catch-up'|'manual',date=new Date(),onlyWhenChanged=false)=>{if(dirtySourcesRef.current.size){setError('未保存の変更があるため、週次更新を停止しました。編集中の画面で保存または明示的に破棄してください。');return}if(weeklyLock.current||!acquireMutation())return;weeklyLock.current=true;try{await Promise.resolve();const current=bundle(),next=runWeeklyBundle(current,date,trigger);if(onlyWhenChanged&&next===current)return;if(cloud){await commit(next,`${next.weekly.lastRun?.runId} を更新しました`,'weekly',true,undefined,true);return}const saved=saveBundle(next);if(!saved.ok){try{localStorage.setItem(KEYS.weeklyFailure,JSON.stringify({at:date.toISOString(),runId:weeklySchedule(date).runId,error:saved.error}))}catch{/* failure evidence is best-effort */}setError(`週次更新を保存できませんでした。変更は反映していません。${saved.error??''}`);return}applyBundle(next);setError('');setNotice(`${next.weekly.lastRun?.runId} を更新しました`)}catch(cause){setError(cause instanceof Error?cause.message:'週次graphを更新できません')}finally{weeklyLock.current=false;releaseMutation()}}
  useEffect(()=>{if(startupWeeklyHandled.current||(!initialBundle&&!initialResult.ok)||readOnly)return;startupWeeklyHandled.current=true;const date=new Date();if(shouldCatchUp(source.weekly,date)){const schedule=weeklySchedule(date),delay=date.getTime()-Date.parse(schedule.scheduledFor);void executeWeekly(delay>=0&&delay<60_000?'scheduled':'catch-up',date)}else void executeWeekly(source.weekly.lastRun?.trigger??'catch-up',date,true)// startup only; state changes must not schedule a second run
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[])
  const complete=tasks.filter((task)=>task.status==='完了').length,progress=Math.round(complete/Math.max(tasks.length,1)*100),highRemaining=tasks.filter((task)=>task.urgency==='高'&&task.status!=='完了').length,overdue=tasks.filter((task)=>deadlineState(task).kind==='overdue').length
  const daysToMarch=Math.max(0,Math.ceil((Date.parse('2027-03-01T00:00:00+09:00')-Date.now())/86_400_000)),schedule=weeklySchedule(new Date()),lastRun=weekly.lastRun,compactOperations=page==='tasks'&&taskMode==='quest'
  return <div className="app" ref={shell}><div className="atmosphere" aria-hidden="true"/><header className="topbar" data-shell-anim><div className="brand"><div className="brand-mark">N</div><div><b>NEXUS OPS</b><span>ESPORTS PROJECT CONTROL</span></div></div><div className="top-actions"><button className="icon-text" onClick={exportJson}><Download size={16}/>書き出し</button><button className="icon-text" disabled={readOnly||busy||hasDirty} onClick={()=>fileRef.current?.click()}><FileUp size={16}/>読み込み</button><label className="sr-only" htmlFor="json-import">JSONファイルを読み込む</label><input id="json-import" className="sr-only" ref={fileRef} type="file" accept="application/json,.json" onChange={(event)=>importJson(event.target.files?.[0])}/><button className="icon-text" disabled={!!cloud||readOnly||busy||hasDirty} onClick={reset}><RotateCcw size={16}/>初期復元</button>{cloud&&<><button className="icon-text" disabled={busy||hasDirty} onClick={()=>void cloud.onReload()}><RefreshCw size={16}/>再読込</button><button className="icon-text" disabled={hasDirty} onClick={cloud.onSignOut}><LogOut size={16}/>ログアウト</button></>}</div></header>
    {cloud&&<section className="cloud-workspace-bar" aria-label="共有接続状態"><label htmlFor="organization-select">organization</label><select id="organization-select" disabled={hasDirty||busy} value={cloud.selectedOrganizationId} onChange={(event)=>void cloud.onSelectOrganization(event.target.value)}>{cloud.organizations.map((organization)=><option key={organization.id} value={organization.id}>{organization.name}</option>)}</select><span className={`role-badge role-${cloud.workspace.organization.role}`}>{cloud.workspace.organization.role}</span><span>{cloud.userEmail}</span><span>state v{cloud.workspace.organization.stateVersion}</span><b>{busy?'クラウドへ保存中…':'15秒ごとに同期'}</b></section>}
    {readOnly&&<div className="read-only-banner" role="status"><ShieldCheck size={17}/><b>viewer / 読み取り専用</b><span>表示・検索・JSON書き出しのみ利用できます。</span></div>}
    {hasDirty&&<div className="conflict-recovery" role="status" data-dirty-sources={[...dirtyRegistry].join(',')}><div><b>未保存の変更があります</b><span>編集元: {[...dirtyRegistry].join(', ')}。編集中の画面で保存または明示的に破棄するまで、画面移動、週次更新、remote再読込、organization切替、JSON読込、別データの保存を停止します。</span></div></div>}
    {recoveryBundle&&<div className="conflict-recovery" role="alert"><div><b>未保存候補を保持しています</b><span>自動同期を停止しています。書き出し、最新版確認、再適用、または破棄を選んでください。</span></div><button className="button ghost" onClick={exportRecovery}><Download size={16}/>未保存JSONを書き出す</button><button className="button ghost" onClick={()=>void cloud?.onReload(true)}><RefreshCw size={16}/>最新版を確認</button><button className="button ghost" disabled={busy} onClick={()=>void commit(recoveryBundle,'未保存候補を再適用しました','changes',true)}><Save size={16}/>再適用</button><button className="button ghost" disabled={busy} onClick={()=>cloud?.onPending(null)}>候補を破棄</button></div>}
    <div className="app-shell"><aside className="sidebar" data-shell-anim><nav aria-label="主要メニュー">{nav.map((item)=>{const Icon=item.icon;return <button key={item.id} disabled={navigationBlocked(item.id==='canvas'?'canvas':undefined)} className={page===item.id?'active':''} onClick={()=>setAppPage(item.id)}><Icon size={19}/><span>{item.label}</span></button>})}</nav><div className="sidebar-note"><ShieldCheck size={18}/><p><b>LOCAL FIRST</b>schema v4一括保存 · S4追跡</p></div></aside><main>
      <details className={`operations-overview ${compactOperations?'is-quest':''}`} open={!compactOperations||operationsExpanded} onToggle={(event)=>{if(compactOperations&&event.currentTarget.open!==operationsExpanded)setOperationsExpanded(event.currentTarget.open)}}><summary><span><Activity size={18}/><b>大会運用サマリー</b></span><small>全{tasks.length}件 · 完了{progress}% · 高緊急残{highRemaining}件 · {lastRun?`週次 ${lastRun.runId}`:'週次未実行'}</small><ChevronDown size={18}/></summary><div className="operations-overview-content">
      <section className="hero compact-hero" data-shell-anim><div><span className="eyebrow">VALORANT NATIONAL STUDENT CUP / 2027.03</span><h1>73タスクで、大会開催までを動かす。</h1><p>全体統括 <b>鈴木</b> · 現在 Phase {currentPhaseFor(new Date())} · 開催日は2027年3月内で未確定</p></div><div className="risk-banner"><AlertTriangle size={18}/><span>Riot Games関連</span><b>公式一次情報を要確認</b></div></section>
      <section className="metric-grid" data-shell-anim aria-label="進捗サマリー"><article><span>全タスク</span><b>{tasks.length}</b><small>Phase 0〜6</small></article><article><span>完了率</span><b>{progress}%</b><div className="progress"><i style={{width:`${progress}%`}}/></div></article><article><span>高緊急 残</span><b>{highRemaining}</b><small>期限超過 {overdue}件</small></article><article><span>3月開始まで</span><b>{daysToMarch}</b><small>日（開催日自体は未確定）</small></article></section>
      <section className="kpi-strip" aria-label="主要KPI">{kpis.map((kpi)=><label key={kpi.id}><span>{kpi.label}</span><b>目標 {kpi.target.toLocaleString()}{kpi.unit}</b><input type="number" min="0" disabled={readOnly||busy||(hasDirty&&!dirtyRegistry.has('kpi'))} aria-label={`${kpi.label}の実績`} placeholder="実績未入力" value={kpi.actual??''} onChange={(event)=>{setDirtySource('kpi',true);setKpis((items)=>items.map((item)=>item.id===kpi.id?{...item,actual:event.target.value===''?null:Number(event.target.value)}:item))}}/></label>)}<button className="button ghost" disabled={readOnly||busy||(hasDirty&&!dirtyRegistry.has('kpi'))} onClick={()=>void saveKpis()}><Save size={15}/>KPI保存</button>{dirtyRegistry.has('kpi')&&<button className="button ghost" disabled={busy} onClick={discardKpis}><RotateCcw size={15}/>KPI変更を破棄</button>}</section>
      <section className="phase-progress" aria-label="Phase別完了率">{[0,1,2,3,4,5,6].map((value)=>{const phaseTasks=tasks.filter((task)=>task.phase===value),done=phaseTasks.filter((task)=>task.status==='完了').length,rate=Math.round(done/Math.max(phaseTasks.length,1)*100);return <button key={value} disabled={hasDirty} onClick={()=>{setPhase(String(value));setAppPage('tasks')}}><span>Phase {value}</span><b>{rate}%</b><i><em style={{width:`${rate}%`}}/></i></button>})}</section>
      <section className="weekly-status" aria-labelledby="weekly-status-title"><div><span className="eyebrow">WEEKLY CONTROL / ASIA-TOKYO</span><h2 id="weekly-status-title"><CalendarClock size={19}/>週次進行ループ</h2><dl><div><dt>最終週次更新</dt><dd>{lastRun?new Date(lastRun.ranAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'未実行'}</dd></div><div><dt>次回月曜 00:00</dt><dd>{new Date(schedule.nextScheduledFor).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}</dd></div><div><dt>追加付箋数</dt><dd>{lastRun?.addedStickyCount??0}</dd></div><div><dt>自動追加task数</dt><dd>{lastRun?.autoTaskCount??0}</dd></div></dl><p>{lastRun?`${lastRun.outcome} · ${lastRun.trigger} · 未実行週 ${lastRun.missedWeekCount} · ${lastRun.reasons[0]??'新規提案なし'}`:'起動時に当週分をcatch-upします。ブラウザ停止中の厳密00:00実行は保証されません。'}</p></div><button className="button primary" disabled={readOnly||busy} onClick={()=>void executeWeekly('manual')}><Play size={16}/>今すぐ週次更新</button></section>
      <div className="truth-note"><Activity size={18}/><p><b>正本: S4 / 300行 / SHA-256 D24C…BE87。</b> 旧schema v2タスクは移行アーカイブに保持し、集計へ混在させません。</p></div>
      </div></details>
      <div className="page-tabs-bar"><div className="page-tabs" role="tablist" aria-label="ページ切替">{nav.map((item)=>{const Icon=item.icon;return <button role="tab" aria-selected={page===item.id} key={item.id} disabled={navigationBlocked(item.id==='canvas'?'canvas':undefined)} className={page===item.id?'active':''} onClick={()=>setAppPage(item.id)}><Icon size={17}/>{item.label}</button>})}</div>{page==='tasks'&&taskMode==='all'&&<div className="view-switch"><button className={groupByTeam?'active':''} onClick={()=>setGroupByTeam((value)=>!value)} aria-label="チーム別表示"><UsersRound size={17}/></button><button className={view==='kanban'?'active':''} onClick={()=>setView('kanban')} aria-label="カード表示"><Columns3 size={17}/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')} aria-label="一覧表示"><List size={17}/></button></div>}</div>
      <div className="page-panel" key={page}>{page==='tasks'?<><div className="task-mode-tabs" role="tablist" aria-label="タスク表示"><button id="task-mode-quest" type="button" role="tab" aria-controls="task-mode-panel" aria-selected={taskMode==='quest'} tabIndex={taskMode==='quest'?0:-1} className={taskMode==='quest'?'active':''} onKeyDown={taskModeKey} onClick={()=>{setOperationsExpanded(false);setTaskMode('quest')}}><Play size={17}/>実行順</button><button id="task-mode-all" type="button" role="tab" aria-controls="task-mode-panel" aria-selected={taskMode==='all'} tabIndex={taskMode==='all'?0:-1} className={taskMode==='all'?'active':''} onKeyDown={taskModeKey} onClick={()=>setTaskMode('all')}><List size={17}/>全タスク</button></div><div id="task-mode-panel" role="tabpanel" aria-labelledby={`task-mode-${taskMode}`}>{taskMode==='quest'?<QuestBoard tasks={tasks} taskResults={taskResults} readOnly={readOnly} busy={busy} onResult={openResult} onStatus={changeStatus}/>:<TaskBoard tasks={tasks} taskResults={taskResults} view={view} search={search} department={department} status={status} phase={phase} person={person} dueView={dueView} groupByTeam={groupByTeam} readOnly={readOnly||busy} busy={busy} setSearch={setSearch} setDepartment={setDepartment} setStatus={setStatus} setPhase={setPhase} setPerson={setPerson} setDueView={setDueView} onAdd={()=>openModal()} onSave={saveInlineTask} onDirty={setTaskDirty} onResult={openResult} onDelete={removeTask} onStatus={changeStatus}/>}</div></>:page==='canvas'?<ProjectCanvas key={JSON.stringify(flow.nodes.map((node)=>node.id))} initialFlow={flow} tasks={tasks} taskResults={taskResults} readOnly={readOnly||busy} onDirty={setCanvasDirty} onOpenResult={(taskId)=>{const task=tasks.find((item)=>item.id===taskId);if(task)openResult(task)}} onSave={saveCanvas}/>:page==='report'?<ReportMode tasks={tasks} baseline={reportBaseline} onBaseline={saveReportBaseline} readOnly={readOnly||busy}/>:page==='result'&&tasks.find((task)=>task.id===resultTaskId)?<TaskResultSheet task={tasks.find((task)=>task.id===resultTaskId)!} sourceTask={tasks.find((task)=>task.id===tasks.find((item)=>item.id===resultTaskId)?.provenance?.sourceTaskId)} value={taskResults.find((item)=>item.taskId===resultTaskId)} readOnly={readOnly} busy={busy} error={error} dirty={dirtyRegistry.has('result')} onDirty={setResultDirty} onBack={()=>closeResult()} onDiscardAndBack={()=>closeResult(true)} onSave={saveResult}/>:<AuditLog items={audit}/>}</div>
    </main></div>{notice&&<div className="toast" role="status" aria-live="polite">{notice}</div>}{error&&<div className="toast error" role="alert" aria-live="assertive">{error}</div>}{modal.open&&<TaskModal task={modal.task} tasks={tasks} dirty={dirtyRegistry.has('modal')} onDirty={setModalDirty} onClose={()=>closeModal()} onDiscard={()=>closeModal(true)} onSave={saveModalTask}/>}</div>
}
