import { describe, expect, it } from 'vitest'
import { validateBundle } from './storage'
import { canonicalFingerprint } from './weekly'
import { generateWorkspaceDraft, moveWorkspaceTaskPhase, validateWorkspaceCreationInput, WORKSPACE_GENERATOR_VERSION, type WorkspaceCreationInput } from './workspace'

const input=(overrides:Partial<WorkspaceCreationInput>={}):WorkspaceCreationInput=>({organizationName:'スマートセールス研究所',slug:'smart-sales-lab',projectName:'営業支援SaaS公開',purpose:'営業担当者が安全に顧客情報を整理し、提案準備の時間を短縮できるサービスを公開する。',knownTasks:'顧客ヒアリングを実施する\n要件を確定する\n画面を制作する\n公開前テストを実行する\n利用結果を振り返る',phaseCount:5,taskTerm:'作業',phaseTerm:'段階',departmentTerm:'担当部門',...overrides})

describe('deterministic workspace generator',()=>{
  it('creates the same UTF-8 preview without copying the legacy P tasks',()=>{const at='2026-08-26T00:00:00.000Z',first=generateWorkspaceDraft(input(),at),second=generateWorkspaceDraft(input(),at);expect(first).toEqual(second);expect(first.profile.generatorVersion).toBe(WORKSPACE_GENERATOR_VERSION);expect(first.bundle.tasks).toHaveLength(5);expect(first.bundle.tasks.every((task)=>/^C[0-6]-\d{2}$/.test(task.id))).toBe(true);expect(first.bundle.tasks.some((task)=>task.title.includes('顧客ヒアリング'))).toBe(true);expect(first.config.phases).toHaveLength(5);expect(first.config.departments.length).toBeGreaterThanOrEqual(2);expect(first.config.departments.length).toBeLessThanOrEqual(12);expect(validateBundle(first.bundle,first.config)).toEqual([])})
  it('bounds phases, supplements sparse task text, and reports invalid input',()=>{const draft=generateWorkspaceDraft(input({knownTasks:'',phaseCount:7}), '2026-08-26T00:00:00.000Z');expect(draft.bundle.tasks.length).toBeGreaterThanOrEqual(5);expect(draft.bundle.tasks.length).toBeLessThanOrEqual(20);expect(draft.config.phases).toHaveLength(7);expect(validateWorkspaceCreationInput(input({purpose:'短い',slug:'INVALID'}))).toEqual(expect.arrayContaining(['識別子は英小文字・数字・ハイフンの1〜63文字です','目的は制御文字・空白・ゼロ幅文字だけではない20〜4000文字です']))})
  it('atomically rekeys every task reference when a custom task changes phase',()=>{const draft=generateWorkspaceDraft(input(),'2026-08-26T00:00:00.000Z'),before=draft.bundle.tasks[0],dependent=draft.bundle.tasks[1];draft.bundle.tasks[1]={...dependent,dependencies:[before.id]};draft.bundle.taskResults=[{id:`task-result:${before.id}`,taskId:before.id,resultBody:'result',verificationState:'未確認',verificationSummary:'',deliverables:[],nextStep:'',completionCriteria:'',verificationMemo:'',updatedAt:draft.bundle.exportedAt}];draft.bundle.reportBaseline={savedAt:draft.bundle.exportedAt,statuses:{[before.id]:{status:before.status,updatedAt:before.updatedAt}}};const moved=moveWorkspaceTaskPhase(draft.bundle,before.id,2),after=moved.tasks[0];expect(after.phase).toBe(2);expect(after.id).toMatch(/^C2-/);expect(after.id).not.toBe(before.id);expect(moved.tasks[1].dependencies).toEqual([after.id]);expect(moved.taskResults?.[0]).toMatchObject({id:`task-result:${after.id}`,taskId:after.id});expect(moved.reportBaseline?.statuses[after.id]).toBeDefined();expect(moved.flow.nodes.find((node)=>node.id==='phase-2')?.data.taskIds).toContain(after.id);expect(validateBundle(moved,draft.config)).toEqual([])})
  it('rekeys weekly provenance fingerprints and tombstones with the moved task',()=>{const draft=generateWorkspaceDraft(input(),'2026-08-26T00:00:00.000Z'),weekly=structuredClone(draft.bundle),before=weekly.tasks[0],provenance={ruleId:'test-move',sourceTaskId:before.id,dependencyIds:[]},automatic={...weekly.tasks[1],id:'AUTO-2026-W35-99',sourceRefs:[],dependencies:[],createdBy:'esports_progress_control' as const,createdByDepartment:'esports_progress_control' as const,createdRunId:'weekly:2026-W35',reason:'move reference test',expectedDeliverable:'reference evidence',provenance,fingerprint:canonicalFingerprint(provenance),rationaleCodes:['TEST'],approvalState:'要確認' as const,automationDisabled:false};weekly.tasks.push(automatic);weekly.weekly.tombstones=[automatic.fingerprint];const moved=moveWorkspaceTaskPhase(weekly,before.id,2),nextAutomatic=moved.tasks.find((task)=>task.id===automatic.id)!;expect(nextAutomatic.provenance?.sourceTaskId).toBe(moved.tasks[0].id);expect(nextAutomatic.fingerprint).toBe(canonicalFingerprint(nextAutomatic.provenance!));expect(moved.weekly.tombstones).toEqual([nextAutomatic.fingerprint]);expect(validateBundle(moved,draft.config)).toEqual([])})
  it('rejects zero-width-only user text',()=>{expect(validateWorkspaceCreationInput(input({organizationName:'\u200b',projectName:'\u200d',purpose:'\u200b'.repeat(20)})).length).toBeGreaterThanOrEqual(3)})
})
